// Code generated by ent, DO NOT EDIT.

package importtemplate

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the importtemplate type in the database.
	Label = "import_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDepartmentID holds the string denoting the department_id field in the database.
	FieldDepartmentID = "department_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldImportMode holds the string denoting the import_mode field in the database.
	FieldImportMode = "import_mode"
	// FieldCiTypeID holds the string denoting the ci_type_id field in the database.
	FieldCiTypeID = "ci_type_id"
	// FieldCiTypeName holds the string denoting the ci_type_name field in the database.
	FieldCiTypeName = "ci_type_name"
	// FieldAutoCreateCiType holds the string denoting the auto_create_ci_type field in the database.
	FieldAutoCreateCiType = "auto_create_ci_type"
	// FieldFieldMappings holds the string denoting the field_mappings field in the database.
	FieldFieldMappings = "field_mappings"
	// FieldHeaderMappings holds the string denoting the header_mappings field in the database.
	FieldHeaderMappings = "header_mappings"
	// FieldDefaultValues holds the string denoting the default_values field in the database.
	FieldDefaultValues = "default_values"
	// FieldComputedFields holds the string denoting the computed_fields field in the database.
	FieldComputedFields = "computed_fields"
	// FieldDataTransformations holds the string denoting the data_transformations field in the database.
	FieldDataTransformations = "data_transformations"
	// FieldDataFilters holds the string denoting the data_filters field in the database.
	FieldDataFilters = "data_filters"
	// FieldDataCleaners holds the string denoting the data_cleaners field in the database.
	FieldDataCleaners = "data_cleaners"
	// FieldExcelSheetName holds the string denoting the excel_sheet_name field in the database.
	FieldExcelSheetName = "excel_sheet_name"
	// FieldExcelHeaderRow holds the string denoting the excel_header_row field in the database.
	FieldExcelHeaderRow = "excel_header_row"
	// FieldExcelDataStartRow holds the string denoting the excel_data_start_row field in the database.
	FieldExcelDataStartRow = "excel_data_start_row"
	// FieldExcelColumnMappings holds the string denoting the excel_column_mappings field in the database.
	FieldExcelColumnMappings = "excel_column_mappings"
	// FieldAPIEndpoint holds the string denoting the api_endpoint field in the database.
	FieldAPIEndpoint = "api_endpoint"
	// FieldAPIMethod holds the string denoting the api_method field in the database.
	FieldAPIMethod = "api_method"
	// FieldAPIHeaders holds the string denoting the api_headers field in the database.
	FieldAPIHeaders = "api_headers"
	// FieldAPIParams holds the string denoting the api_params field in the database.
	FieldAPIParams = "api_params"
	// FieldAPIResponsePath holds the string denoting the api_response_path field in the database.
	FieldAPIResponsePath = "api_response_path"
	// FieldMaxErrors holds the string denoting the max_errors field in the database.
	FieldMaxErrors = "max_errors"
	// FieldStopOnFirstError holds the string denoting the stop_on_first_error field in the database.
	FieldStopOnFirstError = "stop_on_first_error"
	// FieldSkipInvalidRows holds the string denoting the skip_invalid_rows field in the database.
	FieldSkipInvalidRows = "skip_invalid_rows"
	// FieldErrorHandlingMode holds the string denoting the error_handling_mode field in the database.
	FieldErrorHandlingMode = "error_handling_mode"
	// FieldBatchSize holds the string denoting the batch_size field in the database.
	FieldBatchSize = "batch_size"
	// FieldMaxParallelJobs holds the string denoting the max_parallel_jobs field in the database.
	FieldMaxParallelJobs = "max_parallel_jobs"
	// FieldEnableTransaction holds the string denoting the enable_transaction field in the database.
	FieldEnableTransaction = "enable_transaction"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldUsageCount holds the string denoting the usage_count field in the database.
	FieldUsageCount = "usage_count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldErrorCount holds the string denoting the error_count field in the database.
	FieldErrorCount = "error_count"
	// FieldSuccessRate holds the string denoting the success_rate field in the database.
	FieldSuccessRate = "success_rate"
	// FieldIsPublic holds the string denoting the is_public field in the database.
	FieldIsPublic = "is_public"
	// FieldIsSystem holds the string denoting the is_system field in the database.
	FieldIsSystem = "is_system"
	// FieldSharedWith holds the string denoting the shared_with field in the database.
	FieldSharedWith = "shared_with"
	// FieldCreatedByName holds the string denoting the created_by_name field in the database.
	FieldCreatedByName = "created_by_name"
	// FieldApprovedBy holds the string denoting the approved_by field in the database.
	FieldApprovedBy = "approved_by"
	// FieldApprovedByName holds the string denoting the approved_by_name field in the database.
	FieldApprovedByName = "approved_by_name"
	// FieldApprovedAt holds the string denoting the approved_at field in the database.
	FieldApprovedAt = "approved_at"
	// EdgeCiType holds the string denoting the ci_type edge name in mutations.
	EdgeCiType = "ci_type"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the importtemplate in the database.
	Table = "cmdb_import_templates"
	// CiTypeTable is the table that holds the ci_type relation/edge.
	CiTypeTable = "cmdb_import_templates"
	// CiTypeInverseTable is the table name for the CiType entity.
	// It exists in this package in order to avoid circular dependency with the "citype" package.
	CiTypeInverseTable = "cmdb_ci_types"
	// CiTypeColumn is the table column denoting the ci_type relation/edge.
	CiTypeColumn = "ci_type_id"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "cmdb_import_tasks"
	// TasksInverseTable is the table name for the ImportTask entity.
	// It exists in this package in order to avoid circular dependency with the "importtask" package.
	TasksInverseTable = "cmdb_import_tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "template_id"
)

// Columns holds all SQL columns for importtemplate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStatus,
	FieldDeletedAt,
	FieldTenantID,
	FieldDepartmentID,
	FieldCreatedBy,
	FieldName,
	FieldCode,
	FieldDescription,
	FieldVersion,
	FieldType,
	FieldImportMode,
	FieldCiTypeID,
	FieldCiTypeName,
	FieldAutoCreateCiType,
	FieldFieldMappings,
	FieldHeaderMappings,
	FieldDefaultValues,
	FieldComputedFields,
	FieldDataTransformations,
	FieldDataFilters,
	FieldDataCleaners,
	FieldExcelSheetName,
	FieldExcelHeaderRow,
	FieldExcelDataStartRow,
	FieldExcelColumnMappings,
	FieldAPIEndpoint,
	FieldAPIMethod,
	FieldAPIHeaders,
	FieldAPIParams,
	FieldAPIResponsePath,
	FieldMaxErrors,
	FieldStopOnFirstError,
	FieldSkipInvalidRows,
	FieldErrorHandlingMode,
	FieldBatchSize,
	FieldMaxParallelJobs,
	FieldEnableTransaction,
	FieldTags,
	FieldMetadata,
	FieldIcon,
	FieldCategory,
	FieldUsageCount,
	FieldSuccessCount,
	FieldErrorCount,
	FieldSuccessRate,
	FieldIsPublic,
	FieldIsSystem,
	FieldSharedWith,
	FieldCreatedByName,
	FieldApprovedBy,
	FieldApprovedByName,
	FieldApprovedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/coder-lulu/newbee-cmdb-rpc/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint64
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion string
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// CiTypeNameValidator is a validator for the "ci_type_name" field. It is called by the builders before save.
	CiTypeNameValidator func(string) error
	// DefaultAutoCreateCiType holds the default value on creation for the "auto_create_ci_type" field.
	DefaultAutoCreateCiType bool
	// ExcelSheetNameValidator is a validator for the "excel_sheet_name" field. It is called by the builders before save.
	ExcelSheetNameValidator func(string) error
	// DefaultExcelHeaderRow holds the default value on creation for the "excel_header_row" field.
	DefaultExcelHeaderRow int
	// DefaultExcelDataStartRow holds the default value on creation for the "excel_data_start_row" field.
	DefaultExcelDataStartRow int
	// APIEndpointValidator is a validator for the "api_endpoint" field. It is called by the builders before save.
	APIEndpointValidator func(string) error
	// APIResponsePathValidator is a validator for the "api_response_path" field. It is called by the builders before save.
	APIResponsePathValidator func(string) error
	// DefaultMaxErrors holds the default value on creation for the "max_errors" field.
	DefaultMaxErrors int
	// DefaultStopOnFirstError holds the default value on creation for the "stop_on_first_error" field.
	DefaultStopOnFirstError bool
	// DefaultSkipInvalidRows holds the default value on creation for the "skip_invalid_rows" field.
	DefaultSkipInvalidRows bool
	// DefaultBatchSize holds the default value on creation for the "batch_size" field.
	DefaultBatchSize int
	// DefaultMaxParallelJobs holds the default value on creation for the "max_parallel_jobs" field.
	DefaultMaxParallelJobs int
	// DefaultEnableTransaction holds the default value on creation for the "enable_transaction" field.
	DefaultEnableTransaction bool
	// IconValidator is a validator for the "icon" field. It is called by the builders before save.
	IconValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultUsageCount holds the default value on creation for the "usage_count" field.
	DefaultUsageCount int
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int
	// DefaultErrorCount holds the default value on creation for the "error_count" field.
	DefaultErrorCount int
	// DefaultSuccessRate holds the default value on creation for the "success_rate" field.
	DefaultSuccessRate float64
	// DefaultIsPublic holds the default value on creation for the "is_public" field.
	DefaultIsPublic bool
	// DefaultIsSystem holds the default value on creation for the "is_system" field.
	DefaultIsSystem bool
	// CreatedByNameValidator is a validator for the "created_by_name" field. It is called by the builders before save.
	CreatedByNameValidator func(string) error
	// ApprovedByNameValidator is a validator for the "approved_by_name" field. It is called by the builders before save.
	ApprovedByNameValidator func(string) error
)

// Type defines the type for the "type" enum field.
type Type string

// TypeExcel is the default value of the Type enum.
const DefaultType = TypeExcel

// Type values.
const (
	TypeExcel Type = "excel"
	TypeCsv   Type = "csv"
	TypeJSON  Type = "json"
	TypeAPI   Type = "api"
	TypeXML   Type = "xml"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeExcel, TypeCsv, TypeJSON, TypeAPI, TypeXML:
		return nil
	default:
		return fmt.Errorf("importtemplate: invalid enum value for type field: %q", _type)
	}
}

// ImportMode defines the type for the "import_mode" enum field.
type ImportMode string

// ImportModeUpsert is the default value of the ImportMode enum.
const DefaultImportMode = ImportModeUpsert

// ImportMode values.
const (
	ImportModeCreateOnly ImportMode = "create_only"
	ImportModeUpdateOnly ImportMode = "update_only"
	ImportModeUpsert     ImportMode = "upsert"
	ImportModeMerge      ImportMode = "merge"
)

func (im ImportMode) String() string {
	return string(im)
}

// ImportModeValidator is a validator for the "import_mode" field enum values. It is called by the builders before save.
func ImportModeValidator(im ImportMode) error {
	switch im {
	case ImportModeCreateOnly, ImportModeUpdateOnly, ImportModeUpsert, ImportModeMerge:
		return nil
	default:
		return fmt.Errorf("importtemplate: invalid enum value for import_mode field: %q", im)
	}
}

// APIMethod defines the type for the "api_method" enum field.
type APIMethod string

// APIMethod values.
const (
	APIMethodGET   APIMethod = "GET"
	APIMethodPOST  APIMethod = "POST"
	APIMethodPUT   APIMethod = "PUT"
	APIMethodPATCH APIMethod = "PATCH"
)

func (am APIMethod) String() string {
	return string(am)
}

// APIMethodValidator is a validator for the "api_method" field enum values. It is called by the builders before save.
func APIMethodValidator(am APIMethod) error {
	switch am {
	case APIMethodGET, APIMethodPOST, APIMethodPUT, APIMethodPATCH:
		return nil
	default:
		return fmt.Errorf("importtemplate: invalid enum value for api_method field: %q", am)
	}
}

// ErrorHandlingMode defines the type for the "error_handling_mode" enum field.
type ErrorHandlingMode string

// ErrorHandlingModeLenient is the default value of the ErrorHandlingMode enum.
const DefaultErrorHandlingMode = ErrorHandlingModeLenient

// ErrorHandlingMode values.
const (
	ErrorHandlingModeStrict  ErrorHandlingMode = "strict"
	ErrorHandlingModeLenient ErrorHandlingMode = "lenient"
	ErrorHandlingModeCustom  ErrorHandlingMode = "custom"
)

func (ehm ErrorHandlingMode) String() string {
	return string(ehm)
}

// ErrorHandlingModeValidator is a validator for the "error_handling_mode" field enum values. It is called by the builders before save.
func ErrorHandlingModeValidator(ehm ErrorHandlingMode) error {
	switch ehm {
	case ErrorHandlingModeStrict, ErrorHandlingModeLenient, ErrorHandlingModeCustom:
		return nil
	default:
		return fmt.Errorf("importtemplate: invalid enum value for error_handling_mode field: %q", ehm)
	}
}

// OrderOption defines the ordering options for the ImportTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDepartmentID orders the results by the department_id field.
func ByDepartmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartmentID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByImportMode orders the results by the import_mode field.
func ByImportMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportMode, opts...).ToFunc()
}

// ByCiTypeID orders the results by the ci_type_id field.
func ByCiTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCiTypeID, opts...).ToFunc()
}

// ByCiTypeName orders the results by the ci_type_name field.
func ByCiTypeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCiTypeName, opts...).ToFunc()
}

// ByAutoCreateCiType orders the results by the auto_create_ci_type field.
func ByAutoCreateCiType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoCreateCiType, opts...).ToFunc()
}

// ByExcelSheetName orders the results by the excel_sheet_name field.
func ByExcelSheetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExcelSheetName, opts...).ToFunc()
}

// ByExcelHeaderRow orders the results by the excel_header_row field.
func ByExcelHeaderRow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExcelHeaderRow, opts...).ToFunc()
}

// ByExcelDataStartRow orders the results by the excel_data_start_row field.
func ByExcelDataStartRow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExcelDataStartRow, opts...).ToFunc()
}

// ByAPIEndpoint orders the results by the api_endpoint field.
func ByAPIEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIEndpoint, opts...).ToFunc()
}

// ByAPIMethod orders the results by the api_method field.
func ByAPIMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIMethod, opts...).ToFunc()
}

// ByAPIResponsePath orders the results by the api_response_path field.
func ByAPIResponsePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIResponsePath, opts...).ToFunc()
}

// ByMaxErrors orders the results by the max_errors field.
func ByMaxErrors(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxErrors, opts...).ToFunc()
}

// ByStopOnFirstError orders the results by the stop_on_first_error field.
func ByStopOnFirstError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStopOnFirstError, opts...).ToFunc()
}

// BySkipInvalidRows orders the results by the skip_invalid_rows field.
func BySkipInvalidRows(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipInvalidRows, opts...).ToFunc()
}

// ByErrorHandlingMode orders the results by the error_handling_mode field.
func ByErrorHandlingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorHandlingMode, opts...).ToFunc()
}

// ByBatchSize orders the results by the batch_size field.
func ByBatchSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchSize, opts...).ToFunc()
}

// ByMaxParallelJobs orders the results by the max_parallel_jobs field.
func ByMaxParallelJobs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxParallelJobs, opts...).ToFunc()
}

// ByEnableTransaction orders the results by the enable_transaction field.
func ByEnableTransaction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableTransaction, opts...).ToFunc()
}

// ByIcon orders the results by the icon field.
func ByIcon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIcon, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByUsageCount orders the results by the usage_count field.
func ByUsageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByErrorCount orders the results by the error_count field.
func ByErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCount, opts...).ToFunc()
}

// BySuccessRate orders the results by the success_rate field.
func BySuccessRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessRate, opts...).ToFunc()
}

// ByIsPublic orders the results by the is_public field.
func ByIsPublic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublic, opts...).ToFunc()
}

// ByIsSystem orders the results by the is_system field.
func ByIsSystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSystem, opts...).ToFunc()
}

// ByCreatedByName orders the results by the created_by_name field.
func ByCreatedByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByName, opts...).ToFunc()
}

// ByApprovedBy orders the results by the approved_by field.
func ByApprovedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedBy, opts...).ToFunc()
}

// ByApprovedByName orders the results by the approved_by_name field.
func ByApprovedByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedByName, opts...).ToFunc()
}

// ByApprovedAt orders the results by the approved_at field.
func ByApprovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedAt, opts...).ToFunc()
}

// ByCiTypeField orders the results by ci_type field.
func ByCiTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCiTypeStep(), sql.OrderByField(field, opts...))
	}
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCiTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CiTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CiTypeTable, CiTypeColumn),
	)
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
