// Code generated by ent, DO NOT EDIT.

package cirelation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldDeletedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldTenantID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldDepartmentID, v))
}

// FirstCiID applies equality check predicate on the "first_ci_id" field. It's identical to FirstCiIDEQ.
func FirstCiID(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldFirstCiID, v))
}

// SecondCiID applies equality check predicate on the "second_ci_id" field. It's identical to SecondCiIDEQ.
func SecondCiID(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldSecondCiID, v))
}

// RelationTypeID applies equality check predicate on the "relation_type_id" field. It's identical to RelationTypeIDEQ.
func RelationTypeID(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldRelationTypeID, v))
}

// More applies equality check predicate on the "more" field. It's identical to MoreEQ.
func More(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldMore, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldSource, v))
}

// AncestorIds applies equality check predicate on the "ancestor_ids" field. It's identical to AncestorIdsEQ.
func AncestorIds(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldAncestorIds, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotNull(FieldDeletedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldTenantID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldDepartmentID, v))
}

// DepartmentIDIsNil applies the IsNil predicate on the "department_id" field.
func DepartmentIDIsNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIsNull(FieldDepartmentID))
}

// DepartmentIDNotNil applies the NotNil predicate on the "department_id" field.
func DepartmentIDNotNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotNull(FieldDepartmentID))
}

// FirstCiIDEQ applies the EQ predicate on the "first_ci_id" field.
func FirstCiIDEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldFirstCiID, v))
}

// FirstCiIDNEQ applies the NEQ predicate on the "first_ci_id" field.
func FirstCiIDNEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldFirstCiID, v))
}

// FirstCiIDIn applies the In predicate on the "first_ci_id" field.
func FirstCiIDIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldFirstCiID, vs...))
}

// FirstCiIDNotIn applies the NotIn predicate on the "first_ci_id" field.
func FirstCiIDNotIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldFirstCiID, vs...))
}

// SecondCiIDEQ applies the EQ predicate on the "second_ci_id" field.
func SecondCiIDEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldSecondCiID, v))
}

// SecondCiIDNEQ applies the NEQ predicate on the "second_ci_id" field.
func SecondCiIDNEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldSecondCiID, v))
}

// SecondCiIDIn applies the In predicate on the "second_ci_id" field.
func SecondCiIDIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldSecondCiID, vs...))
}

// SecondCiIDNotIn applies the NotIn predicate on the "second_ci_id" field.
func SecondCiIDNotIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldSecondCiID, vs...))
}

// RelationTypeIDEQ applies the EQ predicate on the "relation_type_id" field.
func RelationTypeIDEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldRelationTypeID, v))
}

// RelationTypeIDNEQ applies the NEQ predicate on the "relation_type_id" field.
func RelationTypeIDNEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldRelationTypeID, v))
}

// RelationTypeIDIn applies the In predicate on the "relation_type_id" field.
func RelationTypeIDIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldRelationTypeID, vs...))
}

// RelationTypeIDNotIn applies the NotIn predicate on the "relation_type_id" field.
func RelationTypeIDNotIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldRelationTypeID, vs...))
}

// MoreEQ applies the EQ predicate on the "more" field.
func MoreEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldMore, v))
}

// MoreNEQ applies the NEQ predicate on the "more" field.
func MoreNEQ(v uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldMore, v))
}

// MoreIn applies the In predicate on the "more" field.
func MoreIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldMore, vs...))
}

// MoreNotIn applies the NotIn predicate on the "more" field.
func MoreNotIn(vs ...uint64) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldMore, vs...))
}

// MoreIsNil applies the IsNil predicate on the "more" field.
func MoreIsNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIsNull(FieldMore))
}

// MoreNotNil applies the NotNil predicate on the "more" field.
func MoreNotNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotNull(FieldMore))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldHasSuffix(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotNull(FieldSource))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldContainsFold(FieldSource, v))
}

// AncestorIdsEQ applies the EQ predicate on the "ancestor_ids" field.
func AncestorIdsEQ(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEQ(FieldAncestorIds, v))
}

// AncestorIdsNEQ applies the NEQ predicate on the "ancestor_ids" field.
func AncestorIdsNEQ(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNEQ(FieldAncestorIds, v))
}

// AncestorIdsIn applies the In predicate on the "ancestor_ids" field.
func AncestorIdsIn(vs ...string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIn(FieldAncestorIds, vs...))
}

// AncestorIdsNotIn applies the NotIn predicate on the "ancestor_ids" field.
func AncestorIdsNotIn(vs ...string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotIn(FieldAncestorIds, vs...))
}

// AncestorIdsGT applies the GT predicate on the "ancestor_ids" field.
func AncestorIdsGT(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGT(FieldAncestorIds, v))
}

// AncestorIdsGTE applies the GTE predicate on the "ancestor_ids" field.
func AncestorIdsGTE(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldGTE(FieldAncestorIds, v))
}

// AncestorIdsLT applies the LT predicate on the "ancestor_ids" field.
func AncestorIdsLT(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLT(FieldAncestorIds, v))
}

// AncestorIdsLTE applies the LTE predicate on the "ancestor_ids" field.
func AncestorIdsLTE(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldLTE(FieldAncestorIds, v))
}

// AncestorIdsContains applies the Contains predicate on the "ancestor_ids" field.
func AncestorIdsContains(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldContains(FieldAncestorIds, v))
}

// AncestorIdsHasPrefix applies the HasPrefix predicate on the "ancestor_ids" field.
func AncestorIdsHasPrefix(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldHasPrefix(FieldAncestorIds, v))
}

// AncestorIdsHasSuffix applies the HasSuffix predicate on the "ancestor_ids" field.
func AncestorIdsHasSuffix(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldHasSuffix(FieldAncestorIds, v))
}

// AncestorIdsIsNil applies the IsNil predicate on the "ancestor_ids" field.
func AncestorIdsIsNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldIsNull(FieldAncestorIds))
}

// AncestorIdsNotNil applies the NotNil predicate on the "ancestor_ids" field.
func AncestorIdsNotNil() predicate.CiRelation {
	return predicate.CiRelation(sql.FieldNotNull(FieldAncestorIds))
}

// AncestorIdsEqualFold applies the EqualFold predicate on the "ancestor_ids" field.
func AncestorIdsEqualFold(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldEqualFold(FieldAncestorIds, v))
}

// AncestorIdsContainsFold applies the ContainsFold predicate on the "ancestor_ids" field.
func AncestorIdsContainsFold(v string) predicate.CiRelation {
	return predicate.CiRelation(sql.FieldContainsFold(FieldAncestorIds, v))
}

// HasFirstCi applies the HasEdge predicate on the "first_ci" edge.
func HasFirstCi() predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FirstCiTable, FirstCiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFirstCiWith applies the HasEdge predicate on the "first_ci" edge with a given conditions (other predicates).
func HasFirstCiWith(preds ...predicate.Cis) predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := newFirstCiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSecondCi applies the HasEdge predicate on the "second_ci" edge.
func HasSecondCi() predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SecondCiTable, SecondCiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSecondCiWith applies the HasEdge predicate on the "second_ci" edge with a given conditions (other predicates).
func HasSecondCiWith(preds ...predicate.Cis) predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := newSecondCiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationType applies the HasEdge predicate on the "relation_type" edge.
func HasRelationType() predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RelationTypeTable, RelationTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationTypeWith applies the HasEdge predicate on the "relation_type" edge with a given conditions (other predicates).
func HasRelationTypeWith(preds ...predicate.RelationType) predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := newRelationTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMoreCi applies the HasEdge predicate on the "more_ci" edge.
func HasMoreCi() predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MoreCiTable, MoreCiColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMoreCiWith applies the HasEdge predicate on the "more_ci" edge with a given conditions (other predicates).
func HasMoreCiWith(preds ...predicate.Cis) predicate.CiRelation {
	return predicate.CiRelation(func(s *sql.Selector) {
		step := newMoreCiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CiRelation) predicate.CiRelation {
	return predicate.CiRelation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CiRelation) predicate.CiRelation {
	return predicate.CiRelation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CiRelation) predicate.CiRelation {
	return predicate.CiRelation(sql.NotPredicates(p))
}
