syntax = "proto3";

// ChoiceInteger message

message ChoiceIntegerInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // 外键，关联cmdb_attributes.id
  optional uint64 attr_id = 4;
  // 选项值
  optional int64 value = 5;
  // 选项内容
  optional AttributeChoiceItemMeta option = 6;
}

message ChoiceIntegerListResp {
  uint64 total = 1;
  repeated ChoiceIntegerInfo data = 2;
}

message ChoiceIntegerListReq {
  uint64 page = 1;
  uint64 page_size = 2;
  optional int64 created_at = 3;
  optional int64 updated_at = 4;
  optional int64 deleted_at = 5;
  optional uint64 attr_id = 6;
  optional int64 value = 7;
  optional AttributeChoiceItemMeta option = 8;
}


service Cmdb {

  // ChoiceInteger management
  // group: choiceinteger
  rpc createChoiceInteger (ChoiceIntegerInfo) returns (BaseIDResp);
  // group: choiceinteger
  rpc updateChoiceInteger (ChoiceIntegerInfo) returns (BaseResp);
  // group: choiceinteger
  rpc getChoiceIntegerList (ChoiceIntegerListReq) returns (ChoiceIntegerListResp);
  // group: choiceinteger
  rpc getChoiceIntegerById (IDReq) returns (ChoiceIntegerInfo);
  // group: choiceinteger
  rpc deleteChoiceInteger (IDsReq) returns (BaseResp);


}