syntax = "proto3";

// CiTypeInheritance message

message CiTypeInheritanceInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // 外键，关联cmdb_ci_types.id，父类型
  optional uint64 parent_id = 4;
  // 外键，关联cmdb_ci_types.id，子类型
  optional uint64 child_id = 5;
}

message CiTypeInheritanceListResp {
  uint64 total = 1;
  repeated CiTypeInheritanceInfo data = 2;
}

message CiTypeInheritanceListReq {
  uint64 page = 1;
  uint64 page_size = 2;
  optional int64 created_at = 3;
  optional int64 updated_at = 4;
  optional int64 deleted_at = 5;
  optional uint64 parent_id = 6;
  optional uint64 child_id = 7;
}


service Cmdb {

  // CiTypeInheritance management
  // group: citypeinheritance
  rpc createCiTypeInheritance (CiTypeInheritanceInfo) returns (BaseIDResp);
  // group: citypeinheritance
  rpc updateCiTypeInheritance (CiTypeInheritanceInfo) returns (BaseResp);
  // group: citypeinheritance
  rpc getCiTypeInheritanceList (CiTypeInheritanceListReq) returns (CiTypeInheritanceListResp);
  // group: citypeinheritance
  rpc getCiTypeInheritanceById (IDReq) returns (CiTypeInheritanceInfo);
  // group: citypeinheritance
  rpc deleteCiTypeInheritance (IDsReq) returns (BaseResp);


}