syntax = "proto3";

// CiTypeRelation message

message CiTypeRelationInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // 外键，关联cmdb_ci_types.id，父类型
  optional uint64 parent_id = 4;
  // 外键，关联cmdb_ci_types.id，子类型
  optional uint64 child_id = 5;
  // 外键，关联cmdb_relation_types.id
  optional uint64 relation_type_id = 6;
  // 约束，枚举类
  optional string constraint = 7;
  // 父类型属性ID
  optional uint64 parent_attr_id = 8;
  // 子类型属性ID
  optional uint64 child_attr_id = 9;
  // 父类型属性ID数组
  repeated uint64 parent_attr_ids = 10;
  // 子类型属性ID数组
  repeated uint64 child_attr_ids = 11;
}

message CiTypeRelationListResp {
  uint64 total = 1;
  repeated CiTypeRelationInfo data = 2;
}

message CiTypeRelationListReq {
  uint64 page = 1;
  uint64 page_size = 2;
  optional int64 created_at = 3;
  optional int64 updated_at = 4;
  optional int64 deleted_at = 5;
  optional uint64 parent_id = 6;
  optional uint64 child_id = 7;
  optional uint64 relation_type_id = 8;
  optional string constraint = 9;
  optional uint64 parent_attr_id = 10;
  optional uint64 child_attr_id = 11;
  repeated uint64 parent_attr_ids = 12;
  repeated uint64 child_attr_ids = 13;
}


service Cmdb {

  // CiTypeRelation management
  // group: cityperelation
  rpc createCiTypeRelation (CiTypeRelationInfo) returns (BaseIDResp);
  // group: cityperelation
  rpc updateCiTypeRelation (CiTypeRelationInfo) returns (BaseResp);
  // group: cityperelation
  rpc getCiTypeRelationList (CiTypeRelationListReq) returns (CiTypeRelationListResp);
  // group: cityperelation
  rpc getCiTypeRelationById (IDReq) returns (CiTypeRelationInfo);
  // group: cityperelation
  rpc deleteCiTypeRelation (IDsReq) returns (BaseResp);


}