syntax = "proto3";

// CiTypeAttribute message

message CiTypeAttributeInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // 外键，关联cmdb_ci_types.id
  optional uint64 type_id = 5;
  // 外键，关联cmdb_attributes.id
  optional uint64 attr_id = 6;
  // 是否必填
  optional bool is_required = 7;
  // 是否唯一
  optional bool is_unique = 8;
  // 是否列表
  optional bool is_list = 9;
  // 是否列表展示
  optional bool list_show = 10;
  // 是否详情展示
  optional bool detail_show = 11; 
  // 是否可编辑
  optional bool is_edit = 12;
}

message CiTypeAttributeListResp {
  uint64 total = 1;
  repeated CiTypeAttributeItem data = 2;
}

message CiTypeAttributeListReq {
  uint64 page = 1;
  uint64 page_size = 2;
  optional int64 created_at = 3;
  optional int64 updated_at = 4;
  optional int64 deleted_at = 5;
  optional uint32 sort = 6;
  optional uint64 type_id = 7;
  optional uint64 attr_id = 8;
  optional bool is_required = 9;
  optional bool list_show = 10;
}

message CiTypeAttributeListWithGroupReq {
  uint64 type_id = 1;
}

// 主属性项
message CiTypeAttributeItem {
  AttributeInfo attribute = 1;
  optional uint64 group_id = 2;
  uint64 type_id = 3;
  optional bool is_required = 4;
  optional bool is_edit = 5;
  optional bool list_show = 6;
  optional bool detail_show = 7;
  optional uint64 id = 8;
  optional uint32 sort = 9;
  optional uint64 ci_type_attribute_id = 10;
  optional bool is_unique = 11;
  optional bool is_inherited = 12;
}

message CiTypeAttributeListWithGroupInfo {
  uint64 group_id = 1;
  uint32 sort = 2;
  string name = 3;
  uint64 type_id = 4;
  repeated CiTypeAttributeItem attributes = 5;
}

message CiTypeAttributeListWithGroupResp {
  repeated CiTypeAttributeListWithGroupInfo data = 1;
}

message CiTypeAttributeChangeDefaultShowReq {
  uint64 ci_type_attribute_id = 1;
  bool list_show = 2;
}

service Cmdb {

  // CiTypeAttribute management
  // group: citypeattribute
  rpc createCiTypeAttribute (CiTypeAttributeItem) returns (BaseResp);
  // group: citypeattribute
  rpc updateCiTypeAttribute (CiTypeAttributeItem) returns (BaseResp);
  // group: citypeattribute
  rpc getCiTypeAttributeList (CiTypeAttributeListReq) returns (CiTypeAttributeListResp);
  // group: citypeattribute
  rpc getCiTypeAttributeById (IDReq) returns (CiTypeAttributeItem);
  // group: citypeattribute
  rpc deleteCiTypeAttribute (IDsReq) returns (BaseResp);

  // group: citypeattribute
  rpc getCiTypeAttributeListWithGroup (CiTypeAttributeListWithGroupReq) returns (CiTypeAttributeListWithGroupResp);
  // group: citypeattribute
  rpc changeCiTypeAttributeDefaultShow (CiTypeAttributeChangeDefaultShowReq) returns (BaseResp);

}