syntax = "proto3";

// CiType message
 
message CiTypeInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // Status 1: normal 2: ban | 状态 1 正常 2 禁用
  optional uint32 status = 4;
  // Sort Number | 排序编号
  optional uint32 sort = 5;
  // 名称
  optional string name = 6;
  // 别名
  optional string alias = 7;
  // 外键，关联c_attributes.id
  optional uint64 unique_id = 8;
  // 是否继承
  optional bool is_inherited = 9;
  // 创建者
  optional string created_by = 10;
  // 图标
  optional string icon = 11;
  // 默认排序属性
  optional uint64 default_order_attr = 12;
  // 展示ID
  optional uint64 show_id = 13;
  // 唯一性约束
  repeated  CiTypeUniqueConst unique_const = 14;
  // 分组ID
  optional uint64 group_id = 15;
  // 继承的模型列表
  repeated uint64 inherited_models = 16;

}

message CiTypeUniqueConst {
  repeated uint64 attr_ids = 1;
}

message CiTypeListResp {
  uint64 total = 1;
  repeated CiTypeInfo data = 2;
}

message CiTypeListReq {
  optional int64 created_at = 1;
  optional int64 updated_at = 2;
  optional uint32 status = 3;
  optional uint32 sort = 4;
  optional int64 deleted_at = 5;
  optional string name = 6;
  optional string alias = 7;
  optional uint64 unique_id = 8;
  optional bool is_inherited = 9;
  optional string created_by = 10;
  optional string icon = 11;
  optional uint64 default_order_attr = 12;
  optional uint64 show_id = 13;
  optional uint64 group_id = 14;
}

message CiTypeAppendAttributeReq {
  optional uint64 type_id = 1;
  repeated uint64 attr_ids = 2;
  optional uint64 group_id = 3;
}


service Cmdb {

  // CiType management
  // group: citype
  rpc createCiType (CiTypeInfo) returns (BaseIDResp);
  // group: citype
  rpc updateCiType (CiTypeInfo) returns (BaseResp);
  // group: citype
  rpc getCiTypeList (CiTypeListReq) returns (CiTypeListResp);
  // group: citype
  rpc getCiTypeById (IDReq) returns (CiTypeInfo);
  // group: citype
  rpc deleteCiType (IDsReq) returns (BaseResp);

  // group: citype
  rpc appendAttribute (CiTypeAppendAttributeReq) returns (BaseResp);


}