syntax = "proto3";

// ValueText message

message ValueTextInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // 外键，关联cmdb_cis.id
  optional uint64 ci_id = 4;
  // 外键，关联cmdb_attributes.id
  optional uint64 attr_id = 5;
  // 属性值
  optional string value = 6;
  // 是否可被覆盖
  optional bool is_cover = 7;
}

message ValueTextListResp {
  uint64 total = 1;
  repeated ValueTextInfo data = 2;
}

message ValueTextListReq {
  uint64 page = 1;
  uint64 page_size = 2;
  optional int64 created_at = 3;
  optional int64 updated_at = 4;
  optional int64 deleted_at = 5;
  optional uint64 ci_id = 6;
  optional uint64 attr_id = 7;
  optional string value = 8;
}


service Cmdb {

  // ValueText management
  // group: valuetext
  rpc createValueText (ValueTextInfo) returns (BaseIDResp);
  // group: valuetext
  rpc updateValueText (ValueTextInfo) returns (BaseResp);
  // group: valuetext
  rpc getValueTextList (ValueTextListReq) returns (ValueTextListResp);
  // group: valuetext
  rpc getValueTextById (IDReq) returns (ValueTextInfo);
  // group: valuetext
  rpc deleteValueText (IDsReq) returns (BaseResp);


}