syntax = "proto3";

// ValueJSON message

message ValueJSONInfo {
  optional uint64 id = 1;
  optional int64 created_at = 2;
  optional int64 updated_at = 3;
  // 外键，关联cmdb_cis.id
  optional uint64 ci_id = 4;
  // 外键，关联cmdb_attributes.id
  optional uint64 attr_id = 5;
  // 属性值(JSON)
  optional string value = 6;
  // 是否可被覆盖
  optional bool is_cover = 7;
}

message ValueJSONListResp {
  uint64 total = 1;
  repeated ValueJSONInfo data = 2;
}

message ValueJSONListReq {
  uint64 page = 1;
  uint64 page_size = 2;
  optional int64 created_at = 3;
  optional int64 updated_at = 4;
  optional int64 deleted_at = 5;
  optional uint64 ci_id = 6;
  optional uint64 attr_id = 7;
  optional string value = 8;
}


service Cmdb {

  // ValueJSON management
  // group: valuejson
  rpc createValueJSON (ValueJSONInfo) returns (BaseIDResp);
  // group: valuejson
  rpc updateValueJSON (ValueJSONInfo) returns (BaseResp);
  // group: valuejson
  rpc getValueJSONList (ValueJSONListReq) returns (ValueJSONListResp);
  // group: valuejson
  rpc getValueJSONById (IDReq) returns (ValueJSONInfo);
  // group: valuejson
  rpc deleteValueJSON (IDsReq) returns (BaseResp);


}