// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/link234/cmdb-rpc/ent/attribute"
	"gitee.com/link234/cmdb-rpc/ent/choicetext"
	"gitee.com/link234/cmdb-rpc/ent/predicate"
	"gitee.com/link234/cmdb-rpc/ent/schema"
)

// ChoiceTextUpdate is the builder for updating ChoiceText entities.
type ChoiceTextUpdate struct {
	config
	hooks    []Hook
	mutation *ChoiceTextMutation
}

// Where appends a list predicates to the ChoiceTextUpdate builder.
func (ctu *ChoiceTextUpdate) Where(ps ...predicate.ChoiceText) *ChoiceTextUpdate {
	ctu.mutation.Where(ps...)
	return ctu
}

// SetUpdatedAt sets the "updated_at" field.
func (ctu *ChoiceTextUpdate) SetUpdatedAt(t time.Time) *ChoiceTextUpdate {
	ctu.mutation.SetUpdatedAt(t)
	return ctu
}

// SetDeletedAt sets the "deleted_at" field.
func (ctu *ChoiceTextUpdate) SetDeletedAt(t time.Time) *ChoiceTextUpdate {
	ctu.mutation.SetDeletedAt(t)
	return ctu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ctu *ChoiceTextUpdate) SetNillableDeletedAt(t *time.Time) *ChoiceTextUpdate {
	if t != nil {
		ctu.SetDeletedAt(*t)
	}
	return ctu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ctu *ChoiceTextUpdate) ClearDeletedAt() *ChoiceTextUpdate {
	ctu.mutation.ClearDeletedAt()
	return ctu
}

// SetDepartmentID sets the "department_id" field.
func (ctu *ChoiceTextUpdate) SetDepartmentID(u uint64) *ChoiceTextUpdate {
	ctu.mutation.ResetDepartmentID()
	ctu.mutation.SetDepartmentID(u)
	return ctu
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (ctu *ChoiceTextUpdate) SetNillableDepartmentID(u *uint64) *ChoiceTextUpdate {
	if u != nil {
		ctu.SetDepartmentID(*u)
	}
	return ctu
}

// AddDepartmentID adds u to the "department_id" field.
func (ctu *ChoiceTextUpdate) AddDepartmentID(u int64) *ChoiceTextUpdate {
	ctu.mutation.AddDepartmentID(u)
	return ctu
}

// ClearDepartmentID clears the value of the "department_id" field.
func (ctu *ChoiceTextUpdate) ClearDepartmentID() *ChoiceTextUpdate {
	ctu.mutation.ClearDepartmentID()
	return ctu
}

// SetAttrID sets the "attr_id" field.
func (ctu *ChoiceTextUpdate) SetAttrID(u uint64) *ChoiceTextUpdate {
	ctu.mutation.SetAttrID(u)
	return ctu
}

// SetNillableAttrID sets the "attr_id" field if the given value is not nil.
func (ctu *ChoiceTextUpdate) SetNillableAttrID(u *uint64) *ChoiceTextUpdate {
	if u != nil {
		ctu.SetAttrID(*u)
	}
	return ctu
}

// SetValue sets the "value" field.
func (ctu *ChoiceTextUpdate) SetValue(s string) *ChoiceTextUpdate {
	ctu.mutation.SetValue(s)
	return ctu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (ctu *ChoiceTextUpdate) SetNillableValue(s *string) *ChoiceTextUpdate {
	if s != nil {
		ctu.SetValue(*s)
	}
	return ctu
}

// SetOption sets the "option" field.
func (ctu *ChoiceTextUpdate) SetOption(sim schema.ChoiceItemMetaS) *ChoiceTextUpdate {
	ctu.mutation.SetOption(sim)
	return ctu
}

// SetNillableOption sets the "option" field if the given value is not nil.
func (ctu *ChoiceTextUpdate) SetNillableOption(sim *schema.ChoiceItemMetaS) *ChoiceTextUpdate {
	if sim != nil {
		ctu.SetOption(*sim)
	}
	return ctu
}

// ClearOption clears the value of the "option" field.
func (ctu *ChoiceTextUpdate) ClearOption() *ChoiceTextUpdate {
	ctu.mutation.ClearOption()
	return ctu
}

// SetAttributeID sets the "attribute" edge to the Attribute entity by ID.
func (ctu *ChoiceTextUpdate) SetAttributeID(id uint64) *ChoiceTextUpdate {
	ctu.mutation.SetAttributeID(id)
	return ctu
}

// SetAttribute sets the "attribute" edge to the Attribute entity.
func (ctu *ChoiceTextUpdate) SetAttribute(a *Attribute) *ChoiceTextUpdate {
	return ctu.SetAttributeID(a.ID)
}

// Mutation returns the ChoiceTextMutation object of the builder.
func (ctu *ChoiceTextUpdate) Mutation() *ChoiceTextMutation {
	return ctu.mutation
}

// ClearAttribute clears the "attribute" edge to the Attribute entity.
func (ctu *ChoiceTextUpdate) ClearAttribute() *ChoiceTextUpdate {
	ctu.mutation.ClearAttribute()
	return ctu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ctu *ChoiceTextUpdate) Save(ctx context.Context) (int, error) {
	if err := ctu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ctu.sqlSave, ctu.mutation, ctu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctu *ChoiceTextUpdate) SaveX(ctx context.Context) int {
	affected, err := ctu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ctu *ChoiceTextUpdate) Exec(ctx context.Context) error {
	_, err := ctu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctu *ChoiceTextUpdate) ExecX(ctx context.Context) {
	if err := ctu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ctu *ChoiceTextUpdate) defaults() error {
	if _, ok := ctu.mutation.UpdatedAt(); !ok {
		if choicetext.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized choicetext.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := choicetext.UpdateDefaultUpdatedAt()
		ctu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ctu *ChoiceTextUpdate) check() error {
	if ctu.mutation.AttributeCleared() && len(ctu.mutation.AttributeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChoiceText.attribute"`)
	}
	return nil
}

func (ctu *ChoiceTextUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ctu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(choicetext.Table, choicetext.Columns, sqlgraph.NewFieldSpec(choicetext.FieldID, field.TypeUint64))
	if ps := ctu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ctu.mutation.UpdatedAt(); ok {
		_spec.SetField(choicetext.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ctu.mutation.DeletedAt(); ok {
		_spec.SetField(choicetext.FieldDeletedAt, field.TypeTime, value)
	}
	if ctu.mutation.DeletedAtCleared() {
		_spec.ClearField(choicetext.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ctu.mutation.DepartmentID(); ok {
		_spec.SetField(choicetext.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := ctu.mutation.AddedDepartmentID(); ok {
		_spec.AddField(choicetext.FieldDepartmentID, field.TypeUint64, value)
	}
	if ctu.mutation.DepartmentIDCleared() {
		_spec.ClearField(choicetext.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := ctu.mutation.Value(); ok {
		_spec.SetField(choicetext.FieldValue, field.TypeString, value)
	}
	if value, ok := ctu.mutation.Option(); ok {
		_spec.SetField(choicetext.FieldOption, field.TypeJSON, value)
	}
	if ctu.mutation.OptionCleared() {
		_spec.ClearField(choicetext.FieldOption, field.TypeJSON)
	}
	if ctu.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choicetext.AttributeTable,
			Columns: []string{choicetext.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctu.mutation.AttributeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choicetext.AttributeTable,
			Columns: []string{choicetext.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ctu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choicetext.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ctu.mutation.done = true
	return n, nil
}

// ChoiceTextUpdateOne is the builder for updating a single ChoiceText entity.
type ChoiceTextUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChoiceTextMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ctuo *ChoiceTextUpdateOne) SetUpdatedAt(t time.Time) *ChoiceTextUpdateOne {
	ctuo.mutation.SetUpdatedAt(t)
	return ctuo
}

// SetDeletedAt sets the "deleted_at" field.
func (ctuo *ChoiceTextUpdateOne) SetDeletedAt(t time.Time) *ChoiceTextUpdateOne {
	ctuo.mutation.SetDeletedAt(t)
	return ctuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ctuo *ChoiceTextUpdateOne) SetNillableDeletedAt(t *time.Time) *ChoiceTextUpdateOne {
	if t != nil {
		ctuo.SetDeletedAt(*t)
	}
	return ctuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ctuo *ChoiceTextUpdateOne) ClearDeletedAt() *ChoiceTextUpdateOne {
	ctuo.mutation.ClearDeletedAt()
	return ctuo
}

// SetDepartmentID sets the "department_id" field.
func (ctuo *ChoiceTextUpdateOne) SetDepartmentID(u uint64) *ChoiceTextUpdateOne {
	ctuo.mutation.ResetDepartmentID()
	ctuo.mutation.SetDepartmentID(u)
	return ctuo
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (ctuo *ChoiceTextUpdateOne) SetNillableDepartmentID(u *uint64) *ChoiceTextUpdateOne {
	if u != nil {
		ctuo.SetDepartmentID(*u)
	}
	return ctuo
}

// AddDepartmentID adds u to the "department_id" field.
func (ctuo *ChoiceTextUpdateOne) AddDepartmentID(u int64) *ChoiceTextUpdateOne {
	ctuo.mutation.AddDepartmentID(u)
	return ctuo
}

// ClearDepartmentID clears the value of the "department_id" field.
func (ctuo *ChoiceTextUpdateOne) ClearDepartmentID() *ChoiceTextUpdateOne {
	ctuo.mutation.ClearDepartmentID()
	return ctuo
}

// SetAttrID sets the "attr_id" field.
func (ctuo *ChoiceTextUpdateOne) SetAttrID(u uint64) *ChoiceTextUpdateOne {
	ctuo.mutation.SetAttrID(u)
	return ctuo
}

// SetNillableAttrID sets the "attr_id" field if the given value is not nil.
func (ctuo *ChoiceTextUpdateOne) SetNillableAttrID(u *uint64) *ChoiceTextUpdateOne {
	if u != nil {
		ctuo.SetAttrID(*u)
	}
	return ctuo
}

// SetValue sets the "value" field.
func (ctuo *ChoiceTextUpdateOne) SetValue(s string) *ChoiceTextUpdateOne {
	ctuo.mutation.SetValue(s)
	return ctuo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (ctuo *ChoiceTextUpdateOne) SetNillableValue(s *string) *ChoiceTextUpdateOne {
	if s != nil {
		ctuo.SetValue(*s)
	}
	return ctuo
}

// SetOption sets the "option" field.
func (ctuo *ChoiceTextUpdateOne) SetOption(sim schema.ChoiceItemMetaS) *ChoiceTextUpdateOne {
	ctuo.mutation.SetOption(sim)
	return ctuo
}

// SetNillableOption sets the "option" field if the given value is not nil.
func (ctuo *ChoiceTextUpdateOne) SetNillableOption(sim *schema.ChoiceItemMetaS) *ChoiceTextUpdateOne {
	if sim != nil {
		ctuo.SetOption(*sim)
	}
	return ctuo
}

// ClearOption clears the value of the "option" field.
func (ctuo *ChoiceTextUpdateOne) ClearOption() *ChoiceTextUpdateOne {
	ctuo.mutation.ClearOption()
	return ctuo
}

// SetAttributeID sets the "attribute" edge to the Attribute entity by ID.
func (ctuo *ChoiceTextUpdateOne) SetAttributeID(id uint64) *ChoiceTextUpdateOne {
	ctuo.mutation.SetAttributeID(id)
	return ctuo
}

// SetAttribute sets the "attribute" edge to the Attribute entity.
func (ctuo *ChoiceTextUpdateOne) SetAttribute(a *Attribute) *ChoiceTextUpdateOne {
	return ctuo.SetAttributeID(a.ID)
}

// Mutation returns the ChoiceTextMutation object of the builder.
func (ctuo *ChoiceTextUpdateOne) Mutation() *ChoiceTextMutation {
	return ctuo.mutation
}

// ClearAttribute clears the "attribute" edge to the Attribute entity.
func (ctuo *ChoiceTextUpdateOne) ClearAttribute() *ChoiceTextUpdateOne {
	ctuo.mutation.ClearAttribute()
	return ctuo
}

// Where appends a list predicates to the ChoiceTextUpdate builder.
func (ctuo *ChoiceTextUpdateOne) Where(ps ...predicate.ChoiceText) *ChoiceTextUpdateOne {
	ctuo.mutation.Where(ps...)
	return ctuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ctuo *ChoiceTextUpdateOne) Select(field string, fields ...string) *ChoiceTextUpdateOne {
	ctuo.fields = append([]string{field}, fields...)
	return ctuo
}

// Save executes the query and returns the updated ChoiceText entity.
func (ctuo *ChoiceTextUpdateOne) Save(ctx context.Context) (*ChoiceText, error) {
	if err := ctuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ctuo.sqlSave, ctuo.mutation, ctuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctuo *ChoiceTextUpdateOne) SaveX(ctx context.Context) *ChoiceText {
	node, err := ctuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ctuo *ChoiceTextUpdateOne) Exec(ctx context.Context) error {
	_, err := ctuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctuo *ChoiceTextUpdateOne) ExecX(ctx context.Context) {
	if err := ctuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ctuo *ChoiceTextUpdateOne) defaults() error {
	if _, ok := ctuo.mutation.UpdatedAt(); !ok {
		if choicetext.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized choicetext.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := choicetext.UpdateDefaultUpdatedAt()
		ctuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ctuo *ChoiceTextUpdateOne) check() error {
	if ctuo.mutation.AttributeCleared() && len(ctuo.mutation.AttributeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChoiceText.attribute"`)
	}
	return nil
}

func (ctuo *ChoiceTextUpdateOne) sqlSave(ctx context.Context) (_node *ChoiceText, err error) {
	if err := ctuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(choicetext.Table, choicetext.Columns, sqlgraph.NewFieldSpec(choicetext.FieldID, field.TypeUint64))
	id, ok := ctuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChoiceText.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ctuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, choicetext.FieldID)
		for _, f := range fields {
			if !choicetext.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != choicetext.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ctuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ctuo.mutation.UpdatedAt(); ok {
		_spec.SetField(choicetext.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ctuo.mutation.DeletedAt(); ok {
		_spec.SetField(choicetext.FieldDeletedAt, field.TypeTime, value)
	}
	if ctuo.mutation.DeletedAtCleared() {
		_spec.ClearField(choicetext.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ctuo.mutation.DepartmentID(); ok {
		_spec.SetField(choicetext.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := ctuo.mutation.AddedDepartmentID(); ok {
		_spec.AddField(choicetext.FieldDepartmentID, field.TypeUint64, value)
	}
	if ctuo.mutation.DepartmentIDCleared() {
		_spec.ClearField(choicetext.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := ctuo.mutation.Value(); ok {
		_spec.SetField(choicetext.FieldValue, field.TypeString, value)
	}
	if value, ok := ctuo.mutation.Option(); ok {
		_spec.SetField(choicetext.FieldOption, field.TypeJSON, value)
	}
	if ctuo.mutation.OptionCleared() {
		_spec.ClearField(choicetext.FieldOption, field.TypeJSON)
	}
	if ctuo.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choicetext.AttributeTable,
			Columns: []string{choicetext.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctuo.mutation.AttributeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choicetext.AttributeTable,
			Columns: []string{choicetext.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChoiceText{config: ctuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ctuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choicetext.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ctuo.mutation.done = true
	return _node, nil
}
