// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/cidimension"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
)

// CiDimensionUpdate is the builder for updating CiDimension entities.
type CiDimensionUpdate struct {
	config
	hooks    []Hook
	mutation *CiDimensionMutation
}

// Where appends a list predicates to the CiDimensionUpdate builder.
func (_u *CiDimensionUpdate) Where(ps ...predicate.CiDimension) *CiDimensionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CiDimensionUpdate) SetUpdatedAt(v time.Time) *CiDimensionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *CiDimensionUpdate) SetDepartmentID(v uint64) *CiDimensionUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableDepartmentID(v *uint64) *CiDimensionUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *CiDimensionUpdate) AddDepartmentID(v int64) *CiDimensionUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *CiDimensionUpdate) ClearDepartmentID() *CiDimensionUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCiTypeID sets the "ci_type_id" field.
func (_u *CiDimensionUpdate) SetCiTypeID(v uint64) *CiDimensionUpdate {
	_u.mutation.ResetCiTypeID()
	_u.mutation.SetCiTypeID(v)
	return _u
}

// SetNillableCiTypeID sets the "ci_type_id" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableCiTypeID(v *uint64) *CiDimensionUpdate {
	if v != nil {
		_u.SetCiTypeID(*v)
	}
	return _u
}

// AddCiTypeID adds value to the "ci_type_id" field.
func (_u *CiDimensionUpdate) AddCiTypeID(v int64) *CiDimensionUpdate {
	_u.mutation.AddCiTypeID(v)
	return _u
}

// SetCiTypeName sets the "ci_type_name" field.
func (_u *CiDimensionUpdate) SetCiTypeName(v string) *CiDimensionUpdate {
	_u.mutation.SetCiTypeName(v)
	return _u
}

// SetNillableCiTypeName sets the "ci_type_name" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableCiTypeName(v *string) *CiDimensionUpdate {
	if v != nil {
		_u.SetCiTypeName(*v)
	}
	return _u
}

// SetCiTypeAlias sets the "ci_type_alias" field.
func (_u *CiDimensionUpdate) SetCiTypeAlias(v string) *CiDimensionUpdate {
	_u.mutation.SetCiTypeAlias(v)
	return _u
}

// SetNillableCiTypeAlias sets the "ci_type_alias" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableCiTypeAlias(v *string) *CiDimensionUpdate {
	if v != nil {
		_u.SetCiTypeAlias(*v)
	}
	return _u
}

// ClearCiTypeAlias clears the value of the "ci_type_alias" field.
func (_u *CiDimensionUpdate) ClearCiTypeAlias() *CiDimensionUpdate {
	_u.mutation.ClearCiTypeAlias()
	return _u
}

// SetCiCategory sets the "ci_category" field.
func (_u *CiDimensionUpdate) SetCiCategory(v string) *CiDimensionUpdate {
	_u.mutation.SetCiCategory(v)
	return _u
}

// SetNillableCiCategory sets the "ci_category" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableCiCategory(v *string) *CiDimensionUpdate {
	if v != nil {
		_u.SetCiCategory(*v)
	}
	return _u
}

// ClearCiCategory clears the value of the "ci_category" field.
func (_u *CiDimensionUpdate) ClearCiCategory() *CiDimensionUpdate {
	_u.mutation.ClearCiCategory()
	return _u
}

// SetLifecycleStage sets the "lifecycle_stage" field.
func (_u *CiDimensionUpdate) SetLifecycleStage(v cidimension.LifecycleStage) *CiDimensionUpdate {
	_u.mutation.SetLifecycleStage(v)
	return _u
}

// SetNillableLifecycleStage sets the "lifecycle_stage" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableLifecycleStage(v *cidimension.LifecycleStage) *CiDimensionUpdate {
	if v != nil {
		_u.SetLifecycleStage(*v)
	}
	return _u
}

// SetBusinessCriticality sets the "business_criticality" field.
func (_u *CiDimensionUpdate) SetBusinessCriticality(v cidimension.BusinessCriticality) *CiDimensionUpdate {
	_u.mutation.SetBusinessCriticality(v)
	return _u
}

// SetNillableBusinessCriticality sets the "business_criticality" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableBusinessCriticality(v *cidimension.BusinessCriticality) *CiDimensionUpdate {
	if v != nil {
		_u.SetBusinessCriticality(*v)
	}
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *CiDimensionUpdate) SetEnvironment(v string) *CiDimensionUpdate {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableEnvironment(v *string) *CiDimensionUpdate {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// ClearEnvironment clears the value of the "environment" field.
func (_u *CiDimensionUpdate) ClearEnvironment() *CiDimensionUpdate {
	_u.mutation.ClearEnvironment()
	return _u
}

// SetLocation sets the "location" field.
func (_u *CiDimensionUpdate) SetLocation(v string) *CiDimensionUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableLocation(v *string) *CiDimensionUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *CiDimensionUpdate) ClearLocation() *CiDimensionUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetOrganizationHierarchy sets the "organization_hierarchy" field.
func (_u *CiDimensionUpdate) SetOrganizationHierarchy(v map[string]interface{}) *CiDimensionUpdate {
	_u.mutation.SetOrganizationHierarchy(v)
	return _u
}

// ClearOrganizationHierarchy clears the value of the "organization_hierarchy" field.
func (_u *CiDimensionUpdate) ClearOrganizationHierarchy() *CiDimensionUpdate {
	_u.mutation.ClearOrganizationHierarchy()
	return _u
}

// SetTagDimensions sets the "tag_dimensions" field.
func (_u *CiDimensionUpdate) SetTagDimensions(v []string) *CiDimensionUpdate {
	_u.mutation.SetTagDimensions(v)
	return _u
}

// AppendTagDimensions appends value to the "tag_dimensions" field.
func (_u *CiDimensionUpdate) AppendTagDimensions(v []string) *CiDimensionUpdate {
	_u.mutation.AppendTagDimensions(v)
	return _u
}

// ClearTagDimensions clears the value of the "tag_dimensions" field.
func (_u *CiDimensionUpdate) ClearTagDimensions() *CiDimensionUpdate {
	_u.mutation.ClearTagDimensions()
	return _u
}

// SetCostCenter sets the "cost_center" field.
func (_u *CiDimensionUpdate) SetCostCenter(v string) *CiDimensionUpdate {
	_u.mutation.SetCostCenter(v)
	return _u
}

// SetNillableCostCenter sets the "cost_center" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableCostCenter(v *string) *CiDimensionUpdate {
	if v != nil {
		_u.SetCostCenter(*v)
	}
	return _u
}

// ClearCostCenter clears the value of the "cost_center" field.
func (_u *CiDimensionUpdate) ClearCostCenter() *CiDimensionUpdate {
	_u.mutation.ClearCostCenter()
	return _u
}

// SetOwnerInfo sets the "owner_info" field.
func (_u *CiDimensionUpdate) SetOwnerInfo(v map[string]interface{}) *CiDimensionUpdate {
	_u.mutation.SetOwnerInfo(v)
	return _u
}

// ClearOwnerInfo clears the value of the "owner_info" field.
func (_u *CiDimensionUpdate) ClearOwnerInfo() *CiDimensionUpdate {
	_u.mutation.ClearOwnerInfo()
	return _u
}

// SetCustomDimensions sets the "custom_dimensions" field.
func (_u *CiDimensionUpdate) SetCustomDimensions(v map[string]interface{}) *CiDimensionUpdate {
	_u.mutation.SetCustomDimensions(v)
	return _u
}

// ClearCustomDimensions clears the value of the "custom_dimensions" field.
func (_u *CiDimensionUpdate) ClearCustomDimensions() *CiDimensionUpdate {
	_u.mutation.ClearCustomDimensions()
	return _u
}

// SetSLALevel sets the "sla_level" field.
func (_u *CiDimensionUpdate) SetSLALevel(v cidimension.SLALevel) *CiDimensionUpdate {
	_u.mutation.SetSLALevel(v)
	return _u
}

// SetNillableSLALevel sets the "sla_level" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableSLALevel(v *cidimension.SLALevel) *CiDimensionUpdate {
	if v != nil {
		_u.SetSLALevel(*v)
	}
	return _u
}

// ClearSLALevel clears the value of the "sla_level" field.
func (_u *CiDimensionUpdate) ClearSLALevel() *CiDimensionUpdate {
	_u.mutation.ClearSLALevel()
	return _u
}

// SetComplianceTags sets the "compliance_tags" field.
func (_u *CiDimensionUpdate) SetComplianceTags(v []string) *CiDimensionUpdate {
	_u.mutation.SetComplianceTags(v)
	return _u
}

// AppendComplianceTags appends value to the "compliance_tags" field.
func (_u *CiDimensionUpdate) AppendComplianceTags(v []string) *CiDimensionUpdate {
	_u.mutation.AppendComplianceTags(v)
	return _u
}

// ClearComplianceTags clears the value of the "compliance_tags" field.
func (_u *CiDimensionUpdate) ClearComplianceTags() *CiDimensionUpdate {
	_u.mutation.ClearComplianceTags()
	return _u
}

// SetRiskLevel sets the "risk_level" field.
func (_u *CiDimensionUpdate) SetRiskLevel(v cidimension.RiskLevel) *CiDimensionUpdate {
	_u.mutation.SetRiskLevel(v)
	return _u
}

// SetNillableRiskLevel sets the "risk_level" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableRiskLevel(v *cidimension.RiskLevel) *CiDimensionUpdate {
	if v != nil {
		_u.SetRiskLevel(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CiDimensionUpdate) SetIsActive(v bool) *CiDimensionUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableIsActive(v *bool) *CiDimensionUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDimensionVersion sets the "dimension_version" field.
func (_u *CiDimensionUpdate) SetDimensionVersion(v uint64) *CiDimensionUpdate {
	_u.mutation.ResetDimensionVersion()
	_u.mutation.SetDimensionVersion(v)
	return _u
}

// SetNillableDimensionVersion sets the "dimension_version" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableDimensionVersion(v *uint64) *CiDimensionUpdate {
	if v != nil {
		_u.SetDimensionVersion(*v)
	}
	return _u
}

// AddDimensionVersion adds value to the "dimension_version" field.
func (_u *CiDimensionUpdate) AddDimensionVersion(v int64) *CiDimensionUpdate {
	_u.mutation.AddDimensionVersion(v)
	return _u
}

// SetDimensionUpdatedAt sets the "dimension_updated_at" field.
func (_u *CiDimensionUpdate) SetDimensionUpdatedAt(v time.Time) *CiDimensionUpdate {
	_u.mutation.SetDimensionUpdatedAt(v)
	return _u
}

// SetNillableDimensionUpdatedAt sets the "dimension_updated_at" field if the given value is not nil.
func (_u *CiDimensionUpdate) SetNillableDimensionUpdatedAt(v *time.Time) *CiDimensionUpdate {
	if v != nil {
		_u.SetDimensionUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the CiDimensionMutation object of the builder.
func (_u *CiDimensionUpdate) Mutation() *CiDimensionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CiDimensionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CiDimensionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CiDimensionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CiDimensionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CiDimensionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cidimension.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CiDimensionUpdate) check() error {
	if v, ok := _u.mutation.CiTypeName(); ok {
		if err := cidimension.CiTypeNameValidator(v); err != nil {
			return &ValidationError{Name: "ci_type_name", err: fmt.Errorf(`ent: validator failed for field "CiDimension.ci_type_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiTypeAlias(); ok {
		if err := cidimension.CiTypeAliasValidator(v); err != nil {
			return &ValidationError{Name: "ci_type_alias", err: fmt.Errorf(`ent: validator failed for field "CiDimension.ci_type_alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiCategory(); ok {
		if err := cidimension.CiCategoryValidator(v); err != nil {
			return &ValidationError{Name: "ci_category", err: fmt.Errorf(`ent: validator failed for field "CiDimension.ci_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifecycleStage(); ok {
		if err := cidimension.LifecycleStageValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle_stage", err: fmt.Errorf(`ent: validator failed for field "CiDimension.lifecycle_stage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BusinessCriticality(); ok {
		if err := cidimension.BusinessCriticalityValidator(v); err != nil {
			return &ValidationError{Name: "business_criticality", err: fmt.Errorf(`ent: validator failed for field "CiDimension.business_criticality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Environment(); ok {
		if err := cidimension.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "CiDimension.environment": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := cidimension.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "CiDimension.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostCenter(); ok {
		if err := cidimension.CostCenterValidator(v); err != nil {
			return &ValidationError{Name: "cost_center", err: fmt.Errorf(`ent: validator failed for field "CiDimension.cost_center": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SLALevel(); ok {
		if err := cidimension.SLALevelValidator(v); err != nil {
			return &ValidationError{Name: "sla_level", err: fmt.Errorf(`ent: validator failed for field "CiDimension.sla_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskLevel(); ok {
		if err := cidimension.RiskLevelValidator(v); err != nil {
			return &ValidationError{Name: "risk_level", err: fmt.Errorf(`ent: validator failed for field "CiDimension.risk_level": %w`, err)}
		}
	}
	return nil
}

func (_u *CiDimensionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cidimension.Table, cidimension.Columns, sqlgraph.NewFieldSpec(cidimension.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cidimension.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(cidimension.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(cidimension.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(cidimension.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CiTypeID(); ok {
		_spec.SetField(cidimension.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiTypeID(); ok {
		_spec.AddField(cidimension.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CiTypeName(); ok {
		_spec.SetField(cidimension.FieldCiTypeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CiTypeAlias(); ok {
		_spec.SetField(cidimension.FieldCiTypeAlias, field.TypeString, value)
	}
	if _u.mutation.CiTypeAliasCleared() {
		_spec.ClearField(cidimension.FieldCiTypeAlias, field.TypeString)
	}
	if value, ok := _u.mutation.CiCategory(); ok {
		_spec.SetField(cidimension.FieldCiCategory, field.TypeString, value)
	}
	if _u.mutation.CiCategoryCleared() {
		_spec.ClearField(cidimension.FieldCiCategory, field.TypeString)
	}
	if value, ok := _u.mutation.LifecycleStage(); ok {
		_spec.SetField(cidimension.FieldLifecycleStage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BusinessCriticality(); ok {
		_spec.SetField(cidimension.FieldBusinessCriticality, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(cidimension.FieldEnvironment, field.TypeString, value)
	}
	if _u.mutation.EnvironmentCleared() {
		_spec.ClearField(cidimension.FieldEnvironment, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(cidimension.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(cidimension.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.OrganizationHierarchy(); ok {
		_spec.SetField(cidimension.FieldOrganizationHierarchy, field.TypeJSON, value)
	}
	if _u.mutation.OrganizationHierarchyCleared() {
		_spec.ClearField(cidimension.FieldOrganizationHierarchy, field.TypeJSON)
	}
	if value, ok := _u.mutation.TagDimensions(); ok {
		_spec.SetField(cidimension.FieldTagDimensions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTagDimensions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, cidimension.FieldTagDimensions, value)
		})
	}
	if _u.mutation.TagDimensionsCleared() {
		_spec.ClearField(cidimension.FieldTagDimensions, field.TypeJSON)
	}
	if value, ok := _u.mutation.CostCenter(); ok {
		_spec.SetField(cidimension.FieldCostCenter, field.TypeString, value)
	}
	if _u.mutation.CostCenterCleared() {
		_spec.ClearField(cidimension.FieldCostCenter, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerInfo(); ok {
		_spec.SetField(cidimension.FieldOwnerInfo, field.TypeJSON, value)
	}
	if _u.mutation.OwnerInfoCleared() {
		_spec.ClearField(cidimension.FieldOwnerInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.CustomDimensions(); ok {
		_spec.SetField(cidimension.FieldCustomDimensions, field.TypeJSON, value)
	}
	if _u.mutation.CustomDimensionsCleared() {
		_spec.ClearField(cidimension.FieldCustomDimensions, field.TypeJSON)
	}
	if value, ok := _u.mutation.SLALevel(); ok {
		_spec.SetField(cidimension.FieldSLALevel, field.TypeEnum, value)
	}
	if _u.mutation.SLALevelCleared() {
		_spec.ClearField(cidimension.FieldSLALevel, field.TypeEnum)
	}
	if value, ok := _u.mutation.ComplianceTags(); ok {
		_spec.SetField(cidimension.FieldComplianceTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedComplianceTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, cidimension.FieldComplianceTags, value)
		})
	}
	if _u.mutation.ComplianceTagsCleared() {
		_spec.ClearField(cidimension.FieldComplianceTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.RiskLevel(); ok {
		_spec.SetField(cidimension.FieldRiskLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(cidimension.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DimensionVersion(); ok {
		_spec.SetField(cidimension.FieldDimensionVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDimensionVersion(); ok {
		_spec.AddField(cidimension.FieldDimensionVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DimensionUpdatedAt(); ok {
		_spec.SetField(cidimension.FieldDimensionUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cidimension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CiDimensionUpdateOne is the builder for updating a single CiDimension entity.
type CiDimensionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CiDimensionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CiDimensionUpdateOne) SetUpdatedAt(v time.Time) *CiDimensionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *CiDimensionUpdateOne) SetDepartmentID(v uint64) *CiDimensionUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableDepartmentID(v *uint64) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *CiDimensionUpdateOne) AddDepartmentID(v int64) *CiDimensionUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *CiDimensionUpdateOne) ClearDepartmentID() *CiDimensionUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCiTypeID sets the "ci_type_id" field.
func (_u *CiDimensionUpdateOne) SetCiTypeID(v uint64) *CiDimensionUpdateOne {
	_u.mutation.ResetCiTypeID()
	_u.mutation.SetCiTypeID(v)
	return _u
}

// SetNillableCiTypeID sets the "ci_type_id" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableCiTypeID(v *uint64) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetCiTypeID(*v)
	}
	return _u
}

// AddCiTypeID adds value to the "ci_type_id" field.
func (_u *CiDimensionUpdateOne) AddCiTypeID(v int64) *CiDimensionUpdateOne {
	_u.mutation.AddCiTypeID(v)
	return _u
}

// SetCiTypeName sets the "ci_type_name" field.
func (_u *CiDimensionUpdateOne) SetCiTypeName(v string) *CiDimensionUpdateOne {
	_u.mutation.SetCiTypeName(v)
	return _u
}

// SetNillableCiTypeName sets the "ci_type_name" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableCiTypeName(v *string) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetCiTypeName(*v)
	}
	return _u
}

// SetCiTypeAlias sets the "ci_type_alias" field.
func (_u *CiDimensionUpdateOne) SetCiTypeAlias(v string) *CiDimensionUpdateOne {
	_u.mutation.SetCiTypeAlias(v)
	return _u
}

// SetNillableCiTypeAlias sets the "ci_type_alias" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableCiTypeAlias(v *string) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetCiTypeAlias(*v)
	}
	return _u
}

// ClearCiTypeAlias clears the value of the "ci_type_alias" field.
func (_u *CiDimensionUpdateOne) ClearCiTypeAlias() *CiDimensionUpdateOne {
	_u.mutation.ClearCiTypeAlias()
	return _u
}

// SetCiCategory sets the "ci_category" field.
func (_u *CiDimensionUpdateOne) SetCiCategory(v string) *CiDimensionUpdateOne {
	_u.mutation.SetCiCategory(v)
	return _u
}

// SetNillableCiCategory sets the "ci_category" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableCiCategory(v *string) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetCiCategory(*v)
	}
	return _u
}

// ClearCiCategory clears the value of the "ci_category" field.
func (_u *CiDimensionUpdateOne) ClearCiCategory() *CiDimensionUpdateOne {
	_u.mutation.ClearCiCategory()
	return _u
}

// SetLifecycleStage sets the "lifecycle_stage" field.
func (_u *CiDimensionUpdateOne) SetLifecycleStage(v cidimension.LifecycleStage) *CiDimensionUpdateOne {
	_u.mutation.SetLifecycleStage(v)
	return _u
}

// SetNillableLifecycleStage sets the "lifecycle_stage" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableLifecycleStage(v *cidimension.LifecycleStage) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetLifecycleStage(*v)
	}
	return _u
}

// SetBusinessCriticality sets the "business_criticality" field.
func (_u *CiDimensionUpdateOne) SetBusinessCriticality(v cidimension.BusinessCriticality) *CiDimensionUpdateOne {
	_u.mutation.SetBusinessCriticality(v)
	return _u
}

// SetNillableBusinessCriticality sets the "business_criticality" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableBusinessCriticality(v *cidimension.BusinessCriticality) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetBusinessCriticality(*v)
	}
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *CiDimensionUpdateOne) SetEnvironment(v string) *CiDimensionUpdateOne {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableEnvironment(v *string) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// ClearEnvironment clears the value of the "environment" field.
func (_u *CiDimensionUpdateOne) ClearEnvironment() *CiDimensionUpdateOne {
	_u.mutation.ClearEnvironment()
	return _u
}

// SetLocation sets the "location" field.
func (_u *CiDimensionUpdateOne) SetLocation(v string) *CiDimensionUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableLocation(v *string) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *CiDimensionUpdateOne) ClearLocation() *CiDimensionUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetOrganizationHierarchy sets the "organization_hierarchy" field.
func (_u *CiDimensionUpdateOne) SetOrganizationHierarchy(v map[string]interface{}) *CiDimensionUpdateOne {
	_u.mutation.SetOrganizationHierarchy(v)
	return _u
}

// ClearOrganizationHierarchy clears the value of the "organization_hierarchy" field.
func (_u *CiDimensionUpdateOne) ClearOrganizationHierarchy() *CiDimensionUpdateOne {
	_u.mutation.ClearOrganizationHierarchy()
	return _u
}

// SetTagDimensions sets the "tag_dimensions" field.
func (_u *CiDimensionUpdateOne) SetTagDimensions(v []string) *CiDimensionUpdateOne {
	_u.mutation.SetTagDimensions(v)
	return _u
}

// AppendTagDimensions appends value to the "tag_dimensions" field.
func (_u *CiDimensionUpdateOne) AppendTagDimensions(v []string) *CiDimensionUpdateOne {
	_u.mutation.AppendTagDimensions(v)
	return _u
}

// ClearTagDimensions clears the value of the "tag_dimensions" field.
func (_u *CiDimensionUpdateOne) ClearTagDimensions() *CiDimensionUpdateOne {
	_u.mutation.ClearTagDimensions()
	return _u
}

// SetCostCenter sets the "cost_center" field.
func (_u *CiDimensionUpdateOne) SetCostCenter(v string) *CiDimensionUpdateOne {
	_u.mutation.SetCostCenter(v)
	return _u
}

// SetNillableCostCenter sets the "cost_center" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableCostCenter(v *string) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetCostCenter(*v)
	}
	return _u
}

// ClearCostCenter clears the value of the "cost_center" field.
func (_u *CiDimensionUpdateOne) ClearCostCenter() *CiDimensionUpdateOne {
	_u.mutation.ClearCostCenter()
	return _u
}

// SetOwnerInfo sets the "owner_info" field.
func (_u *CiDimensionUpdateOne) SetOwnerInfo(v map[string]interface{}) *CiDimensionUpdateOne {
	_u.mutation.SetOwnerInfo(v)
	return _u
}

// ClearOwnerInfo clears the value of the "owner_info" field.
func (_u *CiDimensionUpdateOne) ClearOwnerInfo() *CiDimensionUpdateOne {
	_u.mutation.ClearOwnerInfo()
	return _u
}

// SetCustomDimensions sets the "custom_dimensions" field.
func (_u *CiDimensionUpdateOne) SetCustomDimensions(v map[string]interface{}) *CiDimensionUpdateOne {
	_u.mutation.SetCustomDimensions(v)
	return _u
}

// ClearCustomDimensions clears the value of the "custom_dimensions" field.
func (_u *CiDimensionUpdateOne) ClearCustomDimensions() *CiDimensionUpdateOne {
	_u.mutation.ClearCustomDimensions()
	return _u
}

// SetSLALevel sets the "sla_level" field.
func (_u *CiDimensionUpdateOne) SetSLALevel(v cidimension.SLALevel) *CiDimensionUpdateOne {
	_u.mutation.SetSLALevel(v)
	return _u
}

// SetNillableSLALevel sets the "sla_level" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableSLALevel(v *cidimension.SLALevel) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetSLALevel(*v)
	}
	return _u
}

// ClearSLALevel clears the value of the "sla_level" field.
func (_u *CiDimensionUpdateOne) ClearSLALevel() *CiDimensionUpdateOne {
	_u.mutation.ClearSLALevel()
	return _u
}

// SetComplianceTags sets the "compliance_tags" field.
func (_u *CiDimensionUpdateOne) SetComplianceTags(v []string) *CiDimensionUpdateOne {
	_u.mutation.SetComplianceTags(v)
	return _u
}

// AppendComplianceTags appends value to the "compliance_tags" field.
func (_u *CiDimensionUpdateOne) AppendComplianceTags(v []string) *CiDimensionUpdateOne {
	_u.mutation.AppendComplianceTags(v)
	return _u
}

// ClearComplianceTags clears the value of the "compliance_tags" field.
func (_u *CiDimensionUpdateOne) ClearComplianceTags() *CiDimensionUpdateOne {
	_u.mutation.ClearComplianceTags()
	return _u
}

// SetRiskLevel sets the "risk_level" field.
func (_u *CiDimensionUpdateOne) SetRiskLevel(v cidimension.RiskLevel) *CiDimensionUpdateOne {
	_u.mutation.SetRiskLevel(v)
	return _u
}

// SetNillableRiskLevel sets the "risk_level" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableRiskLevel(v *cidimension.RiskLevel) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetRiskLevel(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CiDimensionUpdateOne) SetIsActive(v bool) *CiDimensionUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableIsActive(v *bool) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDimensionVersion sets the "dimension_version" field.
func (_u *CiDimensionUpdateOne) SetDimensionVersion(v uint64) *CiDimensionUpdateOne {
	_u.mutation.ResetDimensionVersion()
	_u.mutation.SetDimensionVersion(v)
	return _u
}

// SetNillableDimensionVersion sets the "dimension_version" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableDimensionVersion(v *uint64) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetDimensionVersion(*v)
	}
	return _u
}

// AddDimensionVersion adds value to the "dimension_version" field.
func (_u *CiDimensionUpdateOne) AddDimensionVersion(v int64) *CiDimensionUpdateOne {
	_u.mutation.AddDimensionVersion(v)
	return _u
}

// SetDimensionUpdatedAt sets the "dimension_updated_at" field.
func (_u *CiDimensionUpdateOne) SetDimensionUpdatedAt(v time.Time) *CiDimensionUpdateOne {
	_u.mutation.SetDimensionUpdatedAt(v)
	return _u
}

// SetNillableDimensionUpdatedAt sets the "dimension_updated_at" field if the given value is not nil.
func (_u *CiDimensionUpdateOne) SetNillableDimensionUpdatedAt(v *time.Time) *CiDimensionUpdateOne {
	if v != nil {
		_u.SetDimensionUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the CiDimensionMutation object of the builder.
func (_u *CiDimensionUpdateOne) Mutation() *CiDimensionMutation {
	return _u.mutation
}

// Where appends a list predicates to the CiDimensionUpdate builder.
func (_u *CiDimensionUpdateOne) Where(ps ...predicate.CiDimension) *CiDimensionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CiDimensionUpdateOne) Select(field string, fields ...string) *CiDimensionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CiDimension entity.
func (_u *CiDimensionUpdateOne) Save(ctx context.Context) (*CiDimension, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CiDimensionUpdateOne) SaveX(ctx context.Context) *CiDimension {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CiDimensionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CiDimensionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CiDimensionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cidimension.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CiDimensionUpdateOne) check() error {
	if v, ok := _u.mutation.CiTypeName(); ok {
		if err := cidimension.CiTypeNameValidator(v); err != nil {
			return &ValidationError{Name: "ci_type_name", err: fmt.Errorf(`ent: validator failed for field "CiDimension.ci_type_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiTypeAlias(); ok {
		if err := cidimension.CiTypeAliasValidator(v); err != nil {
			return &ValidationError{Name: "ci_type_alias", err: fmt.Errorf(`ent: validator failed for field "CiDimension.ci_type_alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiCategory(); ok {
		if err := cidimension.CiCategoryValidator(v); err != nil {
			return &ValidationError{Name: "ci_category", err: fmt.Errorf(`ent: validator failed for field "CiDimension.ci_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifecycleStage(); ok {
		if err := cidimension.LifecycleStageValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle_stage", err: fmt.Errorf(`ent: validator failed for field "CiDimension.lifecycle_stage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BusinessCriticality(); ok {
		if err := cidimension.BusinessCriticalityValidator(v); err != nil {
			return &ValidationError{Name: "business_criticality", err: fmt.Errorf(`ent: validator failed for field "CiDimension.business_criticality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Environment(); ok {
		if err := cidimension.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "CiDimension.environment": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := cidimension.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "CiDimension.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostCenter(); ok {
		if err := cidimension.CostCenterValidator(v); err != nil {
			return &ValidationError{Name: "cost_center", err: fmt.Errorf(`ent: validator failed for field "CiDimension.cost_center": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SLALevel(); ok {
		if err := cidimension.SLALevelValidator(v); err != nil {
			return &ValidationError{Name: "sla_level", err: fmt.Errorf(`ent: validator failed for field "CiDimension.sla_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskLevel(); ok {
		if err := cidimension.RiskLevelValidator(v); err != nil {
			return &ValidationError{Name: "risk_level", err: fmt.Errorf(`ent: validator failed for field "CiDimension.risk_level": %w`, err)}
		}
	}
	return nil
}

func (_u *CiDimensionUpdateOne) sqlSave(ctx context.Context) (_node *CiDimension, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cidimension.Table, cidimension.Columns, sqlgraph.NewFieldSpec(cidimension.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CiDimension.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cidimension.FieldID)
		for _, f := range fields {
			if !cidimension.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cidimension.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cidimension.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(cidimension.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(cidimension.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(cidimension.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CiTypeID(); ok {
		_spec.SetField(cidimension.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiTypeID(); ok {
		_spec.AddField(cidimension.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CiTypeName(); ok {
		_spec.SetField(cidimension.FieldCiTypeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CiTypeAlias(); ok {
		_spec.SetField(cidimension.FieldCiTypeAlias, field.TypeString, value)
	}
	if _u.mutation.CiTypeAliasCleared() {
		_spec.ClearField(cidimension.FieldCiTypeAlias, field.TypeString)
	}
	if value, ok := _u.mutation.CiCategory(); ok {
		_spec.SetField(cidimension.FieldCiCategory, field.TypeString, value)
	}
	if _u.mutation.CiCategoryCleared() {
		_spec.ClearField(cidimension.FieldCiCategory, field.TypeString)
	}
	if value, ok := _u.mutation.LifecycleStage(); ok {
		_spec.SetField(cidimension.FieldLifecycleStage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BusinessCriticality(); ok {
		_spec.SetField(cidimension.FieldBusinessCriticality, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(cidimension.FieldEnvironment, field.TypeString, value)
	}
	if _u.mutation.EnvironmentCleared() {
		_spec.ClearField(cidimension.FieldEnvironment, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(cidimension.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(cidimension.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.OrganizationHierarchy(); ok {
		_spec.SetField(cidimension.FieldOrganizationHierarchy, field.TypeJSON, value)
	}
	if _u.mutation.OrganizationHierarchyCleared() {
		_spec.ClearField(cidimension.FieldOrganizationHierarchy, field.TypeJSON)
	}
	if value, ok := _u.mutation.TagDimensions(); ok {
		_spec.SetField(cidimension.FieldTagDimensions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTagDimensions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, cidimension.FieldTagDimensions, value)
		})
	}
	if _u.mutation.TagDimensionsCleared() {
		_spec.ClearField(cidimension.FieldTagDimensions, field.TypeJSON)
	}
	if value, ok := _u.mutation.CostCenter(); ok {
		_spec.SetField(cidimension.FieldCostCenter, field.TypeString, value)
	}
	if _u.mutation.CostCenterCleared() {
		_spec.ClearField(cidimension.FieldCostCenter, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerInfo(); ok {
		_spec.SetField(cidimension.FieldOwnerInfo, field.TypeJSON, value)
	}
	if _u.mutation.OwnerInfoCleared() {
		_spec.ClearField(cidimension.FieldOwnerInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.CustomDimensions(); ok {
		_spec.SetField(cidimension.FieldCustomDimensions, field.TypeJSON, value)
	}
	if _u.mutation.CustomDimensionsCleared() {
		_spec.ClearField(cidimension.FieldCustomDimensions, field.TypeJSON)
	}
	if value, ok := _u.mutation.SLALevel(); ok {
		_spec.SetField(cidimension.FieldSLALevel, field.TypeEnum, value)
	}
	if _u.mutation.SLALevelCleared() {
		_spec.ClearField(cidimension.FieldSLALevel, field.TypeEnum)
	}
	if value, ok := _u.mutation.ComplianceTags(); ok {
		_spec.SetField(cidimension.FieldComplianceTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedComplianceTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, cidimension.FieldComplianceTags, value)
		})
	}
	if _u.mutation.ComplianceTagsCleared() {
		_spec.ClearField(cidimension.FieldComplianceTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.RiskLevel(); ok {
		_spec.SetField(cidimension.FieldRiskLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(cidimension.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DimensionVersion(); ok {
		_spec.SetField(cidimension.FieldDimensionVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDimensionVersion(); ok {
		_spec.AddField(cidimension.FieldDimensionVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DimensionUpdatedAt(); ok {
		_spec.SetField(cidimension.FieldDimensionUpdatedAt, field.TypeTime, value)
	}
	_node = &CiDimension{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cidimension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
