// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/link234/cmdb-rpc/ent/cirelation"
	"gitee.com/link234/cmdb-rpc/ent/cis"
	"gitee.com/link234/cmdb-rpc/ent/relationtype"
)

// CiRelationCreate is the builder for creating a CiRelation entity.
type CiRelationCreate struct {
	config
	mutation *CiRelationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (crc *CiRelationCreate) SetCreatedAt(t time.Time) *CiRelationCreate {
	crc.mutation.SetCreatedAt(t)
	return crc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableCreatedAt(t *time.Time) *CiRelationCreate {
	if t != nil {
		crc.SetCreatedAt(*t)
	}
	return crc
}

// SetUpdatedAt sets the "updated_at" field.
func (crc *CiRelationCreate) SetUpdatedAt(t time.Time) *CiRelationCreate {
	crc.mutation.SetUpdatedAt(t)
	return crc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableUpdatedAt(t *time.Time) *CiRelationCreate {
	if t != nil {
		crc.SetUpdatedAt(*t)
	}
	return crc
}

// SetDeletedAt sets the "deleted_at" field.
func (crc *CiRelationCreate) SetDeletedAt(t time.Time) *CiRelationCreate {
	crc.mutation.SetDeletedAt(t)
	return crc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableDeletedAt(t *time.Time) *CiRelationCreate {
	if t != nil {
		crc.SetDeletedAt(*t)
	}
	return crc
}

// SetTenantID sets the "tenant_id" field.
func (crc *CiRelationCreate) SetTenantID(u uint64) *CiRelationCreate {
	crc.mutation.SetTenantID(u)
	return crc
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableTenantID(u *uint64) *CiRelationCreate {
	if u != nil {
		crc.SetTenantID(*u)
	}
	return crc
}

// SetDepartmentID sets the "department_id" field.
func (crc *CiRelationCreate) SetDepartmentID(u uint64) *CiRelationCreate {
	crc.mutation.SetDepartmentID(u)
	return crc
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableDepartmentID(u *uint64) *CiRelationCreate {
	if u != nil {
		crc.SetDepartmentID(*u)
	}
	return crc
}

// SetFirstCiID sets the "first_ci_id" field.
func (crc *CiRelationCreate) SetFirstCiID(u uint64) *CiRelationCreate {
	crc.mutation.SetFirstCiID(u)
	return crc
}

// SetSecondCiID sets the "second_ci_id" field.
func (crc *CiRelationCreate) SetSecondCiID(u uint64) *CiRelationCreate {
	crc.mutation.SetSecondCiID(u)
	return crc
}

// SetRelationTypeID sets the "relation_type_id" field.
func (crc *CiRelationCreate) SetRelationTypeID(u uint64) *CiRelationCreate {
	crc.mutation.SetRelationTypeID(u)
	return crc
}

// SetMore sets the "more" field.
func (crc *CiRelationCreate) SetMore(u uint64) *CiRelationCreate {
	crc.mutation.SetMore(u)
	return crc
}

// SetNillableMore sets the "more" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableMore(u *uint64) *CiRelationCreate {
	if u != nil {
		crc.SetMore(*u)
	}
	return crc
}

// SetSource sets the "source" field.
func (crc *CiRelationCreate) SetSource(s string) *CiRelationCreate {
	crc.mutation.SetSource(s)
	return crc
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableSource(s *string) *CiRelationCreate {
	if s != nil {
		crc.SetSource(*s)
	}
	return crc
}

// SetAncestorIds sets the "ancestor_ids" field.
func (crc *CiRelationCreate) SetAncestorIds(s string) *CiRelationCreate {
	crc.mutation.SetAncestorIds(s)
	return crc
}

// SetNillableAncestorIds sets the "ancestor_ids" field if the given value is not nil.
func (crc *CiRelationCreate) SetNillableAncestorIds(s *string) *CiRelationCreate {
	if s != nil {
		crc.SetAncestorIds(*s)
	}
	return crc
}

// SetID sets the "id" field.
func (crc *CiRelationCreate) SetID(u uint64) *CiRelationCreate {
	crc.mutation.SetID(u)
	return crc
}

// SetFirstCi sets the "first_ci" edge to the Cis entity.
func (crc *CiRelationCreate) SetFirstCi(c *Cis) *CiRelationCreate {
	return crc.SetFirstCiID(c.ID)
}

// SetSecondCi sets the "second_ci" edge to the Cis entity.
func (crc *CiRelationCreate) SetSecondCi(c *Cis) *CiRelationCreate {
	return crc.SetSecondCiID(c.ID)
}

// SetRelationType sets the "relation_type" edge to the RelationType entity.
func (crc *CiRelationCreate) SetRelationType(r *RelationType) *CiRelationCreate {
	return crc.SetRelationTypeID(r.ID)
}

// SetMoreCiID sets the "more_ci" edge to the Cis entity by ID.
func (crc *CiRelationCreate) SetMoreCiID(id uint64) *CiRelationCreate {
	crc.mutation.SetMoreCiID(id)
	return crc
}

// SetNillableMoreCiID sets the "more_ci" edge to the Cis entity by ID if the given value is not nil.
func (crc *CiRelationCreate) SetNillableMoreCiID(id *uint64) *CiRelationCreate {
	if id != nil {
		crc = crc.SetMoreCiID(*id)
	}
	return crc
}

// SetMoreCi sets the "more_ci" edge to the Cis entity.
func (crc *CiRelationCreate) SetMoreCi(c *Cis) *CiRelationCreate {
	return crc.SetMoreCiID(c.ID)
}

// Mutation returns the CiRelationMutation object of the builder.
func (crc *CiRelationCreate) Mutation() *CiRelationMutation {
	return crc.mutation
}

// Save creates the CiRelation in the database.
func (crc *CiRelationCreate) Save(ctx context.Context) (*CiRelation, error) {
	if err := crc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, crc.sqlSave, crc.mutation, crc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (crc *CiRelationCreate) SaveX(ctx context.Context) *CiRelation {
	v, err := crc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crc *CiRelationCreate) Exec(ctx context.Context) error {
	_, err := crc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crc *CiRelationCreate) ExecX(ctx context.Context) {
	if err := crc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (crc *CiRelationCreate) defaults() error {
	if _, ok := crc.mutation.CreatedAt(); !ok {
		if cirelation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized cirelation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := cirelation.DefaultCreatedAt()
		crc.mutation.SetCreatedAt(v)
	}
	if _, ok := crc.mutation.UpdatedAt(); !ok {
		if cirelation.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized cirelation.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := cirelation.DefaultUpdatedAt()
		crc.mutation.SetUpdatedAt(v)
	}
	if _, ok := crc.mutation.TenantID(); !ok {
		v := cirelation.DefaultTenantID
		crc.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (crc *CiRelationCreate) check() error {
	if _, ok := crc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CiRelation.created_at"`)}
	}
	if _, ok := crc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CiRelation.updated_at"`)}
	}
	if _, ok := crc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CiRelation.tenant_id"`)}
	}
	if _, ok := crc.mutation.FirstCiID(); !ok {
		return &ValidationError{Name: "first_ci_id", err: errors.New(`ent: missing required field "CiRelation.first_ci_id"`)}
	}
	if _, ok := crc.mutation.SecondCiID(); !ok {
		return &ValidationError{Name: "second_ci_id", err: errors.New(`ent: missing required field "CiRelation.second_ci_id"`)}
	}
	if _, ok := crc.mutation.RelationTypeID(); !ok {
		return &ValidationError{Name: "relation_type_id", err: errors.New(`ent: missing required field "CiRelation.relation_type_id"`)}
	}
	if v, ok := crc.mutation.AncestorIds(); ok {
		if err := cirelation.AncestorIdsValidator(v); err != nil {
			return &ValidationError{Name: "ancestor_ids", err: fmt.Errorf(`ent: validator failed for field "CiRelation.ancestor_ids": %w`, err)}
		}
	}
	if len(crc.mutation.FirstCiIDs()) == 0 {
		return &ValidationError{Name: "first_ci", err: errors.New(`ent: missing required edge "CiRelation.first_ci"`)}
	}
	if len(crc.mutation.SecondCiIDs()) == 0 {
		return &ValidationError{Name: "second_ci", err: errors.New(`ent: missing required edge "CiRelation.second_ci"`)}
	}
	if len(crc.mutation.RelationTypeIDs()) == 0 {
		return &ValidationError{Name: "relation_type", err: errors.New(`ent: missing required edge "CiRelation.relation_type"`)}
	}
	return nil
}

func (crc *CiRelationCreate) sqlSave(ctx context.Context) (*CiRelation, error) {
	if err := crc.check(); err != nil {
		return nil, err
	}
	_node, _spec := crc.createSpec()
	if err := sqlgraph.CreateNode(ctx, crc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	crc.mutation.id = &_node.ID
	crc.mutation.done = true
	return _node, nil
}

func (crc *CiRelationCreate) createSpec() (*CiRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &CiRelation{config: crc.config}
		_spec = sqlgraph.NewCreateSpec(cirelation.Table, sqlgraph.NewFieldSpec(cirelation.FieldID, field.TypeUint64))
	)
	if id, ok := crc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := crc.mutation.CreatedAt(); ok {
		_spec.SetField(cirelation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := crc.mutation.UpdatedAt(); ok {
		_spec.SetField(cirelation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := crc.mutation.DeletedAt(); ok {
		_spec.SetField(cirelation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := crc.mutation.TenantID(); ok {
		_spec.SetField(cirelation.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := crc.mutation.DepartmentID(); ok {
		_spec.SetField(cirelation.FieldDepartmentID, field.TypeUint64, value)
		_node.DepartmentID = value
	}
	if value, ok := crc.mutation.Source(); ok {
		_spec.SetField(cirelation.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := crc.mutation.AncestorIds(); ok {
		_spec.SetField(cirelation.FieldAncestorIds, field.TypeString, value)
		_node.AncestorIds = value
	}
	if nodes := crc.mutation.FirstCiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cirelation.FirstCiTable,
			Columns: []string{cirelation.FirstCiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cis.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FirstCiID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := crc.mutation.SecondCiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cirelation.SecondCiTable,
			Columns: []string{cirelation.SecondCiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cis.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SecondCiID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := crc.mutation.RelationTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cirelation.RelationTypeTable,
			Columns: []string{cirelation.RelationTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationtype.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RelationTypeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := crc.mutation.MoreCiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cirelation.MoreCiTable,
			Columns: []string{cirelation.MoreCiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cis.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.More = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CiRelationCreateBulk is the builder for creating many CiRelation entities in bulk.
type CiRelationCreateBulk struct {
	config
	err      error
	builders []*CiRelationCreate
}

// Save creates the CiRelation entities in the database.
func (crcb *CiRelationCreateBulk) Save(ctx context.Context) ([]*CiRelation, error) {
	if crcb.err != nil {
		return nil, crcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(crcb.builders))
	nodes := make([]*CiRelation, len(crcb.builders))
	mutators := make([]Mutator, len(crcb.builders))
	for i := range crcb.builders {
		func(i int, root context.Context) {
			builder := crcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CiRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, crcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, crcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, crcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (crcb *CiRelationCreateBulk) SaveX(ctx context.Context) []*CiRelation {
	v, err := crcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crcb *CiRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := crcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crcb *CiRelationCreateBulk) ExecX(ctx context.Context) {
	if err := crcb.Exec(ctx); err != nil {
		panic(err)
	}
}
