// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/cistatisticsfact"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
)

// CiStatisticsFactUpdate is the builder for updating CiStatisticsFact entities.
type CiStatisticsFactUpdate struct {
	config
	hooks    []Hook
	mutation *CiStatisticsFactMutation
}

// Where appends a list predicates to the CiStatisticsFactUpdate builder.
func (_u *CiStatisticsFactUpdate) Where(ps ...predicate.CiStatisticsFact) *CiStatisticsFactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CiStatisticsFactUpdate) SetUpdatedAt(v time.Time) *CiStatisticsFactUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *CiStatisticsFactUpdate) SetDepartmentID(v uint64) *CiStatisticsFactUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableDepartmentID(v *uint64) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *CiStatisticsFactUpdate) AddDepartmentID(v int64) *CiStatisticsFactUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *CiStatisticsFactUpdate) ClearDepartmentID() *CiStatisticsFactUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCiTypeID sets the "ci_type_id" field.
func (_u *CiStatisticsFactUpdate) SetCiTypeID(v uint64) *CiStatisticsFactUpdate {
	_u.mutation.ResetCiTypeID()
	_u.mutation.SetCiTypeID(v)
	return _u
}

// SetNillableCiTypeID sets the "ci_type_id" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableCiTypeID(v *uint64) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetCiTypeID(*v)
	}
	return _u
}

// AddCiTypeID adds value to the "ci_type_id" field.
func (_u *CiStatisticsFactUpdate) AddCiTypeID(v int64) *CiStatisticsFactUpdate {
	_u.mutation.AddCiTypeID(v)
	return _u
}

// SetCiCount sets the "ci_count" field.
func (_u *CiStatisticsFactUpdate) SetCiCount(v uint64) *CiStatisticsFactUpdate {
	_u.mutation.ResetCiCount()
	_u.mutation.SetCiCount(v)
	return _u
}

// SetNillableCiCount sets the "ci_count" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableCiCount(v *uint64) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetCiCount(*v)
	}
	return _u
}

// AddCiCount adds value to the "ci_count" field.
func (_u *CiStatisticsFactUpdate) AddCiCount(v int64) *CiStatisticsFactUpdate {
	_u.mutation.AddCiCount(v)
	return _u
}

// SetAttributeDistribution sets the "attribute_distribution" field.
func (_u *CiStatisticsFactUpdate) SetAttributeDistribution(v map[string]interface{}) *CiStatisticsFactUpdate {
	_u.mutation.SetAttributeDistribution(v)
	return _u
}

// ClearAttributeDistribution clears the value of the "attribute_distribution" field.
func (_u *CiStatisticsFactUpdate) ClearAttributeDistribution() *CiStatisticsFactUpdate {
	_u.mutation.ClearAttributeDistribution()
	return _u
}

// SetRelationMetrics sets the "relation_metrics" field.
func (_u *CiStatisticsFactUpdate) SetRelationMetrics(v map[string]interface{}) *CiStatisticsFactUpdate {
	_u.mutation.SetRelationMetrics(v)
	return _u
}

// ClearRelationMetrics clears the value of the "relation_metrics" field.
func (_u *CiStatisticsFactUpdate) ClearRelationMetrics() *CiStatisticsFactUpdate {
	_u.mutation.ClearRelationMetrics()
	return _u
}

// SetLifecycleStage sets the "lifecycle_stage" field.
func (_u *CiStatisticsFactUpdate) SetLifecycleStage(v cistatisticsfact.LifecycleStage) *CiStatisticsFactUpdate {
	_u.mutation.SetLifecycleStage(v)
	return _u
}

// SetNillableLifecycleStage sets the "lifecycle_stage" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableLifecycleStage(v *cistatisticsfact.LifecycleStage) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetLifecycleStage(*v)
	}
	return _u
}

// SetStatusDistribution sets the "status_distribution" field.
func (_u *CiStatisticsFactUpdate) SetStatusDistribution(v map[string]interface{}) *CiStatisticsFactUpdate {
	_u.mutation.SetStatusDistribution(v)
	return _u
}

// ClearStatusDistribution clears the value of the "status_distribution" field.
func (_u *CiStatisticsFactUpdate) ClearStatusDistribution() *CiStatisticsFactUpdate {
	_u.mutation.ClearStatusDistribution()
	return _u
}

// SetDepartmentDistribution sets the "department_distribution" field.
func (_u *CiStatisticsFactUpdate) SetDepartmentDistribution(v map[string]interface{}) *CiStatisticsFactUpdate {
	_u.mutation.SetDepartmentDistribution(v)
	return _u
}

// ClearDepartmentDistribution clears the value of the "department_distribution" field.
func (_u *CiStatisticsFactUpdate) ClearDepartmentDistribution() *CiStatisticsFactUpdate {
	_u.mutation.ClearDepartmentDistribution()
	return _u
}

// SetUserActivity sets the "user_activity" field.
func (_u *CiStatisticsFactUpdate) SetUserActivity(v map[string]interface{}) *CiStatisticsFactUpdate {
	_u.mutation.SetUserActivity(v)
	return _u
}

// ClearUserActivity clears the value of the "user_activity" field.
func (_u *CiStatisticsFactUpdate) ClearUserActivity() *CiStatisticsFactUpdate {
	_u.mutation.ClearUserActivity()
	return _u
}

// SetTimeWindow sets the "time_window" field.
func (_u *CiStatisticsFactUpdate) SetTimeWindow(v cistatisticsfact.TimeWindow) *CiStatisticsFactUpdate {
	_u.mutation.SetTimeWindow(v)
	return _u
}

// SetNillableTimeWindow sets the "time_window" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableTimeWindow(v *cistatisticsfact.TimeWindow) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetTimeWindow(*v)
	}
	return _u
}

// SetStatTime sets the "stat_time" field.
func (_u *CiStatisticsFactUpdate) SetStatTime(v time.Time) *CiStatisticsFactUpdate {
	_u.mutation.SetStatTime(v)
	return _u
}

// SetNillableStatTime sets the "stat_time" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableStatTime(v *time.Time) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetStatTime(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CiStatisticsFactUpdate) SetVersion(v uint64) *CiStatisticsFactUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableVersion(v *uint64) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CiStatisticsFactUpdate) AddVersion(v int64) *CiStatisticsFactUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetComputeStatus sets the "compute_status" field.
func (_u *CiStatisticsFactUpdate) SetComputeStatus(v cistatisticsfact.ComputeStatus) *CiStatisticsFactUpdate {
	_u.mutation.SetComputeStatus(v)
	return _u
}

// SetNillableComputeStatus sets the "compute_status" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableComputeStatus(v *cistatisticsfact.ComputeStatus) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetComputeStatus(*v)
	}
	return _u
}

// SetDataHash sets the "data_hash" field.
func (_u *CiStatisticsFactUpdate) SetDataHash(v string) *CiStatisticsFactUpdate {
	_u.mutation.SetDataHash(v)
	return _u
}

// SetNillableDataHash sets the "data_hash" field if the given value is not nil.
func (_u *CiStatisticsFactUpdate) SetNillableDataHash(v *string) *CiStatisticsFactUpdate {
	if v != nil {
		_u.SetDataHash(*v)
	}
	return _u
}

// ClearDataHash clears the value of the "data_hash" field.
func (_u *CiStatisticsFactUpdate) ClearDataHash() *CiStatisticsFactUpdate {
	_u.mutation.ClearDataHash()
	return _u
}

// Mutation returns the CiStatisticsFactMutation object of the builder.
func (_u *CiStatisticsFactUpdate) Mutation() *CiStatisticsFactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CiStatisticsFactUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CiStatisticsFactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CiStatisticsFactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CiStatisticsFactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CiStatisticsFactUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cistatisticsfact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CiStatisticsFactUpdate) check() error {
	if v, ok := _u.mutation.LifecycleStage(); ok {
		if err := cistatisticsfact.LifecycleStageValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle_stage", err: fmt.Errorf(`ent: validator failed for field "CiStatisticsFact.lifecycle_stage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeWindow(); ok {
		if err := cistatisticsfact.TimeWindowValidator(v); err != nil {
			return &ValidationError{Name: "time_window", err: fmt.Errorf(`ent: validator failed for field "CiStatisticsFact.time_window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ComputeStatus(); ok {
		if err := cistatisticsfact.ComputeStatusValidator(v); err != nil {
			return &ValidationError{Name: "compute_status", err: fmt.Errorf(`ent: validator failed for field "CiStatisticsFact.compute_status": %w`, err)}
		}
	}
	return nil
}

func (_u *CiStatisticsFactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cistatisticsfact.Table, cistatisticsfact.Columns, sqlgraph.NewFieldSpec(cistatisticsfact.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cistatisticsfact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(cistatisticsfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(cistatisticsfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(cistatisticsfact.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CiTypeID(); ok {
		_spec.SetField(cistatisticsfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiTypeID(); ok {
		_spec.AddField(cistatisticsfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CiCount(); ok {
		_spec.SetField(cistatisticsfact.FieldCiCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiCount(); ok {
		_spec.AddField(cistatisticsfact.FieldCiCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AttributeDistribution(); ok {
		_spec.SetField(cistatisticsfact.FieldAttributeDistribution, field.TypeJSON, value)
	}
	if _u.mutation.AttributeDistributionCleared() {
		_spec.ClearField(cistatisticsfact.FieldAttributeDistribution, field.TypeJSON)
	}
	if value, ok := _u.mutation.RelationMetrics(); ok {
		_spec.SetField(cistatisticsfact.FieldRelationMetrics, field.TypeJSON, value)
	}
	if _u.mutation.RelationMetricsCleared() {
		_spec.ClearField(cistatisticsfact.FieldRelationMetrics, field.TypeJSON)
	}
	if value, ok := _u.mutation.LifecycleStage(); ok {
		_spec.SetField(cistatisticsfact.FieldLifecycleStage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusDistribution(); ok {
		_spec.SetField(cistatisticsfact.FieldStatusDistribution, field.TypeJSON, value)
	}
	if _u.mutation.StatusDistributionCleared() {
		_spec.ClearField(cistatisticsfact.FieldStatusDistribution, field.TypeJSON)
	}
	if value, ok := _u.mutation.DepartmentDistribution(); ok {
		_spec.SetField(cistatisticsfact.FieldDepartmentDistribution, field.TypeJSON, value)
	}
	if _u.mutation.DepartmentDistributionCleared() {
		_spec.ClearField(cistatisticsfact.FieldDepartmentDistribution, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserActivity(); ok {
		_spec.SetField(cistatisticsfact.FieldUserActivity, field.TypeJSON, value)
	}
	if _u.mutation.UserActivityCleared() {
		_spec.ClearField(cistatisticsfact.FieldUserActivity, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeWindow(); ok {
		_spec.SetField(cistatisticsfact.FieldTimeWindow, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatTime(); ok {
		_spec.SetField(cistatisticsfact.FieldStatTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(cistatisticsfact.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(cistatisticsfact.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ComputeStatus(); ok {
		_spec.SetField(cistatisticsfact.FieldComputeStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DataHash(); ok {
		_spec.SetField(cistatisticsfact.FieldDataHash, field.TypeString, value)
	}
	if _u.mutation.DataHashCleared() {
		_spec.ClearField(cistatisticsfact.FieldDataHash, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cistatisticsfact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CiStatisticsFactUpdateOne is the builder for updating a single CiStatisticsFact entity.
type CiStatisticsFactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CiStatisticsFactMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CiStatisticsFactUpdateOne) SetUpdatedAt(v time.Time) *CiStatisticsFactUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *CiStatisticsFactUpdateOne) SetDepartmentID(v uint64) *CiStatisticsFactUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableDepartmentID(v *uint64) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *CiStatisticsFactUpdateOne) AddDepartmentID(v int64) *CiStatisticsFactUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *CiStatisticsFactUpdateOne) ClearDepartmentID() *CiStatisticsFactUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCiTypeID sets the "ci_type_id" field.
func (_u *CiStatisticsFactUpdateOne) SetCiTypeID(v uint64) *CiStatisticsFactUpdateOne {
	_u.mutation.ResetCiTypeID()
	_u.mutation.SetCiTypeID(v)
	return _u
}

// SetNillableCiTypeID sets the "ci_type_id" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableCiTypeID(v *uint64) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetCiTypeID(*v)
	}
	return _u
}

// AddCiTypeID adds value to the "ci_type_id" field.
func (_u *CiStatisticsFactUpdateOne) AddCiTypeID(v int64) *CiStatisticsFactUpdateOne {
	_u.mutation.AddCiTypeID(v)
	return _u
}

// SetCiCount sets the "ci_count" field.
func (_u *CiStatisticsFactUpdateOne) SetCiCount(v uint64) *CiStatisticsFactUpdateOne {
	_u.mutation.ResetCiCount()
	_u.mutation.SetCiCount(v)
	return _u
}

// SetNillableCiCount sets the "ci_count" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableCiCount(v *uint64) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetCiCount(*v)
	}
	return _u
}

// AddCiCount adds value to the "ci_count" field.
func (_u *CiStatisticsFactUpdateOne) AddCiCount(v int64) *CiStatisticsFactUpdateOne {
	_u.mutation.AddCiCount(v)
	return _u
}

// SetAttributeDistribution sets the "attribute_distribution" field.
func (_u *CiStatisticsFactUpdateOne) SetAttributeDistribution(v map[string]interface{}) *CiStatisticsFactUpdateOne {
	_u.mutation.SetAttributeDistribution(v)
	return _u
}

// ClearAttributeDistribution clears the value of the "attribute_distribution" field.
func (_u *CiStatisticsFactUpdateOne) ClearAttributeDistribution() *CiStatisticsFactUpdateOne {
	_u.mutation.ClearAttributeDistribution()
	return _u
}

// SetRelationMetrics sets the "relation_metrics" field.
func (_u *CiStatisticsFactUpdateOne) SetRelationMetrics(v map[string]interface{}) *CiStatisticsFactUpdateOne {
	_u.mutation.SetRelationMetrics(v)
	return _u
}

// ClearRelationMetrics clears the value of the "relation_metrics" field.
func (_u *CiStatisticsFactUpdateOne) ClearRelationMetrics() *CiStatisticsFactUpdateOne {
	_u.mutation.ClearRelationMetrics()
	return _u
}

// SetLifecycleStage sets the "lifecycle_stage" field.
func (_u *CiStatisticsFactUpdateOne) SetLifecycleStage(v cistatisticsfact.LifecycleStage) *CiStatisticsFactUpdateOne {
	_u.mutation.SetLifecycleStage(v)
	return _u
}

// SetNillableLifecycleStage sets the "lifecycle_stage" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableLifecycleStage(v *cistatisticsfact.LifecycleStage) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetLifecycleStage(*v)
	}
	return _u
}

// SetStatusDistribution sets the "status_distribution" field.
func (_u *CiStatisticsFactUpdateOne) SetStatusDistribution(v map[string]interface{}) *CiStatisticsFactUpdateOne {
	_u.mutation.SetStatusDistribution(v)
	return _u
}

// ClearStatusDistribution clears the value of the "status_distribution" field.
func (_u *CiStatisticsFactUpdateOne) ClearStatusDistribution() *CiStatisticsFactUpdateOne {
	_u.mutation.ClearStatusDistribution()
	return _u
}

// SetDepartmentDistribution sets the "department_distribution" field.
func (_u *CiStatisticsFactUpdateOne) SetDepartmentDistribution(v map[string]interface{}) *CiStatisticsFactUpdateOne {
	_u.mutation.SetDepartmentDistribution(v)
	return _u
}

// ClearDepartmentDistribution clears the value of the "department_distribution" field.
func (_u *CiStatisticsFactUpdateOne) ClearDepartmentDistribution() *CiStatisticsFactUpdateOne {
	_u.mutation.ClearDepartmentDistribution()
	return _u
}

// SetUserActivity sets the "user_activity" field.
func (_u *CiStatisticsFactUpdateOne) SetUserActivity(v map[string]interface{}) *CiStatisticsFactUpdateOne {
	_u.mutation.SetUserActivity(v)
	return _u
}

// ClearUserActivity clears the value of the "user_activity" field.
func (_u *CiStatisticsFactUpdateOne) ClearUserActivity() *CiStatisticsFactUpdateOne {
	_u.mutation.ClearUserActivity()
	return _u
}

// SetTimeWindow sets the "time_window" field.
func (_u *CiStatisticsFactUpdateOne) SetTimeWindow(v cistatisticsfact.TimeWindow) *CiStatisticsFactUpdateOne {
	_u.mutation.SetTimeWindow(v)
	return _u
}

// SetNillableTimeWindow sets the "time_window" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableTimeWindow(v *cistatisticsfact.TimeWindow) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetTimeWindow(*v)
	}
	return _u
}

// SetStatTime sets the "stat_time" field.
func (_u *CiStatisticsFactUpdateOne) SetStatTime(v time.Time) *CiStatisticsFactUpdateOne {
	_u.mutation.SetStatTime(v)
	return _u
}

// SetNillableStatTime sets the "stat_time" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableStatTime(v *time.Time) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetStatTime(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CiStatisticsFactUpdateOne) SetVersion(v uint64) *CiStatisticsFactUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableVersion(v *uint64) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CiStatisticsFactUpdateOne) AddVersion(v int64) *CiStatisticsFactUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetComputeStatus sets the "compute_status" field.
func (_u *CiStatisticsFactUpdateOne) SetComputeStatus(v cistatisticsfact.ComputeStatus) *CiStatisticsFactUpdateOne {
	_u.mutation.SetComputeStatus(v)
	return _u
}

// SetNillableComputeStatus sets the "compute_status" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableComputeStatus(v *cistatisticsfact.ComputeStatus) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetComputeStatus(*v)
	}
	return _u
}

// SetDataHash sets the "data_hash" field.
func (_u *CiStatisticsFactUpdateOne) SetDataHash(v string) *CiStatisticsFactUpdateOne {
	_u.mutation.SetDataHash(v)
	return _u
}

// SetNillableDataHash sets the "data_hash" field if the given value is not nil.
func (_u *CiStatisticsFactUpdateOne) SetNillableDataHash(v *string) *CiStatisticsFactUpdateOne {
	if v != nil {
		_u.SetDataHash(*v)
	}
	return _u
}

// ClearDataHash clears the value of the "data_hash" field.
func (_u *CiStatisticsFactUpdateOne) ClearDataHash() *CiStatisticsFactUpdateOne {
	_u.mutation.ClearDataHash()
	return _u
}

// Mutation returns the CiStatisticsFactMutation object of the builder.
func (_u *CiStatisticsFactUpdateOne) Mutation() *CiStatisticsFactMutation {
	return _u.mutation
}

// Where appends a list predicates to the CiStatisticsFactUpdate builder.
func (_u *CiStatisticsFactUpdateOne) Where(ps ...predicate.CiStatisticsFact) *CiStatisticsFactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CiStatisticsFactUpdateOne) Select(field string, fields ...string) *CiStatisticsFactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CiStatisticsFact entity.
func (_u *CiStatisticsFactUpdateOne) Save(ctx context.Context) (*CiStatisticsFact, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CiStatisticsFactUpdateOne) SaveX(ctx context.Context) *CiStatisticsFact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CiStatisticsFactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CiStatisticsFactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CiStatisticsFactUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cistatisticsfact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CiStatisticsFactUpdateOne) check() error {
	if v, ok := _u.mutation.LifecycleStage(); ok {
		if err := cistatisticsfact.LifecycleStageValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle_stage", err: fmt.Errorf(`ent: validator failed for field "CiStatisticsFact.lifecycle_stage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeWindow(); ok {
		if err := cistatisticsfact.TimeWindowValidator(v); err != nil {
			return &ValidationError{Name: "time_window", err: fmt.Errorf(`ent: validator failed for field "CiStatisticsFact.time_window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ComputeStatus(); ok {
		if err := cistatisticsfact.ComputeStatusValidator(v); err != nil {
			return &ValidationError{Name: "compute_status", err: fmt.Errorf(`ent: validator failed for field "CiStatisticsFact.compute_status": %w`, err)}
		}
	}
	return nil
}

func (_u *CiStatisticsFactUpdateOne) sqlSave(ctx context.Context) (_node *CiStatisticsFact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cistatisticsfact.Table, cistatisticsfact.Columns, sqlgraph.NewFieldSpec(cistatisticsfact.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CiStatisticsFact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cistatisticsfact.FieldID)
		for _, f := range fields {
			if !cistatisticsfact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cistatisticsfact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cistatisticsfact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(cistatisticsfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(cistatisticsfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(cistatisticsfact.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CiTypeID(); ok {
		_spec.SetField(cistatisticsfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiTypeID(); ok {
		_spec.AddField(cistatisticsfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CiCount(); ok {
		_spec.SetField(cistatisticsfact.FieldCiCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiCount(); ok {
		_spec.AddField(cistatisticsfact.FieldCiCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AttributeDistribution(); ok {
		_spec.SetField(cistatisticsfact.FieldAttributeDistribution, field.TypeJSON, value)
	}
	if _u.mutation.AttributeDistributionCleared() {
		_spec.ClearField(cistatisticsfact.FieldAttributeDistribution, field.TypeJSON)
	}
	if value, ok := _u.mutation.RelationMetrics(); ok {
		_spec.SetField(cistatisticsfact.FieldRelationMetrics, field.TypeJSON, value)
	}
	if _u.mutation.RelationMetricsCleared() {
		_spec.ClearField(cistatisticsfact.FieldRelationMetrics, field.TypeJSON)
	}
	if value, ok := _u.mutation.LifecycleStage(); ok {
		_spec.SetField(cistatisticsfact.FieldLifecycleStage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusDistribution(); ok {
		_spec.SetField(cistatisticsfact.FieldStatusDistribution, field.TypeJSON, value)
	}
	if _u.mutation.StatusDistributionCleared() {
		_spec.ClearField(cistatisticsfact.FieldStatusDistribution, field.TypeJSON)
	}
	if value, ok := _u.mutation.DepartmentDistribution(); ok {
		_spec.SetField(cistatisticsfact.FieldDepartmentDistribution, field.TypeJSON, value)
	}
	if _u.mutation.DepartmentDistributionCleared() {
		_spec.ClearField(cistatisticsfact.FieldDepartmentDistribution, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserActivity(); ok {
		_spec.SetField(cistatisticsfact.FieldUserActivity, field.TypeJSON, value)
	}
	if _u.mutation.UserActivityCleared() {
		_spec.ClearField(cistatisticsfact.FieldUserActivity, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeWindow(); ok {
		_spec.SetField(cistatisticsfact.FieldTimeWindow, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatTime(); ok {
		_spec.SetField(cistatisticsfact.FieldStatTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(cistatisticsfact.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(cistatisticsfact.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ComputeStatus(); ok {
		_spec.SetField(cistatisticsfact.FieldComputeStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DataHash(); ok {
		_spec.SetField(cistatisticsfact.FieldDataHash, field.TypeString, value)
	}
	if _u.mutation.DataHashCleared() {
		_spec.ClearField(cistatisticsfact.FieldDataHash, field.TypeString)
	}
	_node = &CiStatisticsFact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cistatisticsfact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
