// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/link234/cmdb-rpc/ent/citypeattributegroup"
	"gitee.com/link234/cmdb-rpc/ent/predicate"
)

// CiTypeAttributeGroupDelete is the builder for deleting a CiTypeAttributeGroup entity.
type CiTypeAttributeGroupDelete struct {
	config
	hooks    []Hook
	mutation *CiTypeAttributeGroupMutation
}

// Where appends a list predicates to the CiTypeAttributeGroupDelete builder.
func (ctagd *CiTypeAttributeGroupDelete) Where(ps ...predicate.CiTypeAttributeGroup) *CiTypeAttributeGroupDelete {
	ctagd.mutation.Where(ps...)
	return ctagd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ctagd *CiTypeAttributeGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ctagd.sqlExec, ctagd.mutation, ctagd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ctagd *CiTypeAttributeGroupDelete) ExecX(ctx context.Context) int {
	n, err := ctagd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ctagd *CiTypeAttributeGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(citypeattributegroup.Table, sqlgraph.NewFieldSpec(citypeattributegroup.FieldID, field.TypeUint64))
	if ps := ctagd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ctagd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ctagd.mutation.done = true
	return affected, err
}

// CiTypeAttributeGroupDeleteOne is the builder for deleting a single CiTypeAttributeGroup entity.
type CiTypeAttributeGroupDeleteOne struct {
	ctagd *CiTypeAttributeGroupDelete
}

// Where appends a list predicates to the CiTypeAttributeGroupDelete builder.
func (ctagdo *CiTypeAttributeGroupDeleteOne) Where(ps ...predicate.CiTypeAttributeGroup) *CiTypeAttributeGroupDeleteOne {
	ctagdo.ctagd.mutation.Where(ps...)
	return ctagdo
}

// Exec executes the deletion query.
func (ctagdo *CiTypeAttributeGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := ctagdo.ctagd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{citypeattributegroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ctagdo *CiTypeAttributeGroupDeleteOne) ExecX(ctx context.Context) {
	if err := ctagdo.Exec(ctx); err != nil {
		panic(err)
	}
}
