// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/citypediscoveryconfig"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
)

// CiTypeDiscoveryConfigDelete is the builder for deleting a CiTypeDiscoveryConfig entity.
type CiTypeDiscoveryConfigDelete struct {
	config
	hooks    []Hook
	mutation *CiTypeDiscoveryConfigMutation
}

// Where appends a list predicates to the CiTypeDiscoveryConfigDelete builder.
func (_d *CiTypeDiscoveryConfigDelete) Where(ps ...predicate.CiTypeDiscoveryConfig) *CiTypeDiscoveryConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CiTypeDiscoveryConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CiTypeDiscoveryConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CiTypeDiscoveryConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(citypediscoveryconfig.Table, sqlgraph.NewFieldSpec(citypediscoveryconfig.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CiTypeDiscoveryConfigDeleteOne is the builder for deleting a single CiTypeDiscoveryConfig entity.
type CiTypeDiscoveryConfigDeleteOne struct {
	_d *CiTypeDiscoveryConfigDelete
}

// Where appends a list predicates to the CiTypeDiscoveryConfigDelete builder.
func (_d *CiTypeDiscoveryConfigDeleteOne) Where(ps ...predicate.CiTypeDiscoveryConfig) *CiTypeDiscoveryConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CiTypeDiscoveryConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{citypediscoveryconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CiTypeDiscoveryConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
