// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/citypegroup"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/citypegroupitem"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
)

// CiTypeGroupUpdate is the builder for updating CiTypeGroup entities.
type CiTypeGroupUpdate struct {
	config
	hooks    []Hook
	mutation *CiTypeGroupMutation
}

// Where appends a list predicates to the CiTypeGroupUpdate builder.
func (_u *CiTypeGroupUpdate) Where(ps ...predicate.CiTypeGroup) *CiTypeGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CiTypeGroupUpdate) SetUpdatedAt(v time.Time) *CiTypeGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSort sets the "sort" field.
func (_u *CiTypeGroupUpdate) SetSort(v uint32) *CiTypeGroupUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *CiTypeGroupUpdate) SetNillableSort(v *uint32) *CiTypeGroupUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *CiTypeGroupUpdate) AddSort(v int32) *CiTypeGroupUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *CiTypeGroupUpdate) SetDepartmentID(v uint64) *CiTypeGroupUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *CiTypeGroupUpdate) SetNillableDepartmentID(v *uint64) *CiTypeGroupUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *CiTypeGroupUpdate) AddDepartmentID(v int64) *CiTypeGroupUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *CiTypeGroupUpdate) ClearDepartmentID() *CiTypeGroupUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CiTypeGroupUpdate) SetDeletedAt(v time.Time) *CiTypeGroupUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CiTypeGroupUpdate) SetNillableDeletedAt(v *time.Time) *CiTypeGroupUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CiTypeGroupUpdate) ClearDeletedAt() *CiTypeGroupUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CiTypeGroupUpdate) SetName(v string) *CiTypeGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CiTypeGroupUpdate) SetNillableName(v *string) *CiTypeGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CiTypeGroupUpdate) SetDescription(v string) *CiTypeGroupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CiTypeGroupUpdate) SetNillableDescription(v *string) *CiTypeGroupUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *CiTypeGroupUpdate) SetIcon(v string) *CiTypeGroupUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *CiTypeGroupUpdate) SetNillableIcon(v *string) *CiTypeGroupUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *CiTypeGroupUpdate) ClearIcon() *CiTypeGroupUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// AddGroupItemIDs adds the "group_items" edge to the CiTypeGroupItem entity by IDs.
func (_u *CiTypeGroupUpdate) AddGroupItemIDs(ids ...uint64) *CiTypeGroupUpdate {
	_u.mutation.AddGroupItemIDs(ids...)
	return _u
}

// AddGroupItems adds the "group_items" edges to the CiTypeGroupItem entity.
func (_u *CiTypeGroupUpdate) AddGroupItems(v ...*CiTypeGroupItem) *CiTypeGroupUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupItemIDs(ids...)
}

// Mutation returns the CiTypeGroupMutation object of the builder.
func (_u *CiTypeGroupUpdate) Mutation() *CiTypeGroupMutation {
	return _u.mutation
}

// ClearGroupItems clears all "group_items" edges to the CiTypeGroupItem entity.
func (_u *CiTypeGroupUpdate) ClearGroupItems() *CiTypeGroupUpdate {
	_u.mutation.ClearGroupItems()
	return _u
}

// RemoveGroupItemIDs removes the "group_items" edge to CiTypeGroupItem entities by IDs.
func (_u *CiTypeGroupUpdate) RemoveGroupItemIDs(ids ...uint64) *CiTypeGroupUpdate {
	_u.mutation.RemoveGroupItemIDs(ids...)
	return _u
}

// RemoveGroupItems removes "group_items" edges to CiTypeGroupItem entities.
func (_u *CiTypeGroupUpdate) RemoveGroupItems(v ...*CiTypeGroupItem) *CiTypeGroupUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CiTypeGroupUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CiTypeGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CiTypeGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CiTypeGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CiTypeGroupUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if citypegroup.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized citypegroup.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := citypegroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CiTypeGroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := citypegroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CiTypeGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := citypegroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "CiTypeGroup.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := citypegroup.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "CiTypeGroup.icon": %w`, err)}
		}
	}
	return nil
}

func (_u *CiTypeGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(citypegroup.Table, citypegroup.Columns, sqlgraph.NewFieldSpec(citypegroup.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(citypegroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(citypegroup.FieldSort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(citypegroup.FieldSort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(citypegroup.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(citypegroup.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(citypegroup.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(citypegroup.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(citypegroup.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(citypegroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(citypegroup.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(citypegroup.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(citypegroup.FieldIcon, field.TypeString)
	}
	if _u.mutation.GroupItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   citypegroup.GroupItemsTable,
			Columns: []string{citypegroup.GroupItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypegroupitem.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupItemsIDs(); len(nodes) > 0 && !_u.mutation.GroupItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   citypegroup.GroupItemsTable,
			Columns: []string{citypegroup.GroupItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypegroupitem.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   citypegroup.GroupItemsTable,
			Columns: []string{citypegroup.GroupItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypegroupitem.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{citypegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CiTypeGroupUpdateOne is the builder for updating a single CiTypeGroup entity.
type CiTypeGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CiTypeGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CiTypeGroupUpdateOne) SetUpdatedAt(v time.Time) *CiTypeGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSort sets the "sort" field.
func (_u *CiTypeGroupUpdateOne) SetSort(v uint32) *CiTypeGroupUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *CiTypeGroupUpdateOne) SetNillableSort(v *uint32) *CiTypeGroupUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *CiTypeGroupUpdateOne) AddSort(v int32) *CiTypeGroupUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *CiTypeGroupUpdateOne) SetDepartmentID(v uint64) *CiTypeGroupUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *CiTypeGroupUpdateOne) SetNillableDepartmentID(v *uint64) *CiTypeGroupUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *CiTypeGroupUpdateOne) AddDepartmentID(v int64) *CiTypeGroupUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *CiTypeGroupUpdateOne) ClearDepartmentID() *CiTypeGroupUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CiTypeGroupUpdateOne) SetDeletedAt(v time.Time) *CiTypeGroupUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CiTypeGroupUpdateOne) SetNillableDeletedAt(v *time.Time) *CiTypeGroupUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CiTypeGroupUpdateOne) ClearDeletedAt() *CiTypeGroupUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CiTypeGroupUpdateOne) SetName(v string) *CiTypeGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CiTypeGroupUpdateOne) SetNillableName(v *string) *CiTypeGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CiTypeGroupUpdateOne) SetDescription(v string) *CiTypeGroupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CiTypeGroupUpdateOne) SetNillableDescription(v *string) *CiTypeGroupUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *CiTypeGroupUpdateOne) SetIcon(v string) *CiTypeGroupUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *CiTypeGroupUpdateOne) SetNillableIcon(v *string) *CiTypeGroupUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *CiTypeGroupUpdateOne) ClearIcon() *CiTypeGroupUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// AddGroupItemIDs adds the "group_items" edge to the CiTypeGroupItem entity by IDs.
func (_u *CiTypeGroupUpdateOne) AddGroupItemIDs(ids ...uint64) *CiTypeGroupUpdateOne {
	_u.mutation.AddGroupItemIDs(ids...)
	return _u
}

// AddGroupItems adds the "group_items" edges to the CiTypeGroupItem entity.
func (_u *CiTypeGroupUpdateOne) AddGroupItems(v ...*CiTypeGroupItem) *CiTypeGroupUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupItemIDs(ids...)
}

// Mutation returns the CiTypeGroupMutation object of the builder.
func (_u *CiTypeGroupUpdateOne) Mutation() *CiTypeGroupMutation {
	return _u.mutation
}

// ClearGroupItems clears all "group_items" edges to the CiTypeGroupItem entity.
func (_u *CiTypeGroupUpdateOne) ClearGroupItems() *CiTypeGroupUpdateOne {
	_u.mutation.ClearGroupItems()
	return _u
}

// RemoveGroupItemIDs removes the "group_items" edge to CiTypeGroupItem entities by IDs.
func (_u *CiTypeGroupUpdateOne) RemoveGroupItemIDs(ids ...uint64) *CiTypeGroupUpdateOne {
	_u.mutation.RemoveGroupItemIDs(ids...)
	return _u
}

// RemoveGroupItems removes "group_items" edges to CiTypeGroupItem entities.
func (_u *CiTypeGroupUpdateOne) RemoveGroupItems(v ...*CiTypeGroupItem) *CiTypeGroupUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupItemIDs(ids...)
}

// Where appends a list predicates to the CiTypeGroupUpdate builder.
func (_u *CiTypeGroupUpdateOne) Where(ps ...predicate.CiTypeGroup) *CiTypeGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CiTypeGroupUpdateOne) Select(field string, fields ...string) *CiTypeGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CiTypeGroup entity.
func (_u *CiTypeGroupUpdateOne) Save(ctx context.Context) (*CiTypeGroup, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CiTypeGroupUpdateOne) SaveX(ctx context.Context) *CiTypeGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CiTypeGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CiTypeGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CiTypeGroupUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if citypegroup.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized citypegroup.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := citypegroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CiTypeGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := citypegroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CiTypeGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := citypegroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "CiTypeGroup.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := citypegroup.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "CiTypeGroup.icon": %w`, err)}
		}
	}
	return nil
}

func (_u *CiTypeGroupUpdateOne) sqlSave(ctx context.Context) (_node *CiTypeGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(citypegroup.Table, citypegroup.Columns, sqlgraph.NewFieldSpec(citypegroup.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CiTypeGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, citypegroup.FieldID)
		for _, f := range fields {
			if !citypegroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != citypegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(citypegroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(citypegroup.FieldSort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(citypegroup.FieldSort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(citypegroup.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(citypegroup.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(citypegroup.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(citypegroup.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(citypegroup.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(citypegroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(citypegroup.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(citypegroup.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(citypegroup.FieldIcon, field.TypeString)
	}
	if _u.mutation.GroupItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   citypegroup.GroupItemsTable,
			Columns: []string{citypegroup.GroupItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypegroupitem.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupItemsIDs(); len(nodes) > 0 && !_u.mutation.GroupItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   citypegroup.GroupItemsTable,
			Columns: []string{citypegroup.GroupItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypegroupitem.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   citypegroup.GroupItemsTable,
			Columns: []string{citypegroup.GroupItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypegroupitem.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CiTypeGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{citypegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
