// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitee.com/link234/cmdb-rpc/ent/attribute"
	"gitee.com/link234/cmdb-rpc/ent/citype"
	"gitee.com/link234/cmdb-rpc/ent/citypeattribute"
)

// CiTypeAttribute is the model entity for the CiTypeAttribute schema.
type CiTypeAttribute struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Delete Time | 删除日期
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Sort Number | 排序编号
	Sort uint32 `json:"sort,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Department ID | 部门 ID
	DepartmentID uint64 `json:"department_id,omitempty"`
	// 外键，关联cmdb_ci_types.id
	TypeID uint64 `json:"type_id,omitempty"`
	// 外键，关联cmdb_attributes.id
	AttrID uint64 `json:"attr_id,omitempty"`
	// 是否必填
	IsRequired bool `json:"is_required,omitempty"`
	// 是否唯一
	IsUnique bool `json:"is_unique,omitempty"`
	// 是否列表
	IsList bool `json:"is_list,omitempty"`
	// 是否列表展示
	ListShow bool `json:"list_show,omitempty"`
	// 是否详情展示
	DetailShow bool `json:"detail_show,omitempty"`
	// 是否可编辑
	IsEdit bool `json:"is_edit,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CiTypeAttributeQuery when eager-loading is set.
	Edges        CiTypeAttributeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CiTypeAttributeEdges holds the relations/edges for other nodes in the graph.
type CiTypeAttributeEdges struct {
	// 关联cmdb_ci_types.id
	CiType *CiType `json:"ci_type,omitempty"`
	// 关联cmdb_attributes.id
	Attribute *Attribute `json:"attribute,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CiTypeOrErr returns the CiType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CiTypeAttributeEdges) CiTypeOrErr() (*CiType, error) {
	if e.CiType != nil {
		return e.CiType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: citype.Label}
	}
	return nil, &NotLoadedError{edge: "ci_type"}
}

// AttributeOrErr returns the Attribute value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CiTypeAttributeEdges) AttributeOrErr() (*Attribute, error) {
	if e.Attribute != nil {
		return e.Attribute, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: attribute.Label}
	}
	return nil, &NotLoadedError{edge: "attribute"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CiTypeAttribute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case citypeattribute.FieldIsRequired, citypeattribute.FieldIsUnique, citypeattribute.FieldIsList, citypeattribute.FieldListShow, citypeattribute.FieldDetailShow, citypeattribute.FieldIsEdit:
			values[i] = new(sql.NullBool)
		case citypeattribute.FieldID, citypeattribute.FieldSort, citypeattribute.FieldTenantID, citypeattribute.FieldDepartmentID, citypeattribute.FieldTypeID, citypeattribute.FieldAttrID:
			values[i] = new(sql.NullInt64)
		case citypeattribute.FieldCreatedAt, citypeattribute.FieldUpdatedAt, citypeattribute.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CiTypeAttribute fields.
func (cta *CiTypeAttribute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case citypeattribute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cta.ID = uint64(value.Int64)
		case citypeattribute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cta.CreatedAt = value.Time
			}
		case citypeattribute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cta.UpdatedAt = value.Time
			}
		case citypeattribute.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				cta.DeletedAt = value.Time
			}
		case citypeattribute.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				cta.Sort = uint32(value.Int64)
			}
		case citypeattribute.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				cta.TenantID = uint64(value.Int64)
			}
		case citypeattribute.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				cta.DepartmentID = uint64(value.Int64)
			}
		case citypeattribute.FieldTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type_id", values[i])
			} else if value.Valid {
				cta.TypeID = uint64(value.Int64)
			}
		case citypeattribute.FieldAttrID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attr_id", values[i])
			} else if value.Valid {
				cta.AttrID = uint64(value.Int64)
			}
		case citypeattribute.FieldIsRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_required", values[i])
			} else if value.Valid {
				cta.IsRequired = value.Bool
			}
		case citypeattribute.FieldIsUnique:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_unique", values[i])
			} else if value.Valid {
				cta.IsUnique = value.Bool
			}
		case citypeattribute.FieldIsList:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_list", values[i])
			} else if value.Valid {
				cta.IsList = value.Bool
			}
		case citypeattribute.FieldListShow:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field list_show", values[i])
			} else if value.Valid {
				cta.ListShow = value.Bool
			}
		case citypeattribute.FieldDetailShow:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field detail_show", values[i])
			} else if value.Valid {
				cta.DetailShow = value.Bool
			}
		case citypeattribute.FieldIsEdit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_edit", values[i])
			} else if value.Valid {
				cta.IsEdit = value.Bool
			}
		default:
			cta.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CiTypeAttribute.
// This includes values selected through modifiers, order, etc.
func (cta *CiTypeAttribute) Value(name string) (ent.Value, error) {
	return cta.selectValues.Get(name)
}

// QueryCiType queries the "ci_type" edge of the CiTypeAttribute entity.
func (cta *CiTypeAttribute) QueryCiType() *CiTypeQuery {
	return NewCiTypeAttributeClient(cta.config).QueryCiType(cta)
}

// QueryAttribute queries the "attribute" edge of the CiTypeAttribute entity.
func (cta *CiTypeAttribute) QueryAttribute() *AttributeQuery {
	return NewCiTypeAttributeClient(cta.config).QueryAttribute(cta)
}

// Update returns a builder for updating this CiTypeAttribute.
// Note that you need to call CiTypeAttribute.Unwrap() before calling this method if this CiTypeAttribute
// was returned from a transaction, and the transaction was committed or rolled back.
func (cta *CiTypeAttribute) Update() *CiTypeAttributeUpdateOne {
	return NewCiTypeAttributeClient(cta.config).UpdateOne(cta)
}

// Unwrap unwraps the CiTypeAttribute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cta *CiTypeAttribute) Unwrap() *CiTypeAttribute {
	_tx, ok := cta.config.driver.(*txDriver)
	if !ok {
		panic("ent: CiTypeAttribute is not a transactional entity")
	}
	cta.config.driver = _tx.drv
	return cta
}

// String implements the fmt.Stringer.
func (cta *CiTypeAttribute) String() string {
	var builder strings.Builder
	builder.WriteString("CiTypeAttribute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cta.ID))
	builder.WriteString("created_at=")
	builder.WriteString(cta.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(cta.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(cta.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", cta.Sort))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", cta.TenantID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", cta.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("type_id=")
	builder.WriteString(fmt.Sprintf("%v", cta.TypeID))
	builder.WriteString(", ")
	builder.WriteString("attr_id=")
	builder.WriteString(fmt.Sprintf("%v", cta.AttrID))
	builder.WriteString(", ")
	builder.WriteString("is_required=")
	builder.WriteString(fmt.Sprintf("%v", cta.IsRequired))
	builder.WriteString(", ")
	builder.WriteString("is_unique=")
	builder.WriteString(fmt.Sprintf("%v", cta.IsUnique))
	builder.WriteString(", ")
	builder.WriteString("is_list=")
	builder.WriteString(fmt.Sprintf("%v", cta.IsList))
	builder.WriteString(", ")
	builder.WriteString("list_show=")
	builder.WriteString(fmt.Sprintf("%v", cta.ListShow))
	builder.WriteString(", ")
	builder.WriteString("detail_show=")
	builder.WriteString(fmt.Sprintf("%v", cta.DetailShow))
	builder.WriteString(", ")
	builder.WriteString("is_edit=")
	builder.WriteString(fmt.Sprintf("%v", cta.IsEdit))
	builder.WriteByte(')')
	return builder.String()
}

// CiTypeAttributes is a parsable slice of CiTypeAttribute.
type CiTypeAttributes []*CiTypeAttribute
