// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/citypediscoveryconfig"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/discoveryexecutionhistory"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
)

// DiscoveryExecutionHistoryUpdate is the builder for updating DiscoveryExecutionHistory entities.
type DiscoveryExecutionHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *DiscoveryExecutionHistoryMutation
}

// Where appends a list predicates to the DiscoveryExecutionHistoryUpdate builder.
func (_u *DiscoveryExecutionHistoryUpdate) Where(ps ...predicate.DiscoveryExecutionHistory) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetUpdatedAt(v time.Time) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetDeletedAt(v time.Time) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableDeletedAt(v *time.Time) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearDeletedAt() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDiscoveryConfigID sets the "discovery_config_id" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetDiscoveryConfigID(v uint64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetDiscoveryConfigID(v)
	return _u
}

// SetNillableDiscoveryConfigID sets the "discovery_config_id" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableDiscoveryConfigID(v *uint64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetDiscoveryConfigID(*v)
	}
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetExecutionID(v string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableExecutionID(v *string) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetTriggerType(v string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableTriggerType(v *string) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetTriggeredBy(v uint64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetTriggeredBy()
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableTriggeredBy(v *uint64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// AddTriggeredBy adds value to the "triggered_by" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddTriggeredBy(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddTriggeredBy(v)
	return _u
}

// ClearTriggeredBy clears the value of the "triggered_by" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearTriggeredBy() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearTriggeredBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetStartedAt(v time.Time) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableStartedAt(v *time.Time) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetCompletedAt(v time.Time) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableCompletedAt(v *time.Time) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearCompletedAt() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetDurationSeconds(v int) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableDurationSeconds(v *int) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddDurationSeconds(v int) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearDurationSeconds() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearDurationSeconds()
	return _u
}

// SetExecStatus sets the "exec_status" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetExecStatus(v string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetExecStatus(v)
	return _u
}

// SetNillableExecStatus sets the "exec_status" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableExecStatus(v *string) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetExecStatus(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetStage(v string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableStage(v *string) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// ClearStage clears the value of the "stage" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearStage() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearStage()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetProgress(v int) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableProgress(v *int) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddProgress(v int) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetTotalRecords sets the "total_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetTotalRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetTotalRecords()
	_u.mutation.SetTotalRecords(v)
	return _u
}

// SetNillableTotalRecords sets the "total_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableTotalRecords(v *int64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetTotalRecords(*v)
	}
	return _u
}

// AddTotalRecords adds value to the "total_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddTotalRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddTotalRecords(v)
	return _u
}

// SetProcessedRecords sets the "processed_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetProcessedRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetProcessedRecords()
	_u.mutation.SetProcessedRecords(v)
	return _u
}

// SetNillableProcessedRecords sets the "processed_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableProcessedRecords(v *int64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetProcessedRecords(*v)
	}
	return _u
}

// AddProcessedRecords adds value to the "processed_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddProcessedRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddProcessedRecords(v)
	return _u
}

// SetSuccessRecords sets the "success_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetSuccessRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetSuccessRecords()
	_u.mutation.SetSuccessRecords(v)
	return _u
}

// SetNillableSuccessRecords sets the "success_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableSuccessRecords(v *int64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetSuccessRecords(*v)
	}
	return _u
}

// AddSuccessRecords adds value to the "success_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddSuccessRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddSuccessRecords(v)
	return _u
}

// SetFailedRecords sets the "failed_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetFailedRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetFailedRecords()
	_u.mutation.SetFailedRecords(v)
	return _u
}

// SetNillableFailedRecords sets the "failed_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableFailedRecords(v *int64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetFailedRecords(*v)
	}
	return _u
}

// AddFailedRecords adds value to the "failed_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddFailedRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddFailedRecords(v)
	return _u
}

// SetSkippedRecords sets the "skipped_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetSkippedRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetSkippedRecords()
	_u.mutation.SetSkippedRecords(v)
	return _u
}

// SetNillableSkippedRecords sets the "skipped_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableSkippedRecords(v *int64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetSkippedRecords(*v)
	}
	return _u
}

// AddSkippedRecords adds value to the "skipped_records" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddSkippedRecords(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddSkippedRecords(v)
	return _u
}

// SetCreatedCis sets the "created_cis" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetCreatedCis(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetCreatedCis()
	_u.mutation.SetCreatedCis(v)
	return _u
}

// SetNillableCreatedCis sets the "created_cis" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableCreatedCis(v *int64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetCreatedCis(*v)
	}
	return _u
}

// AddCreatedCis adds value to the "created_cis" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddCreatedCis(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddCreatedCis(v)
	return _u
}

// SetUpdatedCis sets the "updated_cis" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetUpdatedCis(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ResetUpdatedCis()
	_u.mutation.SetUpdatedCis(v)
	return _u
}

// SetNillableUpdatedCis sets the "updated_cis" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableUpdatedCis(v *int64) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetUpdatedCis(*v)
	}
	return _u
}

// AddUpdatedCis adds value to the "updated_cis" field.
func (_u *DiscoveryExecutionHistoryUpdate) AddUpdatedCis(v int64) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AddUpdatedCis(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetErrorMessage(v string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableErrorMessage(v *string) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearErrorMessage() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorDetails sets the "error_details" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetErrorDetails(v map[string]interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetErrorDetails(v)
	return _u
}

// ClearErrorDetails clears the value of the "error_details" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearErrorDetails() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearErrorDetails()
	return _u
}

// SetValidationErrors sets the "validation_errors" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetValidationErrors(v []interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetValidationErrors(v)
	return _u
}

// AppendValidationErrors appends value to the "validation_errors" field.
func (_u *DiscoveryExecutionHistoryUpdate) AppendValidationErrors(v []interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AppendValidationErrors(v)
	return _u
}

// ClearValidationErrors clears the value of the "validation_errors" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearValidationErrors() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearValidationErrors()
	return _u
}

// SetExecutionResult sets the "execution_result" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetExecutionResult(v map[string]interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetExecutionResult(v)
	return _u
}

// ClearExecutionResult clears the value of the "execution_result" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearExecutionResult() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearExecutionResult()
	return _u
}

// SetPerformanceMetrics sets the "performance_metrics" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetPerformanceMetrics(v map[string]interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetPerformanceMetrics(v)
	return _u
}

// ClearPerformanceMetrics clears the value of the "performance_metrics" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearPerformanceMetrics() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearPerformanceMetrics()
	return _u
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetConfigSnapshot(v map[string]interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetConfigSnapshot(v)
	return _u
}

// ClearConfigSnapshot clears the value of the "config_snapshot" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearConfigSnapshot() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearConfigSnapshot()
	return _u
}

// SetProviderInfo sets the "provider_info" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetProviderInfo(v map[string]interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetProviderInfo(v)
	return _u
}

// ClearProviderInfo clears the value of the "provider_info" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearProviderInfo() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearProviderInfo()
	return _u
}

// SetExecutionLog sets the "execution_log" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetExecutionLog(v string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetExecutionLog(v)
	return _u
}

// SetNillableExecutionLog sets the "execution_log" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdate) SetNillableExecutionLog(v *string) *DiscoveryExecutionHistoryUpdate {
	if v != nil {
		_u.SetExecutionLog(*v)
	}
	return _u
}

// ClearExecutionLog clears the value of the "execution_log" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearExecutionLog() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearExecutionLog()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetMetadata(v map[string]interface{}) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearMetadata() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetTags sets the "tags" field.
func (_u *DiscoveryExecutionHistoryUpdate) SetTags(v []string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *DiscoveryExecutionHistoryUpdate) AppendTags(v []string) *DiscoveryExecutionHistoryUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *DiscoveryExecutionHistoryUpdate) ClearTags() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetDiscoveryConfig sets the "discovery_config" edge to the CiTypeDiscoveryConfig entity.
func (_u *DiscoveryExecutionHistoryUpdate) SetDiscoveryConfig(v *CiTypeDiscoveryConfig) *DiscoveryExecutionHistoryUpdate {
	return _u.SetDiscoveryConfigID(v.ID)
}

// Mutation returns the DiscoveryExecutionHistoryMutation object of the builder.
func (_u *DiscoveryExecutionHistoryUpdate) Mutation() *DiscoveryExecutionHistoryMutation {
	return _u.mutation
}

// ClearDiscoveryConfig clears the "discovery_config" edge to the CiTypeDiscoveryConfig entity.
func (_u *DiscoveryExecutionHistoryUpdate) ClearDiscoveryConfig() *DiscoveryExecutionHistoryUpdate {
	_u.mutation.ClearDiscoveryConfig()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiscoveryExecutionHistoryUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscoveryExecutionHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiscoveryExecutionHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscoveryExecutionHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DiscoveryExecutionHistoryUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if discoveryexecutionhistory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized discoveryexecutionhistory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := discoveryexecutionhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscoveryExecutionHistoryUpdate) check() error {
	if _u.mutation.DiscoveryConfigCleared() && len(_u.mutation.DiscoveryConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiscoveryExecutionHistory.discovery_config"`)
	}
	return nil
}

func (_u *DiscoveryExecutionHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discoveryexecutionhistory.Table, discoveryexecutionhistory.Columns, sqlgraph.NewFieldSpec(discoveryexecutionhistory.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTriggeredBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTriggeredBy(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldTriggeredBy, field.TypeUint64, value)
	}
	if _u.mutation.TriggeredByCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldTriggeredBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.DurationSecondsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldDurationSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.ExecStatus(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldStage, field.TypeString, value)
	}
	if _u.mutation.StageCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldStage, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTotalRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldTotalRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProcessedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProcessedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProcessedRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldProcessedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldSuccessRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldSuccessRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FailedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldFailedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFailedRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldFailedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SkippedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldSkippedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSkippedRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldSkippedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedCis(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldCreatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedCis(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldCreatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedCis(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldUpdatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedCis(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldUpdatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorDetails(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldErrorDetails, field.TypeJSON, value)
	}
	if _u.mutation.ErrorDetailsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldErrorDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.ValidationErrors(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldValidationErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValidationErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, discoveryexecutionhistory.FieldValidationErrors, value)
		})
	}
	if _u.mutation.ValidationErrorsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldValidationErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExecutionResult(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionResult, field.TypeJSON, value)
	}
	if _u.mutation.ExecutionResultCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldExecutionResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.PerformanceMetrics(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldPerformanceMetrics, field.TypeJSON, value)
	}
	if _u.mutation.PerformanceMetricsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldPerformanceMetrics, field.TypeJSON)
	}
	if value, ok := _u.mutation.ConfigSnapshot(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldConfigSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ConfigSnapshotCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldConfigSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProviderInfo(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProviderInfo, field.TypeJSON, value)
	}
	if _u.mutation.ProviderInfoCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldProviderInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExecutionLog(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionLog, field.TypeString, value)
	}
	if _u.mutation.ExecutionLogCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldExecutionLog, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, discoveryexecutionhistory.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldTags, field.TypeJSON)
	}
	if _u.mutation.DiscoveryConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discoveryexecutionhistory.DiscoveryConfigTable,
			Columns: []string{discoveryexecutionhistory.DiscoveryConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypediscoveryconfig.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiscoveryConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discoveryexecutionhistory.DiscoveryConfigTable,
			Columns: []string{discoveryexecutionhistory.DiscoveryConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypediscoveryconfig.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discoveryexecutionhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiscoveryExecutionHistoryUpdateOne is the builder for updating a single DiscoveryExecutionHistory entity.
type DiscoveryExecutionHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscoveryExecutionHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetUpdatedAt(v time.Time) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetDeletedAt(v time.Time) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableDeletedAt(v *time.Time) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearDeletedAt() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDiscoveryConfigID sets the "discovery_config_id" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetDiscoveryConfigID(v uint64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetDiscoveryConfigID(v)
	return _u
}

// SetNillableDiscoveryConfigID sets the "discovery_config_id" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableDiscoveryConfigID(v *uint64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetDiscoveryConfigID(*v)
	}
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetExecutionID(v string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableExecutionID(v *string) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetTriggerType(v string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableTriggerType(v *string) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetTriggeredBy(v uint64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetTriggeredBy()
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableTriggeredBy(v *uint64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// AddTriggeredBy adds value to the "triggered_by" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddTriggeredBy(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddTriggeredBy(v)
	return _u
}

// ClearTriggeredBy clears the value of the "triggered_by" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearTriggeredBy() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearTriggeredBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetStartedAt(v time.Time) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableStartedAt(v *time.Time) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetCompletedAt(v time.Time) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableCompletedAt(v *time.Time) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearCompletedAt() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetDurationSeconds(v int) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableDurationSeconds(v *int) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddDurationSeconds(v int) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearDurationSeconds() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearDurationSeconds()
	return _u
}

// SetExecStatus sets the "exec_status" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetExecStatus(v string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetExecStatus(v)
	return _u
}

// SetNillableExecStatus sets the "exec_status" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableExecStatus(v *string) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetExecStatus(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetStage(v string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableStage(v *string) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// ClearStage clears the value of the "stage" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearStage() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearStage()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetProgress(v int) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableProgress(v *int) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddProgress(v int) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetTotalRecords sets the "total_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetTotalRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetTotalRecords()
	_u.mutation.SetTotalRecords(v)
	return _u
}

// SetNillableTotalRecords sets the "total_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableTotalRecords(v *int64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetTotalRecords(*v)
	}
	return _u
}

// AddTotalRecords adds value to the "total_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddTotalRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddTotalRecords(v)
	return _u
}

// SetProcessedRecords sets the "processed_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetProcessedRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetProcessedRecords()
	_u.mutation.SetProcessedRecords(v)
	return _u
}

// SetNillableProcessedRecords sets the "processed_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableProcessedRecords(v *int64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetProcessedRecords(*v)
	}
	return _u
}

// AddProcessedRecords adds value to the "processed_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddProcessedRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddProcessedRecords(v)
	return _u
}

// SetSuccessRecords sets the "success_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetSuccessRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetSuccessRecords()
	_u.mutation.SetSuccessRecords(v)
	return _u
}

// SetNillableSuccessRecords sets the "success_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableSuccessRecords(v *int64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetSuccessRecords(*v)
	}
	return _u
}

// AddSuccessRecords adds value to the "success_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddSuccessRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddSuccessRecords(v)
	return _u
}

// SetFailedRecords sets the "failed_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetFailedRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetFailedRecords()
	_u.mutation.SetFailedRecords(v)
	return _u
}

// SetNillableFailedRecords sets the "failed_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableFailedRecords(v *int64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetFailedRecords(*v)
	}
	return _u
}

// AddFailedRecords adds value to the "failed_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddFailedRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddFailedRecords(v)
	return _u
}

// SetSkippedRecords sets the "skipped_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetSkippedRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetSkippedRecords()
	_u.mutation.SetSkippedRecords(v)
	return _u
}

// SetNillableSkippedRecords sets the "skipped_records" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableSkippedRecords(v *int64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetSkippedRecords(*v)
	}
	return _u
}

// AddSkippedRecords adds value to the "skipped_records" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddSkippedRecords(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddSkippedRecords(v)
	return _u
}

// SetCreatedCis sets the "created_cis" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetCreatedCis(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetCreatedCis()
	_u.mutation.SetCreatedCis(v)
	return _u
}

// SetNillableCreatedCis sets the "created_cis" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableCreatedCis(v *int64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetCreatedCis(*v)
	}
	return _u
}

// AddCreatedCis adds value to the "created_cis" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddCreatedCis(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddCreatedCis(v)
	return _u
}

// SetUpdatedCis sets the "updated_cis" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetUpdatedCis(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ResetUpdatedCis()
	_u.mutation.SetUpdatedCis(v)
	return _u
}

// SetNillableUpdatedCis sets the "updated_cis" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableUpdatedCis(v *int64) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetUpdatedCis(*v)
	}
	return _u
}

// AddUpdatedCis adds value to the "updated_cis" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AddUpdatedCis(v int64) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AddUpdatedCis(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetErrorMessage(v string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableErrorMessage(v *string) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearErrorMessage() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorDetails sets the "error_details" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetErrorDetails(v map[string]interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetErrorDetails(v)
	return _u
}

// ClearErrorDetails clears the value of the "error_details" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearErrorDetails() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearErrorDetails()
	return _u
}

// SetValidationErrors sets the "validation_errors" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetValidationErrors(v []interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetValidationErrors(v)
	return _u
}

// AppendValidationErrors appends value to the "validation_errors" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AppendValidationErrors(v []interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AppendValidationErrors(v)
	return _u
}

// ClearValidationErrors clears the value of the "validation_errors" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearValidationErrors() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearValidationErrors()
	return _u
}

// SetExecutionResult sets the "execution_result" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetExecutionResult(v map[string]interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetExecutionResult(v)
	return _u
}

// ClearExecutionResult clears the value of the "execution_result" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearExecutionResult() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearExecutionResult()
	return _u
}

// SetPerformanceMetrics sets the "performance_metrics" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetPerformanceMetrics(v map[string]interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetPerformanceMetrics(v)
	return _u
}

// ClearPerformanceMetrics clears the value of the "performance_metrics" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearPerformanceMetrics() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearPerformanceMetrics()
	return _u
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetConfigSnapshot(v map[string]interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetConfigSnapshot(v)
	return _u
}

// ClearConfigSnapshot clears the value of the "config_snapshot" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearConfigSnapshot() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearConfigSnapshot()
	return _u
}

// SetProviderInfo sets the "provider_info" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetProviderInfo(v map[string]interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetProviderInfo(v)
	return _u
}

// ClearProviderInfo clears the value of the "provider_info" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearProviderInfo() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearProviderInfo()
	return _u
}

// SetExecutionLog sets the "execution_log" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetExecutionLog(v string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetExecutionLog(v)
	return _u
}

// SetNillableExecutionLog sets the "execution_log" field if the given value is not nil.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetNillableExecutionLog(v *string) *DiscoveryExecutionHistoryUpdateOne {
	if v != nil {
		_u.SetExecutionLog(*v)
	}
	return _u
}

// ClearExecutionLog clears the value of the "execution_log" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearExecutionLog() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearExecutionLog()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetMetadata(v map[string]interface{}) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearMetadata() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetTags sets the "tags" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetTags(v []string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) AppendTags(v []string) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearTags() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetDiscoveryConfig sets the "discovery_config" edge to the CiTypeDiscoveryConfig entity.
func (_u *DiscoveryExecutionHistoryUpdateOne) SetDiscoveryConfig(v *CiTypeDiscoveryConfig) *DiscoveryExecutionHistoryUpdateOne {
	return _u.SetDiscoveryConfigID(v.ID)
}

// Mutation returns the DiscoveryExecutionHistoryMutation object of the builder.
func (_u *DiscoveryExecutionHistoryUpdateOne) Mutation() *DiscoveryExecutionHistoryMutation {
	return _u.mutation
}

// ClearDiscoveryConfig clears the "discovery_config" edge to the CiTypeDiscoveryConfig entity.
func (_u *DiscoveryExecutionHistoryUpdateOne) ClearDiscoveryConfig() *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.ClearDiscoveryConfig()
	return _u
}

// Where appends a list predicates to the DiscoveryExecutionHistoryUpdate builder.
func (_u *DiscoveryExecutionHistoryUpdateOne) Where(ps ...predicate.DiscoveryExecutionHistory) *DiscoveryExecutionHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiscoveryExecutionHistoryUpdateOne) Select(field string, fields ...string) *DiscoveryExecutionHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiscoveryExecutionHistory entity.
func (_u *DiscoveryExecutionHistoryUpdateOne) Save(ctx context.Context) (*DiscoveryExecutionHistory, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscoveryExecutionHistoryUpdateOne) SaveX(ctx context.Context) *DiscoveryExecutionHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiscoveryExecutionHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscoveryExecutionHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DiscoveryExecutionHistoryUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if discoveryexecutionhistory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized discoveryexecutionhistory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := discoveryexecutionhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscoveryExecutionHistoryUpdateOne) check() error {
	if _u.mutation.DiscoveryConfigCleared() && len(_u.mutation.DiscoveryConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiscoveryExecutionHistory.discovery_config"`)
	}
	return nil
}

func (_u *DiscoveryExecutionHistoryUpdateOne) sqlSave(ctx context.Context) (_node *DiscoveryExecutionHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discoveryexecutionhistory.Table, discoveryexecutionhistory.Columns, sqlgraph.NewFieldSpec(discoveryexecutionhistory.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscoveryExecutionHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discoveryexecutionhistory.FieldID)
		for _, f := range fields {
			if !discoveryexecutionhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discoveryexecutionhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTriggeredBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTriggeredBy(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldTriggeredBy, field.TypeUint64, value)
	}
	if _u.mutation.TriggeredByCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldTriggeredBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.DurationSecondsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldDurationSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.ExecStatus(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldStage, field.TypeString, value)
	}
	if _u.mutation.StageCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldStage, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTotalRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldTotalRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProcessedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProcessedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProcessedRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldProcessedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldSuccessRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldSuccessRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FailedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldFailedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFailedRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldFailedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SkippedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldSkippedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSkippedRecords(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldSkippedRecords, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedCis(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldCreatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedCis(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldCreatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedCis(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldUpdatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedCis(); ok {
		_spec.AddField(discoveryexecutionhistory.FieldUpdatedCis, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorDetails(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldErrorDetails, field.TypeJSON, value)
	}
	if _u.mutation.ErrorDetailsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldErrorDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.ValidationErrors(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldValidationErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValidationErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, discoveryexecutionhistory.FieldValidationErrors, value)
		})
	}
	if _u.mutation.ValidationErrorsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldValidationErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExecutionResult(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionResult, field.TypeJSON, value)
	}
	if _u.mutation.ExecutionResultCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldExecutionResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.PerformanceMetrics(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldPerformanceMetrics, field.TypeJSON, value)
	}
	if _u.mutation.PerformanceMetricsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldPerformanceMetrics, field.TypeJSON)
	}
	if value, ok := _u.mutation.ConfigSnapshot(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldConfigSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ConfigSnapshotCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldConfigSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProviderInfo(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProviderInfo, field.TypeJSON, value)
	}
	if _u.mutation.ProviderInfoCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldProviderInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExecutionLog(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionLog, field.TypeString, value)
	}
	if _u.mutation.ExecutionLogCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldExecutionLog, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, discoveryexecutionhistory.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(discoveryexecutionhistory.FieldTags, field.TypeJSON)
	}
	if _u.mutation.DiscoveryConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discoveryexecutionhistory.DiscoveryConfigTable,
			Columns: []string{discoveryexecutionhistory.DiscoveryConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypediscoveryconfig.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiscoveryConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discoveryexecutionhistory.DiscoveryConfigTable,
			Columns: []string{discoveryexecutionhistory.DiscoveryConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypediscoveryconfig.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DiscoveryExecutionHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discoveryexecutionhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
