// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/citypediscoveryconfig"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/discoveryexecutionhistory"
)

// DiscoveryExecutionHistoryCreate is the builder for creating a DiscoveryExecutionHistory entity.
type DiscoveryExecutionHistoryCreate struct {
	config
	mutation *DiscoveryExecutionHistoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DiscoveryExecutionHistoryCreate) SetCreatedAt(v time.Time) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableCreatedAt(v *time.Time) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DiscoveryExecutionHistoryCreate) SetUpdatedAt(v time.Time) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableUpdatedAt(v *time.Time) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DiscoveryExecutionHistoryCreate) SetDeletedAt(v time.Time) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableDeletedAt(v *time.Time) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *DiscoveryExecutionHistoryCreate) SetTenantID(v uint64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableTenantID(v *uint64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetDiscoveryConfigID sets the "discovery_config_id" field.
func (_c *DiscoveryExecutionHistoryCreate) SetDiscoveryConfigID(v uint64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetDiscoveryConfigID(v)
	return _c
}

// SetExecutionID sets the "execution_id" field.
func (_c *DiscoveryExecutionHistoryCreate) SetExecutionID(v string) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetTriggerType sets the "trigger_type" field.
func (_c *DiscoveryExecutionHistoryCreate) SetTriggerType(v string) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetTriggerType(v)
	return _c
}

// SetTriggeredBy sets the "triggered_by" field.
func (_c *DiscoveryExecutionHistoryCreate) SetTriggeredBy(v uint64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetTriggeredBy(v)
	return _c
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableTriggeredBy(v *uint64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetTriggeredBy(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *DiscoveryExecutionHistoryCreate) SetStartedAt(v time.Time) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *DiscoveryExecutionHistoryCreate) SetCompletedAt(v time.Time) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableCompletedAt(v *time.Time) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *DiscoveryExecutionHistoryCreate) SetDurationSeconds(v int) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableDurationSeconds(v *int) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetDurationSeconds(*v)
	}
	return _c
}

// SetExecStatus sets the "exec_status" field.
func (_c *DiscoveryExecutionHistoryCreate) SetExecStatus(v string) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetExecStatus(v)
	return _c
}

// SetStage sets the "stage" field.
func (_c *DiscoveryExecutionHistoryCreate) SetStage(v string) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableStage(v *string) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetStage(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *DiscoveryExecutionHistoryCreate) SetProgress(v int) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableProgress(v *int) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetTotalRecords sets the "total_records" field.
func (_c *DiscoveryExecutionHistoryCreate) SetTotalRecords(v int64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetTotalRecords(v)
	return _c
}

// SetNillableTotalRecords sets the "total_records" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableTotalRecords(v *int64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetTotalRecords(*v)
	}
	return _c
}

// SetProcessedRecords sets the "processed_records" field.
func (_c *DiscoveryExecutionHistoryCreate) SetProcessedRecords(v int64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetProcessedRecords(v)
	return _c
}

// SetNillableProcessedRecords sets the "processed_records" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableProcessedRecords(v *int64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetProcessedRecords(*v)
	}
	return _c
}

// SetSuccessRecords sets the "success_records" field.
func (_c *DiscoveryExecutionHistoryCreate) SetSuccessRecords(v int64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetSuccessRecords(v)
	return _c
}

// SetNillableSuccessRecords sets the "success_records" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableSuccessRecords(v *int64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetSuccessRecords(*v)
	}
	return _c
}

// SetFailedRecords sets the "failed_records" field.
func (_c *DiscoveryExecutionHistoryCreate) SetFailedRecords(v int64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetFailedRecords(v)
	return _c
}

// SetNillableFailedRecords sets the "failed_records" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableFailedRecords(v *int64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetFailedRecords(*v)
	}
	return _c
}

// SetSkippedRecords sets the "skipped_records" field.
func (_c *DiscoveryExecutionHistoryCreate) SetSkippedRecords(v int64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetSkippedRecords(v)
	return _c
}

// SetNillableSkippedRecords sets the "skipped_records" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableSkippedRecords(v *int64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetSkippedRecords(*v)
	}
	return _c
}

// SetCreatedCis sets the "created_cis" field.
func (_c *DiscoveryExecutionHistoryCreate) SetCreatedCis(v int64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetCreatedCis(v)
	return _c
}

// SetNillableCreatedCis sets the "created_cis" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableCreatedCis(v *int64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetCreatedCis(*v)
	}
	return _c
}

// SetUpdatedCis sets the "updated_cis" field.
func (_c *DiscoveryExecutionHistoryCreate) SetUpdatedCis(v int64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetUpdatedCis(v)
	return _c
}

// SetNillableUpdatedCis sets the "updated_cis" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableUpdatedCis(v *int64) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetUpdatedCis(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *DiscoveryExecutionHistoryCreate) SetErrorMessage(v string) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableErrorMessage(v *string) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetErrorDetails sets the "error_details" field.
func (_c *DiscoveryExecutionHistoryCreate) SetErrorDetails(v map[string]interface{}) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetErrorDetails(v)
	return _c
}

// SetValidationErrors sets the "validation_errors" field.
func (_c *DiscoveryExecutionHistoryCreate) SetValidationErrors(v []interface{}) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetValidationErrors(v)
	return _c
}

// SetExecutionResult sets the "execution_result" field.
func (_c *DiscoveryExecutionHistoryCreate) SetExecutionResult(v map[string]interface{}) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetExecutionResult(v)
	return _c
}

// SetPerformanceMetrics sets the "performance_metrics" field.
func (_c *DiscoveryExecutionHistoryCreate) SetPerformanceMetrics(v map[string]interface{}) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetPerformanceMetrics(v)
	return _c
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_c *DiscoveryExecutionHistoryCreate) SetConfigSnapshot(v map[string]interface{}) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetConfigSnapshot(v)
	return _c
}

// SetProviderInfo sets the "provider_info" field.
func (_c *DiscoveryExecutionHistoryCreate) SetProviderInfo(v map[string]interface{}) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetProviderInfo(v)
	return _c
}

// SetExecutionLog sets the "execution_log" field.
func (_c *DiscoveryExecutionHistoryCreate) SetExecutionLog(v string) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetExecutionLog(v)
	return _c
}

// SetNillableExecutionLog sets the "execution_log" field if the given value is not nil.
func (_c *DiscoveryExecutionHistoryCreate) SetNillableExecutionLog(v *string) *DiscoveryExecutionHistoryCreate {
	if v != nil {
		_c.SetExecutionLog(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *DiscoveryExecutionHistoryCreate) SetMetadata(v map[string]interface{}) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *DiscoveryExecutionHistoryCreate) SetTags(v []string) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DiscoveryExecutionHistoryCreate) SetID(v uint64) *DiscoveryExecutionHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDiscoveryConfig sets the "discovery_config" edge to the CiTypeDiscoveryConfig entity.
func (_c *DiscoveryExecutionHistoryCreate) SetDiscoveryConfig(v *CiTypeDiscoveryConfig) *DiscoveryExecutionHistoryCreate {
	return _c.SetDiscoveryConfigID(v.ID)
}

// Mutation returns the DiscoveryExecutionHistoryMutation object of the builder.
func (_c *DiscoveryExecutionHistoryCreate) Mutation() *DiscoveryExecutionHistoryMutation {
	return _c.mutation
}

// Save creates the DiscoveryExecutionHistory in the database.
func (_c *DiscoveryExecutionHistoryCreate) Save(ctx context.Context) (*DiscoveryExecutionHistory, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscoveryExecutionHistoryCreate) SaveX(ctx context.Context) *DiscoveryExecutionHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscoveryExecutionHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscoveryExecutionHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiscoveryExecutionHistoryCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if discoveryexecutionhistory.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized discoveryexecutionhistory.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := discoveryexecutionhistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if discoveryexecutionhistory.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized discoveryexecutionhistory.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := discoveryexecutionhistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := discoveryexecutionhistory.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := discoveryexecutionhistory.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.TotalRecords(); !ok {
		v := discoveryexecutionhistory.DefaultTotalRecords
		_c.mutation.SetTotalRecords(v)
	}
	if _, ok := _c.mutation.ProcessedRecords(); !ok {
		v := discoveryexecutionhistory.DefaultProcessedRecords
		_c.mutation.SetProcessedRecords(v)
	}
	if _, ok := _c.mutation.SuccessRecords(); !ok {
		v := discoveryexecutionhistory.DefaultSuccessRecords
		_c.mutation.SetSuccessRecords(v)
	}
	if _, ok := _c.mutation.FailedRecords(); !ok {
		v := discoveryexecutionhistory.DefaultFailedRecords
		_c.mutation.SetFailedRecords(v)
	}
	if _, ok := _c.mutation.SkippedRecords(); !ok {
		v := discoveryexecutionhistory.DefaultSkippedRecords
		_c.mutation.SetSkippedRecords(v)
	}
	if _, ok := _c.mutation.CreatedCis(); !ok {
		v := discoveryexecutionhistory.DefaultCreatedCis
		_c.mutation.SetCreatedCis(v)
	}
	if _, ok := _c.mutation.UpdatedCis(); !ok {
		v := discoveryexecutionhistory.DefaultUpdatedCis
		_c.mutation.SetUpdatedCis(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscoveryExecutionHistoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.tenant_id"`)}
	}
	if _, ok := _c.mutation.DiscoveryConfigID(); !ok {
		return &ValidationError{Name: "discovery_config_id", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.discovery_config_id"`)}
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.execution_id"`)}
	}
	if _, ok := _c.mutation.TriggerType(); !ok {
		return &ValidationError{Name: "trigger_type", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.trigger_type"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.started_at"`)}
	}
	if _, ok := _c.mutation.ExecStatus(); !ok {
		return &ValidationError{Name: "exec_status", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.exec_status"`)}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.progress"`)}
	}
	if _, ok := _c.mutation.TotalRecords(); !ok {
		return &ValidationError{Name: "total_records", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.total_records"`)}
	}
	if _, ok := _c.mutation.ProcessedRecords(); !ok {
		return &ValidationError{Name: "processed_records", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.processed_records"`)}
	}
	if _, ok := _c.mutation.SuccessRecords(); !ok {
		return &ValidationError{Name: "success_records", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.success_records"`)}
	}
	if _, ok := _c.mutation.FailedRecords(); !ok {
		return &ValidationError{Name: "failed_records", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.failed_records"`)}
	}
	if _, ok := _c.mutation.SkippedRecords(); !ok {
		return &ValidationError{Name: "skipped_records", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.skipped_records"`)}
	}
	if _, ok := _c.mutation.CreatedCis(); !ok {
		return &ValidationError{Name: "created_cis", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.created_cis"`)}
	}
	if _, ok := _c.mutation.UpdatedCis(); !ok {
		return &ValidationError{Name: "updated_cis", err: errors.New(`ent: missing required field "DiscoveryExecutionHistory.updated_cis"`)}
	}
	if len(_c.mutation.DiscoveryConfigIDs()) == 0 {
		return &ValidationError{Name: "discovery_config", err: errors.New(`ent: missing required edge "DiscoveryExecutionHistory.discovery_config"`)}
	}
	return nil
}

func (_c *DiscoveryExecutionHistoryCreate) sqlSave(ctx context.Context) (*DiscoveryExecutionHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscoveryExecutionHistoryCreate) createSpec() (*DiscoveryExecutionHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscoveryExecutionHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discoveryexecutionhistory.Table, sqlgraph.NewFieldSpec(discoveryexecutionhistory.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.ExecutionID(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionID, field.TypeString, value)
		_node.ExecutionID = value
	}
	if value, ok := _c.mutation.TriggerType(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTriggerType, field.TypeString, value)
		_node.TriggerType = value
	}
	if value, ok := _c.mutation.TriggeredBy(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTriggeredBy, field.TypeUint64, value)
		_node.TriggeredBy = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldDurationSeconds, field.TypeInt, value)
		_node.DurationSeconds = value
	}
	if value, ok := _c.mutation.ExecStatus(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecStatus, field.TypeString, value)
		_node.ExecStatus = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProgress, field.TypeInt, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.TotalRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTotalRecords, field.TypeInt64, value)
		_node.TotalRecords = value
	}
	if value, ok := _c.mutation.ProcessedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProcessedRecords, field.TypeInt64, value)
		_node.ProcessedRecords = value
	}
	if value, ok := _c.mutation.SuccessRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldSuccessRecords, field.TypeInt64, value)
		_node.SuccessRecords = value
	}
	if value, ok := _c.mutation.FailedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldFailedRecords, field.TypeInt64, value)
		_node.FailedRecords = value
	}
	if value, ok := _c.mutation.SkippedRecords(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldSkippedRecords, field.TypeInt64, value)
		_node.SkippedRecords = value
	}
	if value, ok := _c.mutation.CreatedCis(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldCreatedCis, field.TypeInt64, value)
		_node.CreatedCis = value
	}
	if value, ok := _c.mutation.UpdatedCis(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldUpdatedCis, field.TypeInt64, value)
		_node.UpdatedCis = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.ErrorDetails(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldErrorDetails, field.TypeJSON, value)
		_node.ErrorDetails = value
	}
	if value, ok := _c.mutation.ValidationErrors(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldValidationErrors, field.TypeJSON, value)
		_node.ValidationErrors = value
	}
	if value, ok := _c.mutation.ExecutionResult(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionResult, field.TypeJSON, value)
		_node.ExecutionResult = value
	}
	if value, ok := _c.mutation.PerformanceMetrics(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldPerformanceMetrics, field.TypeJSON, value)
		_node.PerformanceMetrics = value
	}
	if value, ok := _c.mutation.ConfigSnapshot(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldConfigSnapshot, field.TypeJSON, value)
		_node.ConfigSnapshot = value
	}
	if value, ok := _c.mutation.ProviderInfo(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldProviderInfo, field.TypeJSON, value)
		_node.ProviderInfo = value
	}
	if value, ok := _c.mutation.ExecutionLog(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldExecutionLog, field.TypeString, value)
		_node.ExecutionLog = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(discoveryexecutionhistory.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if nodes := _c.mutation.DiscoveryConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   discoveryexecutionhistory.DiscoveryConfigTable,
			Columns: []string{discoveryexecutionhistory.DiscoveryConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(citypediscoveryconfig.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DiscoveryConfigID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiscoveryExecutionHistoryCreateBulk is the builder for creating many DiscoveryExecutionHistory entities in bulk.
type DiscoveryExecutionHistoryCreateBulk struct {
	config
	err      error
	builders []*DiscoveryExecutionHistoryCreate
}

// Save creates the DiscoveryExecutionHistory entities in the database.
func (_c *DiscoveryExecutionHistoryCreateBulk) Save(ctx context.Context) ([]*DiscoveryExecutionHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscoveryExecutionHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscoveryExecutionHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscoveryExecutionHistoryCreateBulk) SaveX(ctx context.Context) []*DiscoveryExecutionHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscoveryExecutionHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscoveryExecutionHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
