// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/link234/cmdb-rpc/ent/citype"
	"gitee.com/link234/cmdb-rpc/ent/importtask"
	"gitee.com/link234/cmdb-rpc/ent/importtemplate"
	"gitee.com/link234/cmdb-rpc/ent/predicate"
)

// ImportTemplateQuery is the builder for querying ImportTemplate entities.
type ImportTemplateQuery struct {
	config
	ctx        *QueryContext
	order      []importtemplate.OrderOption
	inters     []Interceptor
	predicates []predicate.ImportTemplate
	withCiType *CiTypeQuery
	withTasks  *ImportTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ImportTemplateQuery builder.
func (itq *ImportTemplateQuery) Where(ps ...predicate.ImportTemplate) *ImportTemplateQuery {
	itq.predicates = append(itq.predicates, ps...)
	return itq
}

// Limit the number of records to be returned by this query.
func (itq *ImportTemplateQuery) Limit(limit int) *ImportTemplateQuery {
	itq.ctx.Limit = &limit
	return itq
}

// Offset to start from.
func (itq *ImportTemplateQuery) Offset(offset int) *ImportTemplateQuery {
	itq.ctx.Offset = &offset
	return itq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (itq *ImportTemplateQuery) Unique(unique bool) *ImportTemplateQuery {
	itq.ctx.Unique = &unique
	return itq
}

// Order specifies how the records should be ordered.
func (itq *ImportTemplateQuery) Order(o ...importtemplate.OrderOption) *ImportTemplateQuery {
	itq.order = append(itq.order, o...)
	return itq
}

// QueryCiType chains the current query on the "ci_type" edge.
func (itq *ImportTemplateQuery) QueryCiType() *CiTypeQuery {
	query := (&CiTypeClient{config: itq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := itq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(importtemplate.Table, importtemplate.FieldID, selector),
			sqlgraph.To(citype.Table, citype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, importtemplate.CiTypeTable, importtemplate.CiTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(itq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTasks chains the current query on the "tasks" edge.
func (itq *ImportTemplateQuery) QueryTasks() *ImportTaskQuery {
	query := (&ImportTaskClient{config: itq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := itq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(importtemplate.Table, importtemplate.FieldID, selector),
			sqlgraph.To(importtask.Table, importtask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, importtemplate.TasksTable, importtemplate.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(itq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ImportTemplate entity from the query.
// Returns a *NotFoundError when no ImportTemplate was found.
func (itq *ImportTemplateQuery) First(ctx context.Context) (*ImportTemplate, error) {
	nodes, err := itq.Limit(1).All(setContextOp(ctx, itq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{importtemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (itq *ImportTemplateQuery) FirstX(ctx context.Context) *ImportTemplate {
	node, err := itq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ImportTemplate ID from the query.
// Returns a *NotFoundError when no ImportTemplate ID was found.
func (itq *ImportTemplateQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = itq.Limit(1).IDs(setContextOp(ctx, itq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{importtemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (itq *ImportTemplateQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := itq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ImportTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ImportTemplate entity is found.
// Returns a *NotFoundError when no ImportTemplate entities are found.
func (itq *ImportTemplateQuery) Only(ctx context.Context) (*ImportTemplate, error) {
	nodes, err := itq.Limit(2).All(setContextOp(ctx, itq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{importtemplate.Label}
	default:
		return nil, &NotSingularError{importtemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (itq *ImportTemplateQuery) OnlyX(ctx context.Context) *ImportTemplate {
	node, err := itq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ImportTemplate ID in the query.
// Returns a *NotSingularError when more than one ImportTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (itq *ImportTemplateQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = itq.Limit(2).IDs(setContextOp(ctx, itq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{importtemplate.Label}
	default:
		err = &NotSingularError{importtemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (itq *ImportTemplateQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := itq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ImportTemplates.
func (itq *ImportTemplateQuery) All(ctx context.Context) ([]*ImportTemplate, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryAll)
	if err := itq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ImportTemplate, *ImportTemplateQuery]()
	return withInterceptors[[]*ImportTemplate](ctx, itq, qr, itq.inters)
}

// AllX is like All, but panics if an error occurs.
func (itq *ImportTemplateQuery) AllX(ctx context.Context) []*ImportTemplate {
	nodes, err := itq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ImportTemplate IDs.
func (itq *ImportTemplateQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if itq.ctx.Unique == nil && itq.path != nil {
		itq.Unique(true)
	}
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryIDs)
	if err = itq.Select(importtemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (itq *ImportTemplateQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := itq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (itq *ImportTemplateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryCount)
	if err := itq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, itq, querierCount[*ImportTemplateQuery](), itq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (itq *ImportTemplateQuery) CountX(ctx context.Context) int {
	count, err := itq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (itq *ImportTemplateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryExist)
	switch _, err := itq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (itq *ImportTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := itq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ImportTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (itq *ImportTemplateQuery) Clone() *ImportTemplateQuery {
	if itq == nil {
		return nil
	}
	return &ImportTemplateQuery{
		config:     itq.config,
		ctx:        itq.ctx.Clone(),
		order:      append([]importtemplate.OrderOption{}, itq.order...),
		inters:     append([]Interceptor{}, itq.inters...),
		predicates: append([]predicate.ImportTemplate{}, itq.predicates...),
		withCiType: itq.withCiType.Clone(),
		withTasks:  itq.withTasks.Clone(),
		// clone intermediate query.
		sql:  itq.sql.Clone(),
		path: itq.path,
	}
}

// WithCiType tells the query-builder to eager-load the nodes that are connected to
// the "ci_type" edge. The optional arguments are used to configure the query builder of the edge.
func (itq *ImportTemplateQuery) WithCiType(opts ...func(*CiTypeQuery)) *ImportTemplateQuery {
	query := (&CiTypeClient{config: itq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	itq.withCiType = query
	return itq
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (itq *ImportTemplateQuery) WithTasks(opts ...func(*ImportTaskQuery)) *ImportTemplateQuery {
	query := (&ImportTaskClient{config: itq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	itq.withTasks = query
	return itq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ImportTemplate.Query().
//		GroupBy(importtemplate.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (itq *ImportTemplateQuery) GroupBy(field string, fields ...string) *ImportTemplateGroupBy {
	itq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ImportTemplateGroupBy{build: itq}
	grbuild.flds = &itq.ctx.Fields
	grbuild.label = importtemplate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ImportTemplate.Query().
//		Select(importtemplate.FieldCreatedAt).
//		Scan(ctx, &v)
func (itq *ImportTemplateQuery) Select(fields ...string) *ImportTemplateSelect {
	itq.ctx.Fields = append(itq.ctx.Fields, fields...)
	sbuild := &ImportTemplateSelect{ImportTemplateQuery: itq}
	sbuild.label = importtemplate.Label
	sbuild.flds, sbuild.scan = &itq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ImportTemplateSelect configured with the given aggregations.
func (itq *ImportTemplateQuery) Aggregate(fns ...AggregateFunc) *ImportTemplateSelect {
	return itq.Select().Aggregate(fns...)
}

func (itq *ImportTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range itq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, itq); err != nil {
				return err
			}
		}
	}
	for _, f := range itq.ctx.Fields {
		if !importtemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if itq.path != nil {
		prev, err := itq.path(ctx)
		if err != nil {
			return err
		}
		itq.sql = prev
	}
	return nil
}

func (itq *ImportTemplateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ImportTemplate, error) {
	var (
		nodes       = []*ImportTemplate{}
		_spec       = itq.querySpec()
		loadedTypes = [2]bool{
			itq.withCiType != nil,
			itq.withTasks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ImportTemplate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ImportTemplate{config: itq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, itq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := itq.withCiType; query != nil {
		if err := itq.loadCiType(ctx, query, nodes, nil,
			func(n *ImportTemplate, e *CiType) { n.Edges.CiType = e }); err != nil {
			return nil, err
		}
	}
	if query := itq.withTasks; query != nil {
		if err := itq.loadTasks(ctx, query, nodes,
			func(n *ImportTemplate) { n.Edges.Tasks = []*ImportTask{} },
			func(n *ImportTemplate, e *ImportTask) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (itq *ImportTemplateQuery) loadCiType(ctx context.Context, query *CiTypeQuery, nodes []*ImportTemplate, init func(*ImportTemplate), assign func(*ImportTemplate, *CiType)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*ImportTemplate)
	for i := range nodes {
		fk := nodes[i].CiTypeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(citype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ci_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (itq *ImportTemplateQuery) loadTasks(ctx context.Context, query *ImportTaskQuery, nodes []*ImportTemplate, init func(*ImportTemplate), assign func(*ImportTemplate, *ImportTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*ImportTemplate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(importtask.FieldTemplateID)
	}
	query.Where(predicate.ImportTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(importtemplate.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TemplateID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "template_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (itq *ImportTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := itq.querySpec()
	_spec.Node.Columns = itq.ctx.Fields
	if len(itq.ctx.Fields) > 0 {
		_spec.Unique = itq.ctx.Unique != nil && *itq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, itq.driver, _spec)
}

func (itq *ImportTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(importtemplate.Table, importtemplate.Columns, sqlgraph.NewFieldSpec(importtemplate.FieldID, field.TypeUint64))
	_spec.From = itq.sql
	if unique := itq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if itq.path != nil {
		_spec.Unique = true
	}
	if fields := itq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, importtemplate.FieldID)
		for i := range fields {
			if fields[i] != importtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if itq.withCiType != nil {
			_spec.Node.AddColumnOnce(importtemplate.FieldCiTypeID)
		}
	}
	if ps := itq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := itq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := itq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := itq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (itq *ImportTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(itq.driver.Dialect())
	t1 := builder.Table(importtemplate.Table)
	columns := itq.ctx.Fields
	if len(columns) == 0 {
		columns = importtemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if itq.sql != nil {
		selector = itq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if itq.ctx.Unique != nil && *itq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range itq.predicates {
		p(selector)
	}
	for _, p := range itq.order {
		p(selector)
	}
	if offset := itq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := itq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ImportTemplateGroupBy is the group-by builder for ImportTemplate entities.
type ImportTemplateGroupBy struct {
	selector
	build *ImportTemplateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (itgb *ImportTemplateGroupBy) Aggregate(fns ...AggregateFunc) *ImportTemplateGroupBy {
	itgb.fns = append(itgb.fns, fns...)
	return itgb
}

// Scan applies the selector query and scans the result into the given value.
func (itgb *ImportTemplateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, itgb.build.ctx, ent.OpQueryGroupBy)
	if err := itgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImportTemplateQuery, *ImportTemplateGroupBy](ctx, itgb.build, itgb, itgb.build.inters, v)
}

func (itgb *ImportTemplateGroupBy) sqlScan(ctx context.Context, root *ImportTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(itgb.fns))
	for _, fn := range itgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*itgb.flds)+len(itgb.fns))
		for _, f := range *itgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*itgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := itgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ImportTemplateSelect is the builder for selecting fields of ImportTemplate entities.
type ImportTemplateSelect struct {
	*ImportTemplateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (its *ImportTemplateSelect) Aggregate(fns ...AggregateFunc) *ImportTemplateSelect {
	its.fns = append(its.fns, fns...)
	return its
}

// Scan applies the selector query and scans the result into the given value.
func (its *ImportTemplateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, its.ctx, ent.OpQuerySelect)
	if err := its.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ImportTemplateQuery, *ImportTemplateSelect](ctx, its.ImportTemplateQuery, its, its.inters, v)
}

func (its *ImportTemplateSelect) sqlScan(ctx context.Context, root *ImportTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(its.fns))
	for _, fn := range its.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*its.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := its.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
