// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/permissionfieldmask"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
)

// PermissionFieldMaskDelete is the builder for deleting a PermissionFieldMask entity.
type PermissionFieldMaskDelete struct {
	config
	hooks    []Hook
	mutation *PermissionFieldMaskMutation
}

// Where appends a list predicates to the PermissionFieldMaskDelete builder.
func (_d *PermissionFieldMaskDelete) Where(ps ...predicate.PermissionFieldMask) *PermissionFieldMaskDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PermissionFieldMaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionFieldMaskDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PermissionFieldMaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(permissionfieldmask.Table, sqlgraph.NewFieldSpec(permissionfieldmask.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PermissionFieldMaskDeleteOne is the builder for deleting a single PermissionFieldMask entity.
type PermissionFieldMaskDeleteOne struct {
	_d *PermissionFieldMaskDelete
}

// Where appends a list predicates to the PermissionFieldMaskDelete builder.
func (_d *PermissionFieldMaskDeleteOne) Where(ps ...predicate.PermissionFieldMask) *PermissionFieldMaskDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PermissionFieldMaskDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{permissionfieldmask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionFieldMaskDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
