// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/cipermission"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/permissionoperation"
)

// PermissionOperation is the model entity for the PermissionOperation schema.
type PermissionOperation struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Department ID | 部门 ID
	DepartmentID uint64 `json:"department_id,omitempty"`
	// 权限ID
	PermissionID uint64 `json:"permission_id,omitempty"`
	// 操作代码：read/write/delete/approve等
	OperationCode string `json:"operation_code,omitempty"`
	// 操作名称
	OperationName string `json:"operation_name,omitempty"`
	// 是否允许
	IsAllowed bool `json:"is_allowed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PermissionOperationQuery when eager-loading is set.
	Edges        PermissionOperationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PermissionOperationEdges holds the relations/edges for other nodes in the graph.
type PermissionOperationEdges struct {
	// Permission holds the value of the permission edge.
	Permission *CiPermission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PermissionOperationEdges) PermissionOrErr() (*CiPermission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: cipermission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PermissionOperation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case permissionoperation.FieldIsAllowed:
			values[i] = new(sql.NullBool)
		case permissionoperation.FieldID, permissionoperation.FieldTenantID, permissionoperation.FieldDepartmentID, permissionoperation.FieldPermissionID:
			values[i] = new(sql.NullInt64)
		case permissionoperation.FieldOperationCode, permissionoperation.FieldOperationName:
			values[i] = new(sql.NullString)
		case permissionoperation.FieldCreatedAt, permissionoperation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PermissionOperation fields.
func (_m *PermissionOperation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case permissionoperation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case permissionoperation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case permissionoperation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case permissionoperation.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case permissionoperation.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = uint64(value.Int64)
			}
		case permissionoperation.FieldPermissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = uint64(value.Int64)
			}
		case permissionoperation.FieldOperationCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_code", values[i])
			} else if value.Valid {
				_m.OperationCode = value.String
			}
		case permissionoperation.FieldOperationName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_name", values[i])
			} else if value.Valid {
				_m.OperationName = value.String
			}
		case permissionoperation.FieldIsAllowed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_allowed", values[i])
			} else if value.Valid {
				_m.IsAllowed = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PermissionOperation.
// This includes values selected through modifiers, order, etc.
func (_m *PermissionOperation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPermission queries the "permission" edge of the PermissionOperation entity.
func (_m *PermissionOperation) QueryPermission() *CiPermissionQuery {
	return NewPermissionOperationClient(_m.config).QueryPermission(_m)
}

// Update returns a builder for updating this PermissionOperation.
// Note that you need to call PermissionOperation.Unwrap() before calling this method if this PermissionOperation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PermissionOperation) Update() *PermissionOperationUpdateOne {
	return NewPermissionOperationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PermissionOperation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PermissionOperation) Unwrap() *PermissionOperation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PermissionOperation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PermissionOperation) String() string {
	var builder strings.Builder
	builder.WriteString("PermissionOperation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteString(", ")
	builder.WriteString("operation_code=")
	builder.WriteString(_m.OperationCode)
	builder.WriteString(", ")
	builder.WriteString("operation_name=")
	builder.WriteString(_m.OperationName)
	builder.WriteString(", ")
	builder.WriteString("is_allowed=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAllowed))
	builder.WriteByte(')')
	return builder.String()
}

// PermissionOperations is a parsable slice of PermissionOperation.
type PermissionOperations []*PermissionOperation
