// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitee.com/link234/cmdb-rpc/ent/relationtype"
)

// RelationType is the model entity for the RelationType schema.
type RelationType struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Delete Time | 删除日期
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// 关系类型名称
	Name string `json:"name,omitempty"`
	// 关系类型编码
	Code string `json:"code,omitempty"`
	// Category holds the value of the "category" field.
	Category relationtype.Category `json:"category,omitempty"`
	// Direction holds the value of the "direction" field.
	Direction relationtype.Direction `json:"direction,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelationTypeQuery when eager-loading is set.
	Edges        RelationTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelationTypeEdges holds the relations/edges for other nodes in the graph.
type RelationTypeEdges struct {
	// CiRelations holds the value of the ci_relations edge.
	CiRelations []*CiRelation `json:"ci_relations,omitempty"`
	// CiTypeRelations holds the value of the ci_type_relations edge.
	CiTypeRelations []*CiTypeRelation `json:"ci_type_relations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CiRelationsOrErr returns the CiRelations value or an error if the edge
// was not loaded in eager-loading.
func (e RelationTypeEdges) CiRelationsOrErr() ([]*CiRelation, error) {
	if e.loadedTypes[0] {
		return e.CiRelations, nil
	}
	return nil, &NotLoadedError{edge: "ci_relations"}
}

// CiTypeRelationsOrErr returns the CiTypeRelations value or an error if the edge
// was not loaded in eager-loading.
func (e RelationTypeEdges) CiTypeRelationsOrErr() ([]*CiTypeRelation, error) {
	if e.loadedTypes[1] {
		return e.CiTypeRelations, nil
	}
	return nil, &NotLoadedError{edge: "ci_type_relations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelationType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationtype.FieldID:
			values[i] = new(sql.NullInt64)
		case relationtype.FieldName, relationtype.FieldCode, relationtype.FieldCategory, relationtype.FieldDirection:
			values[i] = new(sql.NullString)
		case relationtype.FieldCreatedAt, relationtype.FieldUpdatedAt, relationtype.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelationType fields.
func (rt *RelationType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationtype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rt.ID = uint64(value.Int64)
		case relationtype.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rt.CreatedAt = value.Time
			}
		case relationtype.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rt.UpdatedAt = value.Time
			}
		case relationtype.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				rt.DeletedAt = value.Time
			}
		case relationtype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				rt.Name = value.String
			}
		case relationtype.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				rt.Code = value.String
			}
		case relationtype.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				rt.Category = relationtype.Category(value.String)
			}
		case relationtype.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				rt.Direction = relationtype.Direction(value.String)
			}
		default:
			rt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelationType.
// This includes values selected through modifiers, order, etc.
func (rt *RelationType) Value(name string) (ent.Value, error) {
	return rt.selectValues.Get(name)
}

// QueryCiRelations queries the "ci_relations" edge of the RelationType entity.
func (rt *RelationType) QueryCiRelations() *CiRelationQuery {
	return NewRelationTypeClient(rt.config).QueryCiRelations(rt)
}

// QueryCiTypeRelations queries the "ci_type_relations" edge of the RelationType entity.
func (rt *RelationType) QueryCiTypeRelations() *CiTypeRelationQuery {
	return NewRelationTypeClient(rt.config).QueryCiTypeRelations(rt)
}

// Update returns a builder for updating this RelationType.
// Note that you need to call RelationType.Unwrap() before calling this method if this RelationType
// was returned from a transaction, and the transaction was committed or rolled back.
func (rt *RelationType) Update() *RelationTypeUpdateOne {
	return NewRelationTypeClient(rt.config).UpdateOne(rt)
}

// Unwrap unwraps the RelationType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rt *RelationType) Unwrap() *RelationType {
	_tx, ok := rt.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelationType is not a transactional entity")
	}
	rt.config.driver = _tx.drv
	return rt
}

// String implements the fmt.Stringer.
func (rt *RelationType) String() string {
	var builder strings.Builder
	builder.WriteString("RelationType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rt.ID))
	builder.WriteString("created_at=")
	builder.WriteString(rt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rt.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(rt.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(rt.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(rt.Code)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", rt.Category))
	builder.WriteString(", ")
	builder.WriteString("direction=")
	builder.WriteString(fmt.Sprintf("%v", rt.Direction))
	builder.WriteByte(')')
	return builder.String()
}

// RelationTypes is a parsable slice of RelationType.
type RelationTypes []*RelationType
