// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/useractivityfact"
)

// UserActivityFactUpdate is the builder for updating UserActivityFact entities.
type UserActivityFactUpdate struct {
	config
	hooks    []Hook
	mutation *UserActivityFactMutation
}

// Where appends a list predicates to the UserActivityFactUpdate builder.
func (_u *UserActivityFactUpdate) Where(ps ...predicate.UserActivityFact) *UserActivityFactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserActivityFactUpdate) SetUpdatedAt(v time.Time) *UserActivityFactUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *UserActivityFactUpdate) SetDepartmentID(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableDepartmentID(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *UserActivityFactUpdate) AddDepartmentID(v int64) *UserActivityFactUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *UserActivityFactUpdate) ClearDepartmentID() *UserActivityFactUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserActivityFactUpdate) SetUserID(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableUserID(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserActivityFactUpdate) AddUserID(v int64) *UserActivityFactUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserActivityFactUpdate) SetUsername(v string) *UserActivityFactUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableUsername(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetUserRoles sets the "user_roles" field.
func (_u *UserActivityFactUpdate) SetUserRoles(v []string) *UserActivityFactUpdate {
	_u.mutation.SetUserRoles(v)
	return _u
}

// AppendUserRoles appends value to the "user_roles" field.
func (_u *UserActivityFactUpdate) AppendUserRoles(v []string) *UserActivityFactUpdate {
	_u.mutation.AppendUserRoles(v)
	return _u
}

// ClearUserRoles clears the value of the "user_roles" field.
func (_u *UserActivityFactUpdate) ClearUserRoles() *UserActivityFactUpdate {
	_u.mutation.ClearUserRoles()
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *UserActivityFactUpdate) SetOperationType(v useractivityfact.OperationType) *UserActivityFactUpdate {
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableOperationType(v *useractivityfact.OperationType) *UserActivityFactUpdate {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *UserActivityFactUpdate) SetResourceType(v string) *UserActivityFactUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableResourceType(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UserActivityFactUpdate) SetResourceID(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableResourceID(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *UserActivityFactUpdate) AddResourceID(v int64) *UserActivityFactUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *UserActivityFactUpdate) ClearResourceID() *UserActivityFactUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetCiTypeID sets the "ci_type_id" field.
func (_u *UserActivityFactUpdate) SetCiTypeID(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetCiTypeID()
	_u.mutation.SetCiTypeID(v)
	return _u
}

// SetNillableCiTypeID sets the "ci_type_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableCiTypeID(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetCiTypeID(*v)
	}
	return _u
}

// AddCiTypeID adds value to the "ci_type_id" field.
func (_u *UserActivityFactUpdate) AddCiTypeID(v int64) *UserActivityFactUpdate {
	_u.mutation.AddCiTypeID(v)
	return _u
}

// ClearCiTypeID clears the value of the "ci_type_id" field.
func (_u *UserActivityFactUpdate) ClearCiTypeID() *UserActivityFactUpdate {
	_u.mutation.ClearCiTypeID()
	return _u
}

// SetOperationDetails sets the "operation_details" field.
func (_u *UserActivityFactUpdate) SetOperationDetails(v map[string]interface{}) *UserActivityFactUpdate {
	_u.mutation.SetOperationDetails(v)
	return _u
}

// ClearOperationDetails clears the value of the "operation_details" field.
func (_u *UserActivityFactUpdate) ClearOperationDetails() *UserActivityFactUpdate {
	_u.mutation.ClearOperationDetails()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserActivityFactUpdate) SetStatus(v useractivityfact.Status) *UserActivityFactUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableStatus(v *useractivityfact.Status) *UserActivityFactUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UserActivityFactUpdate) SetErrorMessage(v string) *UserActivityFactUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableErrorMessage(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UserActivityFactUpdate) ClearErrorMessage() *UserActivityFactUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_u *UserActivityFactUpdate) SetResponseTimeMs(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetResponseTimeMs()
	_u.mutation.SetResponseTimeMs(v)
	return _u
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableResponseTimeMs(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetResponseTimeMs(*v)
	}
	return _u
}

// AddResponseTimeMs adds value to the "response_time_ms" field.
func (_u *UserActivityFactUpdate) AddResponseTimeMs(v int64) *UserActivityFactUpdate {
	_u.mutation.AddResponseTimeMs(v)
	return _u
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (_u *UserActivityFactUpdate) ClearResponseTimeMs() *UserActivityFactUpdate {
	_u.mutation.ClearResponseTimeMs()
	return _u
}

// SetAffectedRecords sets the "affected_records" field.
func (_u *UserActivityFactUpdate) SetAffectedRecords(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetAffectedRecords()
	_u.mutation.SetAffectedRecords(v)
	return _u
}

// SetNillableAffectedRecords sets the "affected_records" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableAffectedRecords(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetAffectedRecords(*v)
	}
	return _u
}

// AddAffectedRecords adds value to the "affected_records" field.
func (_u *UserActivityFactUpdate) AddAffectedRecords(v int64) *UserActivityFactUpdate {
	_u.mutation.AddAffectedRecords(v)
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *UserActivityFactUpdate) SetIPAddress(v string) *UserActivityFactUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableIPAddress(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *UserActivityFactUpdate) ClearIPAddress() *UserActivityFactUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *UserActivityFactUpdate) SetUserAgent(v string) *UserActivityFactUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableUserAgent(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *UserActivityFactUpdate) ClearUserAgent() *UserActivityFactUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *UserActivityFactUpdate) SetSessionID(v string) *UserActivityFactUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableSessionID(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *UserActivityFactUpdate) ClearSessionID() *UserActivityFactUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *UserActivityFactUpdate) SetAPIPath(v string) *UserActivityFactUpdate {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableAPIPath(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// ClearAPIPath clears the value of the "api_path" field.
func (_u *UserActivityFactUpdate) ClearAPIPath() *UserActivityFactUpdate {
	_u.mutation.ClearAPIPath()
	return _u
}

// SetHTTPMethod sets the "http_method" field.
func (_u *UserActivityFactUpdate) SetHTTPMethod(v useractivityfact.HTTPMethod) *UserActivityFactUpdate {
	_u.mutation.SetHTTPMethod(v)
	return _u
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableHTTPMethod(v *useractivityfact.HTTPMethod) *UserActivityFactUpdate {
	if v != nil {
		_u.SetHTTPMethod(*v)
	}
	return _u
}

// ClearHTTPMethod clears the value of the "http_method" field.
func (_u *UserActivityFactUpdate) ClearHTTPMethod() *UserActivityFactUpdate {
	_u.mutation.ClearHTTPMethod()
	return _u
}

// SetBeforeSnapshot sets the "before_snapshot" field.
func (_u *UserActivityFactUpdate) SetBeforeSnapshot(v map[string]interface{}) *UserActivityFactUpdate {
	_u.mutation.SetBeforeSnapshot(v)
	return _u
}

// ClearBeforeSnapshot clears the value of the "before_snapshot" field.
func (_u *UserActivityFactUpdate) ClearBeforeSnapshot() *UserActivityFactUpdate {
	_u.mutation.ClearBeforeSnapshot()
	return _u
}

// SetAfterSnapshot sets the "after_snapshot" field.
func (_u *UserActivityFactUpdate) SetAfterSnapshot(v map[string]interface{}) *UserActivityFactUpdate {
	_u.mutation.SetAfterSnapshot(v)
	return _u
}

// ClearAfterSnapshot clears the value of the "after_snapshot" field.
func (_u *UserActivityFactUpdate) ClearAfterSnapshot() *UserActivityFactUpdate {
	_u.mutation.ClearAfterSnapshot()
	return _u
}

// SetOperationTime sets the "operation_time" field.
func (_u *UserActivityFactUpdate) SetOperationTime(v time.Time) *UserActivityFactUpdate {
	_u.mutation.SetOperationTime(v)
	return _u
}

// SetNillableOperationTime sets the "operation_time" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableOperationTime(v *time.Time) *UserActivityFactUpdate {
	if v != nil {
		_u.SetOperationTime(*v)
	}
	return _u
}

// SetTimeDimensionID sets the "time_dimension_id" field.
func (_u *UserActivityFactUpdate) SetTimeDimensionID(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetTimeDimensionID()
	_u.mutation.SetTimeDimensionID(v)
	return _u
}

// SetNillableTimeDimensionID sets the "time_dimension_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableTimeDimensionID(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetTimeDimensionID(*v)
	}
	return _u
}

// AddTimeDimensionID adds value to the "time_dimension_id" field.
func (_u *UserActivityFactUpdate) AddTimeDimensionID(v int64) *UserActivityFactUpdate {
	_u.mutation.AddTimeDimensionID(v)
	return _u
}

// ClearTimeDimensionID clears the value of the "time_dimension_id" field.
func (_u *UserActivityFactUpdate) ClearTimeDimensionID() *UserActivityFactUpdate {
	_u.mutation.ClearTimeDimensionID()
	return _u
}

// SetBusinessTags sets the "business_tags" field.
func (_u *UserActivityFactUpdate) SetBusinessTags(v []string) *UserActivityFactUpdate {
	_u.mutation.SetBusinessTags(v)
	return _u
}

// AppendBusinessTags appends value to the "business_tags" field.
func (_u *UserActivityFactUpdate) AppendBusinessTags(v []string) *UserActivityFactUpdate {
	_u.mutation.AppendBusinessTags(v)
	return _u
}

// ClearBusinessTags clears the value of the "business_tags" field.
func (_u *UserActivityFactUpdate) ClearBusinessTags() *UserActivityFactUpdate {
	_u.mutation.ClearBusinessTags()
	return _u
}

// SetRiskLevel sets the "risk_level" field.
func (_u *UserActivityFactUpdate) SetRiskLevel(v useractivityfact.RiskLevel) *UserActivityFactUpdate {
	_u.mutation.SetRiskLevel(v)
	return _u
}

// SetNillableRiskLevel sets the "risk_level" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableRiskLevel(v *useractivityfact.RiskLevel) *UserActivityFactUpdate {
	if v != nil {
		_u.SetRiskLevel(*v)
	}
	return _u
}

// SetComplianceFlags sets the "compliance_flags" field.
func (_u *UserActivityFactUpdate) SetComplianceFlags(v []string) *UserActivityFactUpdate {
	_u.mutation.SetComplianceFlags(v)
	return _u
}

// AppendComplianceFlags appends value to the "compliance_flags" field.
func (_u *UserActivityFactUpdate) AppendComplianceFlags(v []string) *UserActivityFactUpdate {
	_u.mutation.AppendComplianceFlags(v)
	return _u
}

// ClearComplianceFlags clears the value of the "compliance_flags" field.
func (_u *UserActivityFactUpdate) ClearComplianceFlags() *UserActivityFactUpdate {
	_u.mutation.ClearComplianceFlags()
	return _u
}

// SetOperationSource sets the "operation_source" field.
func (_u *UserActivityFactUpdate) SetOperationSource(v useractivityfact.OperationSource) *UserActivityFactUpdate {
	_u.mutation.SetOperationSource(v)
	return _u
}

// SetNillableOperationSource sets the "operation_source" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableOperationSource(v *useractivityfact.OperationSource) *UserActivityFactUpdate {
	if v != nil {
		_u.SetOperationSource(*v)
	}
	return _u
}

// SetGeoLocation sets the "geo_location" field.
func (_u *UserActivityFactUpdate) SetGeoLocation(v map[string]interface{}) *UserActivityFactUpdate {
	_u.mutation.SetGeoLocation(v)
	return _u
}

// ClearGeoLocation clears the value of the "geo_location" field.
func (_u *UserActivityFactUpdate) ClearGeoLocation() *UserActivityFactUpdate {
	_u.mutation.ClearGeoLocation()
	return _u
}

// SetDeviceInfo sets the "device_info" field.
func (_u *UserActivityFactUpdate) SetDeviceInfo(v map[string]interface{}) *UserActivityFactUpdate {
	_u.mutation.SetDeviceInfo(v)
	return _u
}

// ClearDeviceInfo clears the value of the "device_info" field.
func (_u *UserActivityFactUpdate) ClearDeviceInfo() *UserActivityFactUpdate {
	_u.mutation.ClearDeviceInfo()
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *UserActivityFactUpdate) SetBatchID(v string) *UserActivityFactUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableBatchID(v *string) *UserActivityFactUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// ClearBatchID clears the value of the "batch_id" field.
func (_u *UserActivityFactUpdate) ClearBatchID() *UserActivityFactUpdate {
	_u.mutation.ClearBatchID()
	return _u
}

// SetParentOperationID sets the "parent_operation_id" field.
func (_u *UserActivityFactUpdate) SetParentOperationID(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetParentOperationID()
	_u.mutation.SetParentOperationID(v)
	return _u
}

// SetNillableParentOperationID sets the "parent_operation_id" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableParentOperationID(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetParentOperationID(*v)
	}
	return _u
}

// AddParentOperationID adds value to the "parent_operation_id" field.
func (_u *UserActivityFactUpdate) AddParentOperationID(v int64) *UserActivityFactUpdate {
	_u.mutation.AddParentOperationID(v)
	return _u
}

// ClearParentOperationID clears the value of the "parent_operation_id" field.
func (_u *UserActivityFactUpdate) ClearParentOperationID() *UserActivityFactUpdate {
	_u.mutation.ClearParentOperationID()
	return _u
}

// SetDataVersion sets the "data_version" field.
func (_u *UserActivityFactUpdate) SetDataVersion(v uint64) *UserActivityFactUpdate {
	_u.mutation.ResetDataVersion()
	_u.mutation.SetDataVersion(v)
	return _u
}

// SetNillableDataVersion sets the "data_version" field if the given value is not nil.
func (_u *UserActivityFactUpdate) SetNillableDataVersion(v *uint64) *UserActivityFactUpdate {
	if v != nil {
		_u.SetDataVersion(*v)
	}
	return _u
}

// AddDataVersion adds value to the "data_version" field.
func (_u *UserActivityFactUpdate) AddDataVersion(v int64) *UserActivityFactUpdate {
	_u.mutation.AddDataVersion(v)
	return _u
}

// Mutation returns the UserActivityFactMutation object of the builder.
func (_u *UserActivityFactUpdate) Mutation() *UserActivityFactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserActivityFactUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserActivityFactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserActivityFactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserActivityFactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserActivityFactUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useractivityfact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserActivityFactUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := useractivityfact.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationType(); ok {
		if err := useractivityfact.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.operation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := useractivityfact.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := useractivityfact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := useractivityfact.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.error_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := useractivityfact.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := useractivityfact.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := useractivityfact.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPath(); ok {
		if err := useractivityfact.APIPathValidator(v); err != nil {
			return &ValidationError{Name: "api_path", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.api_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTTPMethod(); ok {
		if err := useractivityfact.HTTPMethodValidator(v); err != nil {
			return &ValidationError{Name: "http_method", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.http_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskLevel(); ok {
		if err := useractivityfact.RiskLevelValidator(v); err != nil {
			return &ValidationError{Name: "risk_level", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.risk_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationSource(); ok {
		if err := useractivityfact.OperationSourceValidator(v); err != nil {
			return &ValidationError{Name: "operation_source", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.operation_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BatchID(); ok {
		if err := useractivityfact.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UserActivityFactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useractivityfact.Table, useractivityfact.Columns, sqlgraph.NewFieldSpec(useractivityfact.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useractivityfact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(useractivityfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(useractivityfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(useractivityfact.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useractivityfact.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useractivityfact.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(useractivityfact.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserRoles(); ok {
		_spec.SetField(useractivityfact.FieldUserRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUserRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, useractivityfact.FieldUserRoles, value)
		})
	}
	if _u.mutation.UserRolesCleared() {
		_spec.ClearField(useractivityfact.FieldUserRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(useractivityfact.FieldOperationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(useractivityfact.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(useractivityfact.FieldResourceID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(useractivityfact.FieldResourceID, field.TypeUint64, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(useractivityfact.FieldResourceID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CiTypeID(); ok {
		_spec.SetField(useractivityfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiTypeID(); ok {
		_spec.AddField(useractivityfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if _u.mutation.CiTypeIDCleared() {
		_spec.ClearField(useractivityfact.FieldCiTypeID, field.TypeUint64)
	}
	if value, ok := _u.mutation.OperationDetails(); ok {
		_spec.SetField(useractivityfact.FieldOperationDetails, field.TypeJSON, value)
	}
	if _u.mutation.OperationDetailsCleared() {
		_spec.ClearField(useractivityfact.FieldOperationDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(useractivityfact.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(useractivityfact.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(useractivityfact.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseTimeMs(); ok {
		_spec.SetField(useractivityfact.FieldResponseTimeMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedResponseTimeMs(); ok {
		_spec.AddField(useractivityfact.FieldResponseTimeMs, field.TypeUint64, value)
	}
	if _u.mutation.ResponseTimeMsCleared() {
		_spec.ClearField(useractivityfact.FieldResponseTimeMs, field.TypeUint64)
	}
	if value, ok := _u.mutation.AffectedRecords(); ok {
		_spec.SetField(useractivityfact.FieldAffectedRecords, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAffectedRecords(); ok {
		_spec.AddField(useractivityfact.FieldAffectedRecords, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(useractivityfact.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(useractivityfact.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(useractivityfact.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(useractivityfact.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(useractivityfact.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(useractivityfact.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(useractivityfact.FieldAPIPath, field.TypeString, value)
	}
	if _u.mutation.APIPathCleared() {
		_spec.ClearField(useractivityfact.FieldAPIPath, field.TypeString)
	}
	if value, ok := _u.mutation.HTTPMethod(); ok {
		_spec.SetField(useractivityfact.FieldHTTPMethod, field.TypeEnum, value)
	}
	if _u.mutation.HTTPMethodCleared() {
		_spec.ClearField(useractivityfact.FieldHTTPMethod, field.TypeEnum)
	}
	if value, ok := _u.mutation.BeforeSnapshot(); ok {
		_spec.SetField(useractivityfact.FieldBeforeSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.BeforeSnapshotCleared() {
		_spec.ClearField(useractivityfact.FieldBeforeSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.AfterSnapshot(); ok {
		_spec.SetField(useractivityfact.FieldAfterSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.AfterSnapshotCleared() {
		_spec.ClearField(useractivityfact.FieldAfterSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperationTime(); ok {
		_spec.SetField(useractivityfact.FieldOperationTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeDimensionID(); ok {
		_spec.SetField(useractivityfact.FieldTimeDimensionID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTimeDimensionID(); ok {
		_spec.AddField(useractivityfact.FieldTimeDimensionID, field.TypeUint64, value)
	}
	if _u.mutation.TimeDimensionIDCleared() {
		_spec.ClearField(useractivityfact.FieldTimeDimensionID, field.TypeUint64)
	}
	if value, ok := _u.mutation.BusinessTags(); ok {
		_spec.SetField(useractivityfact.FieldBusinessTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBusinessTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, useractivityfact.FieldBusinessTags, value)
		})
	}
	if _u.mutation.BusinessTagsCleared() {
		_spec.ClearField(useractivityfact.FieldBusinessTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.RiskLevel(); ok {
		_spec.SetField(useractivityfact.FieldRiskLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ComplianceFlags(); ok {
		_spec.SetField(useractivityfact.FieldComplianceFlags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedComplianceFlags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, useractivityfact.FieldComplianceFlags, value)
		})
	}
	if _u.mutation.ComplianceFlagsCleared() {
		_spec.ClearField(useractivityfact.FieldComplianceFlags, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperationSource(); ok {
		_spec.SetField(useractivityfact.FieldOperationSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GeoLocation(); ok {
		_spec.SetField(useractivityfact.FieldGeoLocation, field.TypeJSON, value)
	}
	if _u.mutation.GeoLocationCleared() {
		_spec.ClearField(useractivityfact.FieldGeoLocation, field.TypeJSON)
	}
	if value, ok := _u.mutation.DeviceInfo(); ok {
		_spec.SetField(useractivityfact.FieldDeviceInfo, field.TypeJSON, value)
	}
	if _u.mutation.DeviceInfoCleared() {
		_spec.ClearField(useractivityfact.FieldDeviceInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(useractivityfact.FieldBatchID, field.TypeString, value)
	}
	if _u.mutation.BatchIDCleared() {
		_spec.ClearField(useractivityfact.FieldBatchID, field.TypeString)
	}
	if value, ok := _u.mutation.ParentOperationID(); ok {
		_spec.SetField(useractivityfact.FieldParentOperationID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedParentOperationID(); ok {
		_spec.AddField(useractivityfact.FieldParentOperationID, field.TypeUint64, value)
	}
	if _u.mutation.ParentOperationIDCleared() {
		_spec.ClearField(useractivityfact.FieldParentOperationID, field.TypeUint64)
	}
	if value, ok := _u.mutation.DataVersion(); ok {
		_spec.SetField(useractivityfact.FieldDataVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDataVersion(); ok {
		_spec.AddField(useractivityfact.FieldDataVersion, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useractivityfact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserActivityFactUpdateOne is the builder for updating a single UserActivityFact entity.
type UserActivityFactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserActivityFactMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserActivityFactUpdateOne) SetUpdatedAt(v time.Time) *UserActivityFactUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *UserActivityFactUpdateOne) SetDepartmentID(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableDepartmentID(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *UserActivityFactUpdateOne) AddDepartmentID(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *UserActivityFactUpdateOne) ClearDepartmentID() *UserActivityFactUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserActivityFactUpdateOne) SetUserID(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableUserID(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserActivityFactUpdateOne) AddUserID(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserActivityFactUpdateOne) SetUsername(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableUsername(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetUserRoles sets the "user_roles" field.
func (_u *UserActivityFactUpdateOne) SetUserRoles(v []string) *UserActivityFactUpdateOne {
	_u.mutation.SetUserRoles(v)
	return _u
}

// AppendUserRoles appends value to the "user_roles" field.
func (_u *UserActivityFactUpdateOne) AppendUserRoles(v []string) *UserActivityFactUpdateOne {
	_u.mutation.AppendUserRoles(v)
	return _u
}

// ClearUserRoles clears the value of the "user_roles" field.
func (_u *UserActivityFactUpdateOne) ClearUserRoles() *UserActivityFactUpdateOne {
	_u.mutation.ClearUserRoles()
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *UserActivityFactUpdateOne) SetOperationType(v useractivityfact.OperationType) *UserActivityFactUpdateOne {
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableOperationType(v *useractivityfact.OperationType) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *UserActivityFactUpdateOne) SetResourceType(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableResourceType(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UserActivityFactUpdateOne) SetResourceID(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableResourceID(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *UserActivityFactUpdateOne) AddResourceID(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *UserActivityFactUpdateOne) ClearResourceID() *UserActivityFactUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetCiTypeID sets the "ci_type_id" field.
func (_u *UserActivityFactUpdateOne) SetCiTypeID(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetCiTypeID()
	_u.mutation.SetCiTypeID(v)
	return _u
}

// SetNillableCiTypeID sets the "ci_type_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableCiTypeID(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetCiTypeID(*v)
	}
	return _u
}

// AddCiTypeID adds value to the "ci_type_id" field.
func (_u *UserActivityFactUpdateOne) AddCiTypeID(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddCiTypeID(v)
	return _u
}

// ClearCiTypeID clears the value of the "ci_type_id" field.
func (_u *UserActivityFactUpdateOne) ClearCiTypeID() *UserActivityFactUpdateOne {
	_u.mutation.ClearCiTypeID()
	return _u
}

// SetOperationDetails sets the "operation_details" field.
func (_u *UserActivityFactUpdateOne) SetOperationDetails(v map[string]interface{}) *UserActivityFactUpdateOne {
	_u.mutation.SetOperationDetails(v)
	return _u
}

// ClearOperationDetails clears the value of the "operation_details" field.
func (_u *UserActivityFactUpdateOne) ClearOperationDetails() *UserActivityFactUpdateOne {
	_u.mutation.ClearOperationDetails()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserActivityFactUpdateOne) SetStatus(v useractivityfact.Status) *UserActivityFactUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableStatus(v *useractivityfact.Status) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UserActivityFactUpdateOne) SetErrorMessage(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableErrorMessage(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UserActivityFactUpdateOne) ClearErrorMessage() *UserActivityFactUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_u *UserActivityFactUpdateOne) SetResponseTimeMs(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetResponseTimeMs()
	_u.mutation.SetResponseTimeMs(v)
	return _u
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableResponseTimeMs(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetResponseTimeMs(*v)
	}
	return _u
}

// AddResponseTimeMs adds value to the "response_time_ms" field.
func (_u *UserActivityFactUpdateOne) AddResponseTimeMs(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddResponseTimeMs(v)
	return _u
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (_u *UserActivityFactUpdateOne) ClearResponseTimeMs() *UserActivityFactUpdateOne {
	_u.mutation.ClearResponseTimeMs()
	return _u
}

// SetAffectedRecords sets the "affected_records" field.
func (_u *UserActivityFactUpdateOne) SetAffectedRecords(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetAffectedRecords()
	_u.mutation.SetAffectedRecords(v)
	return _u
}

// SetNillableAffectedRecords sets the "affected_records" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableAffectedRecords(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetAffectedRecords(*v)
	}
	return _u
}

// AddAffectedRecords adds value to the "affected_records" field.
func (_u *UserActivityFactUpdateOne) AddAffectedRecords(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddAffectedRecords(v)
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *UserActivityFactUpdateOne) SetIPAddress(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableIPAddress(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *UserActivityFactUpdateOne) ClearIPAddress() *UserActivityFactUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *UserActivityFactUpdateOne) SetUserAgent(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableUserAgent(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *UserActivityFactUpdateOne) ClearUserAgent() *UserActivityFactUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *UserActivityFactUpdateOne) SetSessionID(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableSessionID(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *UserActivityFactUpdateOne) ClearSessionID() *UserActivityFactUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *UserActivityFactUpdateOne) SetAPIPath(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableAPIPath(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// ClearAPIPath clears the value of the "api_path" field.
func (_u *UserActivityFactUpdateOne) ClearAPIPath() *UserActivityFactUpdateOne {
	_u.mutation.ClearAPIPath()
	return _u
}

// SetHTTPMethod sets the "http_method" field.
func (_u *UserActivityFactUpdateOne) SetHTTPMethod(v useractivityfact.HTTPMethod) *UserActivityFactUpdateOne {
	_u.mutation.SetHTTPMethod(v)
	return _u
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableHTTPMethod(v *useractivityfact.HTTPMethod) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetHTTPMethod(*v)
	}
	return _u
}

// ClearHTTPMethod clears the value of the "http_method" field.
func (_u *UserActivityFactUpdateOne) ClearHTTPMethod() *UserActivityFactUpdateOne {
	_u.mutation.ClearHTTPMethod()
	return _u
}

// SetBeforeSnapshot sets the "before_snapshot" field.
func (_u *UserActivityFactUpdateOne) SetBeforeSnapshot(v map[string]interface{}) *UserActivityFactUpdateOne {
	_u.mutation.SetBeforeSnapshot(v)
	return _u
}

// ClearBeforeSnapshot clears the value of the "before_snapshot" field.
func (_u *UserActivityFactUpdateOne) ClearBeforeSnapshot() *UserActivityFactUpdateOne {
	_u.mutation.ClearBeforeSnapshot()
	return _u
}

// SetAfterSnapshot sets the "after_snapshot" field.
func (_u *UserActivityFactUpdateOne) SetAfterSnapshot(v map[string]interface{}) *UserActivityFactUpdateOne {
	_u.mutation.SetAfterSnapshot(v)
	return _u
}

// ClearAfterSnapshot clears the value of the "after_snapshot" field.
func (_u *UserActivityFactUpdateOne) ClearAfterSnapshot() *UserActivityFactUpdateOne {
	_u.mutation.ClearAfterSnapshot()
	return _u
}

// SetOperationTime sets the "operation_time" field.
func (_u *UserActivityFactUpdateOne) SetOperationTime(v time.Time) *UserActivityFactUpdateOne {
	_u.mutation.SetOperationTime(v)
	return _u
}

// SetNillableOperationTime sets the "operation_time" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableOperationTime(v *time.Time) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetOperationTime(*v)
	}
	return _u
}

// SetTimeDimensionID sets the "time_dimension_id" field.
func (_u *UserActivityFactUpdateOne) SetTimeDimensionID(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetTimeDimensionID()
	_u.mutation.SetTimeDimensionID(v)
	return _u
}

// SetNillableTimeDimensionID sets the "time_dimension_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableTimeDimensionID(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetTimeDimensionID(*v)
	}
	return _u
}

// AddTimeDimensionID adds value to the "time_dimension_id" field.
func (_u *UserActivityFactUpdateOne) AddTimeDimensionID(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddTimeDimensionID(v)
	return _u
}

// ClearTimeDimensionID clears the value of the "time_dimension_id" field.
func (_u *UserActivityFactUpdateOne) ClearTimeDimensionID() *UserActivityFactUpdateOne {
	_u.mutation.ClearTimeDimensionID()
	return _u
}

// SetBusinessTags sets the "business_tags" field.
func (_u *UserActivityFactUpdateOne) SetBusinessTags(v []string) *UserActivityFactUpdateOne {
	_u.mutation.SetBusinessTags(v)
	return _u
}

// AppendBusinessTags appends value to the "business_tags" field.
func (_u *UserActivityFactUpdateOne) AppendBusinessTags(v []string) *UserActivityFactUpdateOne {
	_u.mutation.AppendBusinessTags(v)
	return _u
}

// ClearBusinessTags clears the value of the "business_tags" field.
func (_u *UserActivityFactUpdateOne) ClearBusinessTags() *UserActivityFactUpdateOne {
	_u.mutation.ClearBusinessTags()
	return _u
}

// SetRiskLevel sets the "risk_level" field.
func (_u *UserActivityFactUpdateOne) SetRiskLevel(v useractivityfact.RiskLevel) *UserActivityFactUpdateOne {
	_u.mutation.SetRiskLevel(v)
	return _u
}

// SetNillableRiskLevel sets the "risk_level" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableRiskLevel(v *useractivityfact.RiskLevel) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetRiskLevel(*v)
	}
	return _u
}

// SetComplianceFlags sets the "compliance_flags" field.
func (_u *UserActivityFactUpdateOne) SetComplianceFlags(v []string) *UserActivityFactUpdateOne {
	_u.mutation.SetComplianceFlags(v)
	return _u
}

// AppendComplianceFlags appends value to the "compliance_flags" field.
func (_u *UserActivityFactUpdateOne) AppendComplianceFlags(v []string) *UserActivityFactUpdateOne {
	_u.mutation.AppendComplianceFlags(v)
	return _u
}

// ClearComplianceFlags clears the value of the "compliance_flags" field.
func (_u *UserActivityFactUpdateOne) ClearComplianceFlags() *UserActivityFactUpdateOne {
	_u.mutation.ClearComplianceFlags()
	return _u
}

// SetOperationSource sets the "operation_source" field.
func (_u *UserActivityFactUpdateOne) SetOperationSource(v useractivityfact.OperationSource) *UserActivityFactUpdateOne {
	_u.mutation.SetOperationSource(v)
	return _u
}

// SetNillableOperationSource sets the "operation_source" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableOperationSource(v *useractivityfact.OperationSource) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetOperationSource(*v)
	}
	return _u
}

// SetGeoLocation sets the "geo_location" field.
func (_u *UserActivityFactUpdateOne) SetGeoLocation(v map[string]interface{}) *UserActivityFactUpdateOne {
	_u.mutation.SetGeoLocation(v)
	return _u
}

// ClearGeoLocation clears the value of the "geo_location" field.
func (_u *UserActivityFactUpdateOne) ClearGeoLocation() *UserActivityFactUpdateOne {
	_u.mutation.ClearGeoLocation()
	return _u
}

// SetDeviceInfo sets the "device_info" field.
func (_u *UserActivityFactUpdateOne) SetDeviceInfo(v map[string]interface{}) *UserActivityFactUpdateOne {
	_u.mutation.SetDeviceInfo(v)
	return _u
}

// ClearDeviceInfo clears the value of the "device_info" field.
func (_u *UserActivityFactUpdateOne) ClearDeviceInfo() *UserActivityFactUpdateOne {
	_u.mutation.ClearDeviceInfo()
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *UserActivityFactUpdateOne) SetBatchID(v string) *UserActivityFactUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableBatchID(v *string) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// ClearBatchID clears the value of the "batch_id" field.
func (_u *UserActivityFactUpdateOne) ClearBatchID() *UserActivityFactUpdateOne {
	_u.mutation.ClearBatchID()
	return _u
}

// SetParentOperationID sets the "parent_operation_id" field.
func (_u *UserActivityFactUpdateOne) SetParentOperationID(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetParentOperationID()
	_u.mutation.SetParentOperationID(v)
	return _u
}

// SetNillableParentOperationID sets the "parent_operation_id" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableParentOperationID(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetParentOperationID(*v)
	}
	return _u
}

// AddParentOperationID adds value to the "parent_operation_id" field.
func (_u *UserActivityFactUpdateOne) AddParentOperationID(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddParentOperationID(v)
	return _u
}

// ClearParentOperationID clears the value of the "parent_operation_id" field.
func (_u *UserActivityFactUpdateOne) ClearParentOperationID() *UserActivityFactUpdateOne {
	_u.mutation.ClearParentOperationID()
	return _u
}

// SetDataVersion sets the "data_version" field.
func (_u *UserActivityFactUpdateOne) SetDataVersion(v uint64) *UserActivityFactUpdateOne {
	_u.mutation.ResetDataVersion()
	_u.mutation.SetDataVersion(v)
	return _u
}

// SetNillableDataVersion sets the "data_version" field if the given value is not nil.
func (_u *UserActivityFactUpdateOne) SetNillableDataVersion(v *uint64) *UserActivityFactUpdateOne {
	if v != nil {
		_u.SetDataVersion(*v)
	}
	return _u
}

// AddDataVersion adds value to the "data_version" field.
func (_u *UserActivityFactUpdateOne) AddDataVersion(v int64) *UserActivityFactUpdateOne {
	_u.mutation.AddDataVersion(v)
	return _u
}

// Mutation returns the UserActivityFactMutation object of the builder.
func (_u *UserActivityFactUpdateOne) Mutation() *UserActivityFactMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserActivityFactUpdate builder.
func (_u *UserActivityFactUpdateOne) Where(ps ...predicate.UserActivityFact) *UserActivityFactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserActivityFactUpdateOne) Select(field string, fields ...string) *UserActivityFactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserActivityFact entity.
func (_u *UserActivityFactUpdateOne) Save(ctx context.Context) (*UserActivityFact, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserActivityFactUpdateOne) SaveX(ctx context.Context) *UserActivityFact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserActivityFactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserActivityFactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserActivityFactUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useractivityfact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserActivityFactUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := useractivityfact.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationType(); ok {
		if err := useractivityfact.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.operation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := useractivityfact.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := useractivityfact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := useractivityfact.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.error_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := useractivityfact.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := useractivityfact.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := useractivityfact.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPath(); ok {
		if err := useractivityfact.APIPathValidator(v); err != nil {
			return &ValidationError{Name: "api_path", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.api_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTTPMethod(); ok {
		if err := useractivityfact.HTTPMethodValidator(v); err != nil {
			return &ValidationError{Name: "http_method", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.http_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskLevel(); ok {
		if err := useractivityfact.RiskLevelValidator(v); err != nil {
			return &ValidationError{Name: "risk_level", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.risk_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationSource(); ok {
		if err := useractivityfact.OperationSourceValidator(v); err != nil {
			return &ValidationError{Name: "operation_source", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.operation_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BatchID(); ok {
		if err := useractivityfact.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "UserActivityFact.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UserActivityFactUpdateOne) sqlSave(ctx context.Context) (_node *UserActivityFact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useractivityfact.Table, useractivityfact.Columns, sqlgraph.NewFieldSpec(useractivityfact.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserActivityFact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useractivityfact.FieldID)
		for _, f := range fields {
			if !useractivityfact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useractivityfact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useractivityfact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(useractivityfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(useractivityfact.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(useractivityfact.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useractivityfact.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useractivityfact.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(useractivityfact.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserRoles(); ok {
		_spec.SetField(useractivityfact.FieldUserRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUserRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, useractivityfact.FieldUserRoles, value)
		})
	}
	if _u.mutation.UserRolesCleared() {
		_spec.ClearField(useractivityfact.FieldUserRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(useractivityfact.FieldOperationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(useractivityfact.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(useractivityfact.FieldResourceID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(useractivityfact.FieldResourceID, field.TypeUint64, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(useractivityfact.FieldResourceID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CiTypeID(); ok {
		_spec.SetField(useractivityfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCiTypeID(); ok {
		_spec.AddField(useractivityfact.FieldCiTypeID, field.TypeUint64, value)
	}
	if _u.mutation.CiTypeIDCleared() {
		_spec.ClearField(useractivityfact.FieldCiTypeID, field.TypeUint64)
	}
	if value, ok := _u.mutation.OperationDetails(); ok {
		_spec.SetField(useractivityfact.FieldOperationDetails, field.TypeJSON, value)
	}
	if _u.mutation.OperationDetailsCleared() {
		_spec.ClearField(useractivityfact.FieldOperationDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(useractivityfact.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(useractivityfact.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(useractivityfact.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseTimeMs(); ok {
		_spec.SetField(useractivityfact.FieldResponseTimeMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedResponseTimeMs(); ok {
		_spec.AddField(useractivityfact.FieldResponseTimeMs, field.TypeUint64, value)
	}
	if _u.mutation.ResponseTimeMsCleared() {
		_spec.ClearField(useractivityfact.FieldResponseTimeMs, field.TypeUint64)
	}
	if value, ok := _u.mutation.AffectedRecords(); ok {
		_spec.SetField(useractivityfact.FieldAffectedRecords, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAffectedRecords(); ok {
		_spec.AddField(useractivityfact.FieldAffectedRecords, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(useractivityfact.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(useractivityfact.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(useractivityfact.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(useractivityfact.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(useractivityfact.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(useractivityfact.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(useractivityfact.FieldAPIPath, field.TypeString, value)
	}
	if _u.mutation.APIPathCleared() {
		_spec.ClearField(useractivityfact.FieldAPIPath, field.TypeString)
	}
	if value, ok := _u.mutation.HTTPMethod(); ok {
		_spec.SetField(useractivityfact.FieldHTTPMethod, field.TypeEnum, value)
	}
	if _u.mutation.HTTPMethodCleared() {
		_spec.ClearField(useractivityfact.FieldHTTPMethod, field.TypeEnum)
	}
	if value, ok := _u.mutation.BeforeSnapshot(); ok {
		_spec.SetField(useractivityfact.FieldBeforeSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.BeforeSnapshotCleared() {
		_spec.ClearField(useractivityfact.FieldBeforeSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.AfterSnapshot(); ok {
		_spec.SetField(useractivityfact.FieldAfterSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.AfterSnapshotCleared() {
		_spec.ClearField(useractivityfact.FieldAfterSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperationTime(); ok {
		_spec.SetField(useractivityfact.FieldOperationTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TimeDimensionID(); ok {
		_spec.SetField(useractivityfact.FieldTimeDimensionID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTimeDimensionID(); ok {
		_spec.AddField(useractivityfact.FieldTimeDimensionID, field.TypeUint64, value)
	}
	if _u.mutation.TimeDimensionIDCleared() {
		_spec.ClearField(useractivityfact.FieldTimeDimensionID, field.TypeUint64)
	}
	if value, ok := _u.mutation.BusinessTags(); ok {
		_spec.SetField(useractivityfact.FieldBusinessTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBusinessTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, useractivityfact.FieldBusinessTags, value)
		})
	}
	if _u.mutation.BusinessTagsCleared() {
		_spec.ClearField(useractivityfact.FieldBusinessTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.RiskLevel(); ok {
		_spec.SetField(useractivityfact.FieldRiskLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ComplianceFlags(); ok {
		_spec.SetField(useractivityfact.FieldComplianceFlags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedComplianceFlags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, useractivityfact.FieldComplianceFlags, value)
		})
	}
	if _u.mutation.ComplianceFlagsCleared() {
		_spec.ClearField(useractivityfact.FieldComplianceFlags, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperationSource(); ok {
		_spec.SetField(useractivityfact.FieldOperationSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GeoLocation(); ok {
		_spec.SetField(useractivityfact.FieldGeoLocation, field.TypeJSON, value)
	}
	if _u.mutation.GeoLocationCleared() {
		_spec.ClearField(useractivityfact.FieldGeoLocation, field.TypeJSON)
	}
	if value, ok := _u.mutation.DeviceInfo(); ok {
		_spec.SetField(useractivityfact.FieldDeviceInfo, field.TypeJSON, value)
	}
	if _u.mutation.DeviceInfoCleared() {
		_spec.ClearField(useractivityfact.FieldDeviceInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(useractivityfact.FieldBatchID, field.TypeString, value)
	}
	if _u.mutation.BatchIDCleared() {
		_spec.ClearField(useractivityfact.FieldBatchID, field.TypeString)
	}
	if value, ok := _u.mutation.ParentOperationID(); ok {
		_spec.SetField(useractivityfact.FieldParentOperationID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedParentOperationID(); ok {
		_spec.AddField(useractivityfact.FieldParentOperationID, field.TypeUint64, value)
	}
	if _u.mutation.ParentOperationIDCleared() {
		_spec.ClearField(useractivityfact.FieldParentOperationID, field.TypeUint64)
	}
	if value, ok := _u.mutation.DataVersion(); ok {
		_spec.SetField(useractivityfact.FieldDataVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDataVersion(); ok {
		_spec.AddField(useractivityfact.FieldDataVersion, field.TypeUint64, value)
	}
	_node = &UserActivityFact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useractivityfact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
