// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/link234/cmdb-rpc/ent/predicate"
	"gitee.com/link234/cmdb-rpc/ent/valueinteger"
)

// ValueIntegerDelete is the builder for deleting a ValueInteger entity.
type ValueIntegerDelete struct {
	config
	hooks    []Hook
	mutation *ValueIntegerMutation
}

// Where appends a list predicates to the ValueIntegerDelete builder.
func (vid *ValueIntegerDelete) Where(ps ...predicate.ValueInteger) *ValueIntegerDelete {
	vid.mutation.Where(ps...)
	return vid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vid *ValueIntegerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vid.sqlExec, vid.mutation, vid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vid *ValueIntegerDelete) ExecX(ctx context.Context) int {
	n, err := vid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vid *ValueIntegerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(valueinteger.Table, sqlgraph.NewFieldSpec(valueinteger.FieldID, field.TypeUint64))
	if ps := vid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vid.mutation.done = true
	return affected, err
}

// ValueIntegerDeleteOne is the builder for deleting a single ValueInteger entity.
type ValueIntegerDeleteOne struct {
	vid *ValueIntegerDelete
}

// Where appends a list predicates to the ValueIntegerDelete builder.
func (vido *ValueIntegerDeleteOne) Where(ps ...predicate.ValueInteger) *ValueIntegerDeleteOne {
	vido.vid.mutation.Where(ps...)
	return vido
}

// Exec executes the deletion query.
func (vido *ValueIntegerDeleteOne) Exec(ctx context.Context) error {
	n, err := vido.vid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{valueinteger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vido *ValueIntegerDeleteOne) ExecX(ctx context.Context) {
	if err := vido.Exec(ctx); err != nil {
		panic(err)
	}
}
