// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/link234/cmdb-rpc/ent/attribute"
	"gitee.com/link234/cmdb-rpc/ent/cis"
	"gitee.com/link234/cmdb-rpc/ent/predicate"
	"gitee.com/link234/cmdb-rpc/ent/valuefloat"
)

// ValueFloatQuery is the builder for querying ValueFloat entities.
type ValueFloatQuery struct {
	config
	ctx           *QueryContext
	order         []valuefloat.OrderOption
	inters        []Interceptor
	predicates    []predicate.ValueFloat
	withCi        *CisQuery
	withAttribute *AttributeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ValueFloatQuery builder.
func (vfq *ValueFloatQuery) Where(ps ...predicate.ValueFloat) *ValueFloatQuery {
	vfq.predicates = append(vfq.predicates, ps...)
	return vfq
}

// Limit the number of records to be returned by this query.
func (vfq *ValueFloatQuery) Limit(limit int) *ValueFloatQuery {
	vfq.ctx.Limit = &limit
	return vfq
}

// Offset to start from.
func (vfq *ValueFloatQuery) Offset(offset int) *ValueFloatQuery {
	vfq.ctx.Offset = &offset
	return vfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vfq *ValueFloatQuery) Unique(unique bool) *ValueFloatQuery {
	vfq.ctx.Unique = &unique
	return vfq
}

// Order specifies how the records should be ordered.
func (vfq *ValueFloatQuery) Order(o ...valuefloat.OrderOption) *ValueFloatQuery {
	vfq.order = append(vfq.order, o...)
	return vfq
}

// QueryCi chains the current query on the "ci" edge.
func (vfq *ValueFloatQuery) QueryCi() *CisQuery {
	query := (&CisClient{config: vfq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(valuefloat.Table, valuefloat.FieldID, selector),
			sqlgraph.To(cis.Table, cis.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, valuefloat.CiTable, valuefloat.CiColumn),
		)
		fromU = sqlgraph.SetNeighbors(vfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttribute chains the current query on the "attribute" edge.
func (vfq *ValueFloatQuery) QueryAttribute() *AttributeQuery {
	query := (&AttributeClient{config: vfq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(valuefloat.Table, valuefloat.FieldID, selector),
			sqlgraph.To(attribute.Table, attribute.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, valuefloat.AttributeTable, valuefloat.AttributeColumn),
		)
		fromU = sqlgraph.SetNeighbors(vfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ValueFloat entity from the query.
// Returns a *NotFoundError when no ValueFloat was found.
func (vfq *ValueFloatQuery) First(ctx context.Context) (*ValueFloat, error) {
	nodes, err := vfq.Limit(1).All(setContextOp(ctx, vfq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{valuefloat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vfq *ValueFloatQuery) FirstX(ctx context.Context) *ValueFloat {
	node, err := vfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ValueFloat ID from the query.
// Returns a *NotFoundError when no ValueFloat ID was found.
func (vfq *ValueFloatQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = vfq.Limit(1).IDs(setContextOp(ctx, vfq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{valuefloat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vfq *ValueFloatQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := vfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ValueFloat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ValueFloat entity is found.
// Returns a *NotFoundError when no ValueFloat entities are found.
func (vfq *ValueFloatQuery) Only(ctx context.Context) (*ValueFloat, error) {
	nodes, err := vfq.Limit(2).All(setContextOp(ctx, vfq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{valuefloat.Label}
	default:
		return nil, &NotSingularError{valuefloat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vfq *ValueFloatQuery) OnlyX(ctx context.Context) *ValueFloat {
	node, err := vfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ValueFloat ID in the query.
// Returns a *NotSingularError when more than one ValueFloat ID is found.
// Returns a *NotFoundError when no entities are found.
func (vfq *ValueFloatQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = vfq.Limit(2).IDs(setContextOp(ctx, vfq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{valuefloat.Label}
	default:
		err = &NotSingularError{valuefloat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vfq *ValueFloatQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := vfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ValueFloats.
func (vfq *ValueFloatQuery) All(ctx context.Context) ([]*ValueFloat, error) {
	ctx = setContextOp(ctx, vfq.ctx, ent.OpQueryAll)
	if err := vfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ValueFloat, *ValueFloatQuery]()
	return withInterceptors[[]*ValueFloat](ctx, vfq, qr, vfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vfq *ValueFloatQuery) AllX(ctx context.Context) []*ValueFloat {
	nodes, err := vfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ValueFloat IDs.
func (vfq *ValueFloatQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if vfq.ctx.Unique == nil && vfq.path != nil {
		vfq.Unique(true)
	}
	ctx = setContextOp(ctx, vfq.ctx, ent.OpQueryIDs)
	if err = vfq.Select(valuefloat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vfq *ValueFloatQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := vfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vfq *ValueFloatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vfq.ctx, ent.OpQueryCount)
	if err := vfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vfq, querierCount[*ValueFloatQuery](), vfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vfq *ValueFloatQuery) CountX(ctx context.Context) int {
	count, err := vfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vfq *ValueFloatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vfq.ctx, ent.OpQueryExist)
	switch _, err := vfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vfq *ValueFloatQuery) ExistX(ctx context.Context) bool {
	exist, err := vfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ValueFloatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vfq *ValueFloatQuery) Clone() *ValueFloatQuery {
	if vfq == nil {
		return nil
	}
	return &ValueFloatQuery{
		config:        vfq.config,
		ctx:           vfq.ctx.Clone(),
		order:         append([]valuefloat.OrderOption{}, vfq.order...),
		inters:        append([]Interceptor{}, vfq.inters...),
		predicates:    append([]predicate.ValueFloat{}, vfq.predicates...),
		withCi:        vfq.withCi.Clone(),
		withAttribute: vfq.withAttribute.Clone(),
		// clone intermediate query.
		sql:  vfq.sql.Clone(),
		path: vfq.path,
	}
}

// WithCi tells the query-builder to eager-load the nodes that are connected to
// the "ci" edge. The optional arguments are used to configure the query builder of the edge.
func (vfq *ValueFloatQuery) WithCi(opts ...func(*CisQuery)) *ValueFloatQuery {
	query := (&CisClient{config: vfq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vfq.withCi = query
	return vfq
}

// WithAttribute tells the query-builder to eager-load the nodes that are connected to
// the "attribute" edge. The optional arguments are used to configure the query builder of the edge.
func (vfq *ValueFloatQuery) WithAttribute(opts ...func(*AttributeQuery)) *ValueFloatQuery {
	query := (&AttributeClient{config: vfq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vfq.withAttribute = query
	return vfq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ValueFloat.Query().
//		GroupBy(valuefloat.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vfq *ValueFloatQuery) GroupBy(field string, fields ...string) *ValueFloatGroupBy {
	vfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ValueFloatGroupBy{build: vfq}
	grbuild.flds = &vfq.ctx.Fields
	grbuild.label = valuefloat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ValueFloat.Query().
//		Select(valuefloat.FieldCreatedAt).
//		Scan(ctx, &v)
func (vfq *ValueFloatQuery) Select(fields ...string) *ValueFloatSelect {
	vfq.ctx.Fields = append(vfq.ctx.Fields, fields...)
	sbuild := &ValueFloatSelect{ValueFloatQuery: vfq}
	sbuild.label = valuefloat.Label
	sbuild.flds, sbuild.scan = &vfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ValueFloatSelect configured with the given aggregations.
func (vfq *ValueFloatQuery) Aggregate(fns ...AggregateFunc) *ValueFloatSelect {
	return vfq.Select().Aggregate(fns...)
}

func (vfq *ValueFloatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vfq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vfq); err != nil {
				return err
			}
		}
	}
	for _, f := range vfq.ctx.Fields {
		if !valuefloat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vfq.path != nil {
		prev, err := vfq.path(ctx)
		if err != nil {
			return err
		}
		vfq.sql = prev
	}
	return nil
}

func (vfq *ValueFloatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ValueFloat, error) {
	var (
		nodes       = []*ValueFloat{}
		_spec       = vfq.querySpec()
		loadedTypes = [2]bool{
			vfq.withCi != nil,
			vfq.withAttribute != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ValueFloat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ValueFloat{config: vfq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vfq.withCi; query != nil {
		if err := vfq.loadCi(ctx, query, nodes, nil,
			func(n *ValueFloat, e *Cis) { n.Edges.Ci = e }); err != nil {
			return nil, err
		}
	}
	if query := vfq.withAttribute; query != nil {
		if err := vfq.loadAttribute(ctx, query, nodes, nil,
			func(n *ValueFloat, e *Attribute) { n.Edges.Attribute = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vfq *ValueFloatQuery) loadCi(ctx context.Context, query *CisQuery, nodes []*ValueFloat, init func(*ValueFloat), assign func(*ValueFloat, *Cis)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*ValueFloat)
	for i := range nodes {
		fk := nodes[i].CiID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cis.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ci_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (vfq *ValueFloatQuery) loadAttribute(ctx context.Context, query *AttributeQuery, nodes []*ValueFloat, init func(*ValueFloat), assign func(*ValueFloat, *Attribute)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*ValueFloat)
	for i := range nodes {
		fk := nodes[i].AttrID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(attribute.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "attr_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vfq *ValueFloatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vfq.querySpec()
	_spec.Node.Columns = vfq.ctx.Fields
	if len(vfq.ctx.Fields) > 0 {
		_spec.Unique = vfq.ctx.Unique != nil && *vfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vfq.driver, _spec)
}

func (vfq *ValueFloatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(valuefloat.Table, valuefloat.Columns, sqlgraph.NewFieldSpec(valuefloat.FieldID, field.TypeUint64))
	_spec.From = vfq.sql
	if unique := vfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vfq.path != nil {
		_spec.Unique = true
	}
	if fields := vfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, valuefloat.FieldID)
		for i := range fields {
			if fields[i] != valuefloat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if vfq.withCi != nil {
			_spec.Node.AddColumnOnce(valuefloat.FieldCiID)
		}
		if vfq.withAttribute != nil {
			_spec.Node.AddColumnOnce(valuefloat.FieldAttrID)
		}
	}
	if ps := vfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vfq *ValueFloatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vfq.driver.Dialect())
	t1 := builder.Table(valuefloat.Table)
	columns := vfq.ctx.Fields
	if len(columns) == 0 {
		columns = valuefloat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vfq.sql != nil {
		selector = vfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vfq.ctx.Unique != nil && *vfq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vfq.predicates {
		p(selector)
	}
	for _, p := range vfq.order {
		p(selector)
	}
	if offset := vfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ValueFloatGroupBy is the group-by builder for ValueFloat entities.
type ValueFloatGroupBy struct {
	selector
	build *ValueFloatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vfgb *ValueFloatGroupBy) Aggregate(fns ...AggregateFunc) *ValueFloatGroupBy {
	vfgb.fns = append(vfgb.fns, fns...)
	return vfgb
}

// Scan applies the selector query and scans the result into the given value.
func (vfgb *ValueFloatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vfgb.build.ctx, ent.OpQueryGroupBy)
	if err := vfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ValueFloatQuery, *ValueFloatGroupBy](ctx, vfgb.build, vfgb, vfgb.build.inters, v)
}

func (vfgb *ValueFloatGroupBy) sqlScan(ctx context.Context, root *ValueFloatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vfgb.fns))
	for _, fn := range vfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vfgb.flds)+len(vfgb.fns))
		for _, f := range *vfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ValueFloatSelect is the builder for selecting fields of ValueFloat entities.
type ValueFloatSelect struct {
	*ValueFloatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vfs *ValueFloatSelect) Aggregate(fns ...AggregateFunc) *ValueFloatSelect {
	vfs.fns = append(vfs.fns, fns...)
	return vfs
}

// Scan applies the selector query and scans the result into the given value.
func (vfs *ValueFloatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vfs.ctx, ent.OpQuerySelect)
	if err := vfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ValueFloatQuery, *ValueFloatSelect](ctx, vfs.ValueFloatQuery, vfs, vfs.inters, v)
}

func (vfs *ValueFloatSelect) sqlScan(ctx context.Context, root *ValueFloatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vfs.fns))
	for _, fn := range vfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
