// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/attribute"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/cis"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/predicate"
	"github.com/coder-lulu/newbee-cmdb-rpc/ent/valuejson"
)

// ValueJSONUpdate is the builder for updating ValueJSON entities.
type ValueJSONUpdate struct {
	config
	hooks    []Hook
	mutation *ValueJSONMutation
}

// Where appends a list predicates to the ValueJSONUpdate builder.
func (_u *ValueJSONUpdate) Where(ps ...predicate.ValueJSON) *ValueJSONUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ValueJSONUpdate) SetUpdatedAt(v time.Time) *ValueJSONUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ValueJSONUpdate) SetDeletedAt(v time.Time) *ValueJSONUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ValueJSONUpdate) SetNillableDeletedAt(v *time.Time) *ValueJSONUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ValueJSONUpdate) ClearDeletedAt() *ValueJSONUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCiID sets the "ci_id" field.
func (_u *ValueJSONUpdate) SetCiID(v uint64) *ValueJSONUpdate {
	_u.mutation.SetCiID(v)
	return _u
}

// SetNillableCiID sets the "ci_id" field if the given value is not nil.
func (_u *ValueJSONUpdate) SetNillableCiID(v *uint64) *ValueJSONUpdate {
	if v != nil {
		_u.SetCiID(*v)
	}
	return _u
}

// SetAttrID sets the "attr_id" field.
func (_u *ValueJSONUpdate) SetAttrID(v uint64) *ValueJSONUpdate {
	_u.mutation.SetAttrID(v)
	return _u
}

// SetNillableAttrID sets the "attr_id" field if the given value is not nil.
func (_u *ValueJSONUpdate) SetNillableAttrID(v *uint64) *ValueJSONUpdate {
	if v != nil {
		_u.SetAttrID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ValueJSONUpdate) SetValue(v json.RawMessage) *ValueJSONUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// AppendValue appends value to the "value" field.
func (_u *ValueJSONUpdate) AppendValue(v json.RawMessage) *ValueJSONUpdate {
	_u.mutation.AppendValue(v)
	return _u
}

// SetIsCover sets the "is_cover" field.
func (_u *ValueJSONUpdate) SetIsCover(v bool) *ValueJSONUpdate {
	_u.mutation.SetIsCover(v)
	return _u
}

// SetNillableIsCover sets the "is_cover" field if the given value is not nil.
func (_u *ValueJSONUpdate) SetNillableIsCover(v *bool) *ValueJSONUpdate {
	if v != nil {
		_u.SetIsCover(*v)
	}
	return _u
}

// SetCi sets the "ci" edge to the Cis entity.
func (_u *ValueJSONUpdate) SetCi(v *Cis) *ValueJSONUpdate {
	return _u.SetCiID(v.ID)
}

// SetAttributeID sets the "attribute" edge to the Attribute entity by ID.
func (_u *ValueJSONUpdate) SetAttributeID(id uint64) *ValueJSONUpdate {
	_u.mutation.SetAttributeID(id)
	return _u
}

// SetAttribute sets the "attribute" edge to the Attribute entity.
func (_u *ValueJSONUpdate) SetAttribute(v *Attribute) *ValueJSONUpdate {
	return _u.SetAttributeID(v.ID)
}

// Mutation returns the ValueJSONMutation object of the builder.
func (_u *ValueJSONUpdate) Mutation() *ValueJSONMutation {
	return _u.mutation
}

// ClearCi clears the "ci" edge to the Cis entity.
func (_u *ValueJSONUpdate) ClearCi() *ValueJSONUpdate {
	_u.mutation.ClearCi()
	return _u
}

// ClearAttribute clears the "attribute" edge to the Attribute entity.
func (_u *ValueJSONUpdate) ClearAttribute() *ValueJSONUpdate {
	_u.mutation.ClearAttribute()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ValueJSONUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValueJSONUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ValueJSONUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValueJSONUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ValueJSONUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if valuejson.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized valuejson.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := valuejson.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ValueJSONUpdate) check() error {
	if _u.mutation.CiCleared() && len(_u.mutation.CiIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ValueJSON.ci"`)
	}
	if _u.mutation.AttributeCleared() && len(_u.mutation.AttributeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ValueJSON.attribute"`)
	}
	return nil
}

func (_u *ValueJSONUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(valuejson.Table, valuejson.Columns, sqlgraph.NewFieldSpec(valuejson.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(valuejson.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(valuejson.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(valuejson.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(valuejson.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, valuejson.FieldValue, value)
		})
	}
	if value, ok := _u.mutation.IsCover(); ok {
		_spec.SetField(valuejson.FieldIsCover, field.TypeBool, value)
	}
	if _u.mutation.CiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.CiTable,
			Columns: []string{valuejson.CiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cis.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.CiTable,
			Columns: []string{valuejson.CiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cis.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.AttributeTable,
			Columns: []string{valuejson.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttributeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.AttributeTable,
			Columns: []string{valuejson.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuejson.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ValueJSONUpdateOne is the builder for updating a single ValueJSON entity.
type ValueJSONUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ValueJSONMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ValueJSONUpdateOne) SetUpdatedAt(v time.Time) *ValueJSONUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ValueJSONUpdateOne) SetDeletedAt(v time.Time) *ValueJSONUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ValueJSONUpdateOne) SetNillableDeletedAt(v *time.Time) *ValueJSONUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ValueJSONUpdateOne) ClearDeletedAt() *ValueJSONUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCiID sets the "ci_id" field.
func (_u *ValueJSONUpdateOne) SetCiID(v uint64) *ValueJSONUpdateOne {
	_u.mutation.SetCiID(v)
	return _u
}

// SetNillableCiID sets the "ci_id" field if the given value is not nil.
func (_u *ValueJSONUpdateOne) SetNillableCiID(v *uint64) *ValueJSONUpdateOne {
	if v != nil {
		_u.SetCiID(*v)
	}
	return _u
}

// SetAttrID sets the "attr_id" field.
func (_u *ValueJSONUpdateOne) SetAttrID(v uint64) *ValueJSONUpdateOne {
	_u.mutation.SetAttrID(v)
	return _u
}

// SetNillableAttrID sets the "attr_id" field if the given value is not nil.
func (_u *ValueJSONUpdateOne) SetNillableAttrID(v *uint64) *ValueJSONUpdateOne {
	if v != nil {
		_u.SetAttrID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ValueJSONUpdateOne) SetValue(v json.RawMessage) *ValueJSONUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// AppendValue appends value to the "value" field.
func (_u *ValueJSONUpdateOne) AppendValue(v json.RawMessage) *ValueJSONUpdateOne {
	_u.mutation.AppendValue(v)
	return _u
}

// SetIsCover sets the "is_cover" field.
func (_u *ValueJSONUpdateOne) SetIsCover(v bool) *ValueJSONUpdateOne {
	_u.mutation.SetIsCover(v)
	return _u
}

// SetNillableIsCover sets the "is_cover" field if the given value is not nil.
func (_u *ValueJSONUpdateOne) SetNillableIsCover(v *bool) *ValueJSONUpdateOne {
	if v != nil {
		_u.SetIsCover(*v)
	}
	return _u
}

// SetCi sets the "ci" edge to the Cis entity.
func (_u *ValueJSONUpdateOne) SetCi(v *Cis) *ValueJSONUpdateOne {
	return _u.SetCiID(v.ID)
}

// SetAttributeID sets the "attribute" edge to the Attribute entity by ID.
func (_u *ValueJSONUpdateOne) SetAttributeID(id uint64) *ValueJSONUpdateOne {
	_u.mutation.SetAttributeID(id)
	return _u
}

// SetAttribute sets the "attribute" edge to the Attribute entity.
func (_u *ValueJSONUpdateOne) SetAttribute(v *Attribute) *ValueJSONUpdateOne {
	return _u.SetAttributeID(v.ID)
}

// Mutation returns the ValueJSONMutation object of the builder.
func (_u *ValueJSONUpdateOne) Mutation() *ValueJSONMutation {
	return _u.mutation
}

// ClearCi clears the "ci" edge to the Cis entity.
func (_u *ValueJSONUpdateOne) ClearCi() *ValueJSONUpdateOne {
	_u.mutation.ClearCi()
	return _u
}

// ClearAttribute clears the "attribute" edge to the Attribute entity.
func (_u *ValueJSONUpdateOne) ClearAttribute() *ValueJSONUpdateOne {
	_u.mutation.ClearAttribute()
	return _u
}

// Where appends a list predicates to the ValueJSONUpdate builder.
func (_u *ValueJSONUpdateOne) Where(ps ...predicate.ValueJSON) *ValueJSONUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ValueJSONUpdateOne) Select(field string, fields ...string) *ValueJSONUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ValueJSON entity.
func (_u *ValueJSONUpdateOne) Save(ctx context.Context) (*ValueJSON, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValueJSONUpdateOne) SaveX(ctx context.Context) *ValueJSON {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ValueJSONUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValueJSONUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ValueJSONUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if valuejson.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized valuejson.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := valuejson.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ValueJSONUpdateOne) check() error {
	if _u.mutation.CiCleared() && len(_u.mutation.CiIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ValueJSON.ci"`)
	}
	if _u.mutation.AttributeCleared() && len(_u.mutation.AttributeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ValueJSON.attribute"`)
	}
	return nil
}

func (_u *ValueJSONUpdateOne) sqlSave(ctx context.Context) (_node *ValueJSON, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(valuejson.Table, valuejson.Columns, sqlgraph.NewFieldSpec(valuejson.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ValueJSON.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, valuejson.FieldID)
		for _, f := range fields {
			if !valuejson.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != valuejson.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(valuejson.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(valuejson.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(valuejson.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(valuejson.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, valuejson.FieldValue, value)
		})
	}
	if value, ok := _u.mutation.IsCover(); ok {
		_spec.SetField(valuejson.FieldIsCover, field.TypeBool, value)
	}
	if _u.mutation.CiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.CiTable,
			Columns: []string{valuejson.CiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cis.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.CiTable,
			Columns: []string{valuejson.CiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cis.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.AttributeTable,
			Columns: []string{valuejson.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttributeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   valuejson.AttributeTable,
			Columns: []string{valuejson.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ValueJSON{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuejson.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
